// Code generated by omnicore-gen. DO NOT EDIT.
//
// The ClientClaim child value object.
//
// entity:     Client
// spec:       specs/omnicore-gen/client.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-06
// checksum:   sha256:400208f1e118ef45e0d480c7b978dfc50c136354b50d28d98d9264ba7d0a99c3
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package aggregatevos

import (
	"github.com/ClaudioSchirmer/authcore/internal/domain/vos"
	"github.com/ClaudioSchirmer/omnicore/domain"
)

// ClientClaim is one entry of Client's claims collection.
//
// The claim values set on this client directly — level 1 of the two-level
// chain, read before the definition's tenant-wide default. One row per
// definition, holding the definition's id and the value.
//
// It embeds the framework's managed carrier and declares NO id field of its
// own: an exported ID here would compile, never be persisted, and never come
// back on a read.
type ClientClaim struct {
	domain.Managed
	ClaimID domain.ID      `labelKey:"ClientClaimClaimIDField"` // The claim definition this value belongs to — the id and not the name, so a retired-and-recreated definition needs an explicit re-set rather than silently inheriting a value written for the old one
	Value   vos.ClaimValue `labelKey:"ClientClaimValueField"`   // The value this client carries for the definition above. Validated against the definition's declared ValueType by a rule, since no value object can read another aggregate's field

	// Filled by the READ JOINS the repository declares — see WithJoins in
	// internal/infra. They are ordinary fields of this entry, populated on EVERY
	// load, and readable by the rules like any other; they are absent from the
	// TableSchema, so no write can carry them and no migration creates them.
	ClaimName      string // The claim's exact name as a token would carry it, prefix included. Read-only, filled on load — Claim.name, via the InnerJoin on claim_id
	ClaimValueType string // What the value beside it must parse as, per the definition. Read-only, filled on load — a stored "true" is unreadable without it — Claim.value_type, via the InnerJoin on claim_id
}

// CollectionName is the name of the claims collection.
//
// It is a constant of the TYPE, resolved once from a zero value, and it is the
// single source for the document segment, the read DTO's field and the
// notification path — so the three can never drift apart.
func (ClientClaim) CollectionName() string { return "Claims" }

// IsSameBusinessIdentity decides whether two entries are the same one.
//
// The framework matches children through this, never by comparing every field.
// It answers from the BUSINESS view, so editing a detail still leaves the
// entry recognisable and it keeps its id instead of being replaced.
func (c ClientClaim) IsSameBusinessIdentity(other domain.AggregateValueObject) bool {
	o, ok := other.(ClientClaim)
	if !ok {
		return false
	}
	return c.ClaimID == o.ClaimID
}

// BuildRules validates one ClientClaim.
//
// It runs scoped to this entry, so a notification it raises reaches the caller
// addressed to the exact position in the collection rather than to the root.
func (c *ClientClaim) BuildRules(actionName string, service domain.Service, r *domain.Rules) {
	// No rule beyond what the value objects validate on their own.
}
