// Code generated by omnicore-gen. DO NOT EDIT.
//
// The ClientRole child value object.
//
// entity:     Client
// spec:       specs/omnicore-gen/client.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-26
// checksum:   sha256:ed0e91075cf7130cc543fde0f078fc162fb1ff7a32f767127342a8876c8baa46
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package aggregatevos

import "github.com/ClaudioSchirmer/omnicore/domain"

// ClientRole is one entry of Client's roles collection.
//
// The roles granted to this client. One row per grant, holding nothing but the
// role's id — so a retired-and-recreated role is never silently re-granted.
//
// It embeds the framework's managed carrier and declares NO id field of its
// own: an exported ID here would compile, never be persisted, and never come
// back on a read.
type ClientRole struct {
	domain.Managed
	RoleID domain.ID `labelKey:"ClientRoleRoleIDField"` // The role granted to this client — the id and not the key, so a retired-and-recreated role needs an explicit re-grant

	// Filled by the READ JOINS the repository declares — see WithJoins in
	// internal/infra. They are ordinary fields of this entry, populated on EVERY
	// load, and readable by the rules like any other; they are absent from the
	// TableSchema, so no write can carry them and no migration creates them.
	RoleKey  string // The granted role's stable machine handle. Read-only, filled on load — Role.role_key, via the InnerJoin on role_id
	RoleName string // The granted role's display name. Read-only, filled on load — Role.name, via the InnerJoin on role_id
}

// CollectionName is the name of the roles collection.
//
// It is a constant of the TYPE, resolved once from a zero value, and it is the
// single source for the document segment, the read DTO's field and the
// notification path — so the three can never drift apart.
func (ClientRole) CollectionName() string { return "Roles" }

// IsSameBusinessIdentity decides whether two entries are the same one.
//
// The framework matches children through this, never by comparing every field.
// It answers from the BUSINESS view, so editing a detail still leaves the
// entry recognisable and it keeps its id instead of being replaced.
func (c ClientRole) IsSameBusinessIdentity(other domain.AggregateValueObject) bool {
	o, ok := other.(ClientRole)
	if !ok {
		return false
	}
	return c.RoleID == o.RoleID
}

// BuildRules validates one ClientRole.
//
// It runs scoped to this entry, so a notification it raises reaches the caller
// addressed to the exact position in the collection rather than to the root.
func (c ClientRole) BuildRules(actionName string, service domain.Service, r *domain.Rules) {
	// No rule beyond what the value objects validate on their own.
}
