// Code generated by omnicore-gen. DO NOT EDIT.
//
// Tests for the collection types.
//
// entity:     User
// spec:       specs/omnicore-gen/user.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-26
// checksum:   sha256:e43ccb1b2db1109c823a6345fbc02ce4306f021f2a82d82a6b0708ec455981a9
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package aggregatevos

import (
	"testing"

	"github.com/ClaudioSchirmer/omnicore/domain"
)

// userRuleHost stands in for the aggregate root so an entry can be validated
// through the framework's own seat.
//
// The real root is in internal/domain, which imports this package: importing
// it back is a cycle. What the seat needs of a root is the notification
// context and the collection index, both of which this carries.
type userRuleHost struct {
	domain.AggregateRoot
}

func (h *userRuleHost) GetAggregateRoot() *domain.AggregateRoot { return &h.AggregateRoot }

func (h *userRuleHost) AggregateChildren() []domain.AggregateValueObject {
	return []domain.AggregateValueObject{
		UserGroup{},
		UserRole{},
	}
}

// rulesForUserGroup runs one entry through the framework's own seat.
//
// Not %s.BuildRules directly. A rule may end the validation pass — the
// `guard: true` barrier — and the framework unwinds that from inside the
// seat that invoked the rules; a body called by hand would let the unwind
// escape as a panic, and every test below would fail on a rule doing exactly
// what it was declared to do.
//
// The seat also validates the entry's value objects, which is what a write
// does, so what these tests see is what the service sees.
func rulesForUserUserGroup(v UserGroup) *domain.NotificationContext {
	host := &userRuleHost{}
	domain.ValidateAggregateChild(host, v, domain.ModeInsert, "insert", nil)
	return host.GetAggregateRoot().NotificationContext()
}

// validUserGroup is one entry every rule accepts.
func validUserUserGroup() UserGroup {
	return UserGroup{
		GroupID: domain.NewID("0198f3e0-9c25-7a1f-b73d-5e08c4a29f61"),
	}
}

// UserGroup's collection name is a PERSISTED key, so it is pinned here.
//
// It is the segment the projection nests the collection under and the field a
// read DTO carries. Changing it is a data migration wearing a rename's
// clothes: the old documents keep the old key and nothing reads them back.
func TestUserUserGroup_CollectionNameIsTheDocumentKey(t *testing.T) {
	if got := (UserGroup{}).CollectionName(); got != "Groups" {
		t.Errorf("the collection is written under %q, and the documents already say %q", got, "Groups")
	}
}

// Two UserGroup entries are the same one when their business identity matches.
//
// Sameness is the business identity, never the id: the same entry typed twice
// in one request carries two ids and is still one entry, and the aggregate
// refuses the duplicate on exactly this answer.
func TestUserUserGroup_SamenessIsTheBusinessIdentity(t *testing.T) {
	a := validUserUserGroup()
	b := validUserUserGroup()
	if !a.IsSameBusinessIdentity(b) {
		t.Error("two entries with the same business identity were seen as different")
	}
	b.GroupID = domain.NewID("00000000-0000-0000-0000-000000000002")
	if a.IsSameBusinessIdentity(b) {
		t.Errorf("changing GroupID did not change the identity")
	}
}

// A well-formed UserGroup passes its own rules.
//
// The negative cases below are only meaningful if the positive one holds: a
// builder that never validates would make every rejection vacuous.
func TestUserUserGroup_ValidPasses(t *testing.T) {
	ctx := rulesForUserUserGroup(validUserUserGroup())
	if msgs := ctx.Messages(); len(msgs) > 0 {
		t.Errorf("a valid UserGroup was refused: %v", msgs)
	}
}

// rulesForUserRole runs one entry through the framework's own seat.
//
// Not %s.BuildRules directly. A rule may end the validation pass — the
// `guard: true` barrier — and the framework unwinds that from inside the
// seat that invoked the rules; a body called by hand would let the unwind
// escape as a panic, and every test below would fail on a rule doing exactly
// what it was declared to do.
//
// The seat also validates the entry's value objects, which is what a write
// does, so what these tests see is what the service sees.
func rulesForUserUserRole(v UserRole) *domain.NotificationContext {
	host := &userRuleHost{}
	domain.ValidateAggregateChild(host, v, domain.ModeInsert, "insert", nil)
	return host.GetAggregateRoot().NotificationContext()
}

// validUserRole is one entry every rule accepts.
func validUserUserRole() UserRole {
	return UserRole{
		RoleID: domain.NewID("0198f3e0-1a44-7bb2-9c31-77c0d5e1b904"),
	}
}

// UserRole's collection name is a PERSISTED key, so it is pinned here.
//
// It is the segment the projection nests the collection under and the field a
// read DTO carries. Changing it is a data migration wearing a rename's
// clothes: the old documents keep the old key and nothing reads them back.
func TestUserUserRole_CollectionNameIsTheDocumentKey(t *testing.T) {
	if got := (UserRole{}).CollectionName(); got != "Roles" {
		t.Errorf("the collection is written under %q, and the documents already say %q", got, "Roles")
	}
}

// Two UserRole entries are the same one when their business identity matches.
//
// Sameness is the business identity, never the id: the same entry typed twice
// in one request carries two ids and is still one entry, and the aggregate
// refuses the duplicate on exactly this answer.
func TestUserUserRole_SamenessIsTheBusinessIdentity(t *testing.T) {
	a := validUserUserRole()
	b := validUserUserRole()
	if !a.IsSameBusinessIdentity(b) {
		t.Error("two entries with the same business identity were seen as different")
	}
	b.RoleID = domain.NewID("00000000-0000-0000-0000-000000000002")
	if a.IsSameBusinessIdentity(b) {
		t.Errorf("changing RoleID did not change the identity")
	}
}

// A well-formed UserRole passes its own rules.
//
// The negative cases below are only meaningful if the positive one holds: a
// builder that never validates would make every rejection vacuous.
func TestUserUserRole_ValidPasses(t *testing.T) {
	ctx := rulesForUserUserRole(validUserUserRole())
	if msgs := ctx.Messages(); len(msgs) > 0 {
		t.Errorf("a valid UserRole was refused: %v", msgs)
	}
}
