// Code generated by omnicore-gen. DO NOT EDIT.
//
// The ClientAllowedCIDR input DTO.
//
// entity:     Client
// spec:       specs/omnicore-gen/client.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-29
// checksum:   sha256:230a411462b066ad0516407e7d4e73744110cf040747fe0226c325a0a03c3708
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package dtos

import (
	"github.com/ClaudioSchirmer/authcore/internal/domain/aggregatevos"
	"github.com/ClaudioSchirmer/authcore/internal/domain/vos"
)

// ClientAllowedCIDRInput carries one ClientAllowedCIDR from the application
// layer into the domain.
//
// It has no wire tags and takes no context: the wire names live on the web
// layer's request types, and the identity never reaches this far down.
type ClientAllowedCIDRInput struct {
	CIDR  string
	Label string
}

func (i ClientAllowedCIDRInput) ToClientAllowedCIDR() aggregatevos.ClientAllowedCIDR {
	return aggregatevos.ClientAllowedCIDR{
		CIDR:  vos.CIDRBlock(i.CIDR),
		Label: vos.DisplayName(i.Label),
	}
}
