// Code generated by omnicore-gen. DO NOT EDIT.
//
// The ClientAllowedCIDR input DTO.
//
// entity:     Client
// spec:       specs/omnicore-gen/client.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-26
// checksum:   sha256:13a8276c9270f452635a10d32edfa2c1b7d0b01b1ca365a9b0323a76430c4693
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package dtos

import (
	"github.com/ClaudioSchirmer/authcore/internal/domain/aggregatevos"
	"github.com/ClaudioSchirmer/authcore/internal/domain/vos"
)

// ClientAllowedCIDRInput carries one ClientAllowedCIDR from the application
// layer into the domain.
//
// It has no wire tags and takes no context: the wire names live on the web
// layer's request types, and the identity never reaches this far down.
type ClientAllowedCIDRInput struct {
	CIDR  string
	Label string
}

func (i ClientAllowedCIDRInput) ToClientAllowedCIDR() aggregatevos.ClientAllowedCIDR {
	return aggregatevos.ClientAllowedCIDR{
		CIDR:  vos.CIDRBlock(i.CIDR),
		Label: vos.DisplayName(i.Label),
	}
}
