// Code generated by omnicore-gen. DO NOT EDIT.
//
// The ClientClaim input DTO.
//
// entity:     Client
// spec:       specs/omnicore-gen/client.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-28
// checksum:   sha256:5a0057edad54d8b463994299472edbf7db16d916fb5d3dffbaf396b08086a75c
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package dtos

import (
	"github.com/ClaudioSchirmer/authcore/internal/domain/aggregatevos"
	"github.com/ClaudioSchirmer/authcore/internal/domain/vos"
	"github.com/ClaudioSchirmer/omnicore/domain"
)

// ClientClaimInput carries one ClientClaim from the application layer into the
// domain.
//
// It has no wire tags and takes no context: the wire names live on the web
// layer's request types, and the identity never reaches this far down.
type ClientClaimInput struct {
	ClaimID domain.ID
	Value   string
}

func (i ClientClaimInput) ToClientClaim() aggregatevos.ClientClaim {
	return aggregatevos.ClientClaim{
		ClaimID: i.ClaimID,
		Value:   vos.ClaimValue(i.Value),
	}
}
