// Code generated by omnicore-gen. DO NOT EDIT.
//
// The RolePermission input DTO.
//
// entity:     Role
// spec:       specs/omnicore-gen/role.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-21
// checksum:   sha256:0c9d340a0a7c5a513b89ce576ec62814f15fffb44a381ad4d71f94a0580e7b07
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package dtos

import (
	"github.com/ClaudioSchirmer/authcore/internal/domain/aggregatevos"
	"github.com/ClaudioSchirmer/omnicore/domain"
)

// RolePermissionInput carries one RolePermission from the application layer
// into the domain.
//
// It has no wire tags and takes no context: the wire names live on the web
// layer's request types, and the identity never reaches this far down.
type RolePermissionInput struct {
	PermissionID domain.ID
}

func (i RolePermissionInput) ToRolePermission() aggregatevos.RolePermission {
	return aggregatevos.RolePermission{
		PermissionID: i.PermissionID,
	}
}
