// Code generated by omnicore-gen. DO NOT EDIT.
//
// Tests for the user_group_input mapper.
//
// entity:     User
// spec:       specs/omnicore-gen/user.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-01
// checksum:   sha256:dad846b627a1e8fe7414bd039597588a4766c10cf02e35f3095aa32e632b93b3
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package dtos

import (
	"github.com/ClaudioSchirmer/omnicore/domain"
	"testing"
)

// A UserGroup entry carries every field it was sent with.
//
// A field added to the collection and forgotten in this mapper is accepted on
// the wire, saved without it, and reported nowhere.
func TestUserUserGroupInputCarriesEveryField(t *testing.T) {
	in := UserGroupInput{
		GroupID: domain.NewID("0198f3e0-9c25-7a1f-b73d-5e08c4a29f61"),
	}
	got := in.ToUserGroup()
	if got.GroupID != domain.NewID("0198f3e0-9c25-7a1f-b73d-5e08c4a29f61") {
		t.Errorf("GroupID did not survive the mapper")
	}
}
