// Code generated by omnicore-gen. DO NOT EDIT.
//
// The UserRole input DTO.
//
// entity:     User
// spec:       specs/omnicore-gen/user.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-26
// checksum:   sha256:d179f4acf2a21747a8fcadf033c6edc9cf23cd661f986ceebb5280a4a809c526
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package dtos

import (
	"github.com/ClaudioSchirmer/authcore/internal/domain/aggregatevos"
	"github.com/ClaudioSchirmer/omnicore/domain"
)

// UserRoleInput carries one UserRole from the application layer into the
// domain.
//
// It has no wire tags and takes no context: the wire names live on the web
// layer's request types, and the identity never reaches this far down.
type UserRoleInput struct {
	RoleID domain.ID
}

func (i UserRoleInput) ToUserRole() aggregatevos.UserRole {
	return aggregatevos.UserRole{
		RoleID: i.RoleID,
	}
}
