// Code generated by omnicore-gen. DO NOT EDIT.
//
// Tests for the 2 collection input mapper(s).
//
// entity:     User
// spec:       specs/omnicore-gen/user.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-26
// checksum:   sha256:130ee5ed15e4d20d8c1fc00a4feb09bfcf15c43e8d0827dfbed8eb794364b33f
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package dtos

import (
	"github.com/ClaudioSchirmer/omnicore/domain"
	"testing"
)

// A UserGroup entry carries every field it was sent with.
//
// A field added to the collection and forgotten in this mapper is accepted on
// the wire, saved without it, and reported nowhere.
func TestUserUserGroupInputCarriesEveryField(t *testing.T) {
	in := UserGroupInput{
		GroupID: domain.NewID("0198f3e0-9c25-7a1f-b73d-5e08c4a29f61"),
	}
	got := in.ToUserGroup()
	if got.GroupID != domain.NewID("0198f3e0-9c25-7a1f-b73d-5e08c4a29f61") {
		t.Errorf("GroupID did not survive the mapper")
	}
}

// A UserRole entry carries every field it was sent with.
//
// A field added to the collection and forgotten in this mapper is accepted on
// the wire, saved without it, and reported nowhere.
func TestUserUserRoleInputCarriesEveryField(t *testing.T) {
	in := UserRoleInput{
		RoleID: domain.NewID("0198f3e0-1a44-7bb2-9c31-77c0d5e1b904"),
	}
	got := in.ToUserRole()
	if got.RoleID != domain.NewID("0198f3e0-1a44-7bb2-9c31-77c0d5e1b904") {
		t.Errorf("RoleID did not survive the mapper")
	}
}
