// Code generated by omnicore-gen. DO NOT EDIT.
//
// The 5 claim endpoints.
//
// entity:     Claim
// spec:       specs/omnicore-gen/claim.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-29
// checksum:   sha256:04d302adc216de307fa2ceb7396df223517f2811abb0dff5fdd5e89180e32f1b
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package web

import (
	"github.com/ClaudioSchirmer/omnicore/application/handlers"
	"github.com/ClaudioSchirmer/omnicore/application/persistence"
	fwresults "github.com/ClaudioSchirmer/omnicore/application/results"
	"github.com/ClaudioSchirmer/omnicore/bootstrap"
	"github.com/ClaudioSchirmer/omnicore/domain"
	"github.com/ClaudioSchirmer/omnicore/infra/db/query"
	fwweb "github.com/ClaudioSchirmer/omnicore/web"
	fwopenapi "github.com/ClaudioSchirmer/omnicore/web/openapi"
	fwresponses "github.com/ClaudioSchirmer/omnicore/web/responses"

	"github.com/ClaudioSchirmer/authcore/internal/application/commands"
	appqueries "github.com/ClaudioSchirmer/authcore/internal/application/queries"
	appdomain "github.com/ClaudioSchirmer/authcore/internal/domain"
	"github.com/ClaudioSchirmer/authcore/internal/web/requests"
	fwgraphql "github.com/ClaudioSchirmer/omnicore/web/graphql"
	"github.com/gofiber/fiber/v3"
)

// MountClaims registers every claim endpoint.
//
// The repository arrives as an interface, not as the concrete infra type: the
// web layer must not depend on infra.
func MountClaims(
	app *fiber.App,
	repo persistence.ScopedRepository[*appdomain.Claim],
	svc domain.Service,
	view *query.RelationalViewDefinition,
	d bootstrap.Deps,
) {
	group := app.Group("/claims")
	viewName := view.Name()

	insertH, insertSpec := fwweb.CommandWithBodySpec(d.Pipeline,
		requests.InsertClaimRequest{},
		requests.InsertClaimResponse{}.FromResult,
		&handlers.InsertCommandHandler[*appdomain.Claim, *commands.InsertClaimCommand, commands.InsertClaimResult]{
			Repo: repo, Service: svc,
		}, fiber.StatusCreated)
	fwopenapi.Mount(d.OpenAPIRegistry, group, fiber.MethodPost, "/",
		insertH, insertSpec,
		fwopenapi.Doc{
			Summary:     "Create a claim",
			Description: "Creates a claim and returns it as stored — the response reflects any value the domain normalised or defaulted, not an echo of the request.",
			Tags:        []string{"Claims"},
		},
		fwopenapi.RequirePermission("claim:insert"))

	patchH, patchSpec := fwweb.CommandWithBodyIDSpec(d.Pipeline,
		requests.PatchClaimRequest{},
		requests.PatchClaimResponse{}.FromResult,
		&handlers.PartialUpdateCommandHandler[*appdomain.Claim, *commands.PatchClaimCommand, commands.PatchClaimResult]{
			Repo: repo, Service: svc,
		}, fiber.StatusOK)
	fwopenapi.Mount(d.OpenAPIRegistry, group, fiber.MethodPatch, "/:id",
		patchH, patchSpec,
		fwopenapi.Doc{
			Summary:     "Update a claim (partial)",
			Description: "Partial update: only the fields present in the body change. Because an absent field and an explicit null cannot be told apart here, this verb cannot set a value back to null.",
			Tags:        []string{"Claims"},
		},
		fwopenapi.RequirePermission("claim:update"))

	archiveH, archiveSpec := fwweb.CommandByIDSpec(d.Pipeline,
		fwresponses.NoBody,
		&handlers.ArchiveCommandHandler[*appdomain.Claim, *commands.ArchiveClaimCommand, fwresults.None]{
			Repo: repo, Service: svc,
		}, fiber.StatusNoContent)
	fwopenapi.Mount(d.OpenAPIRegistry, group, fiber.MethodPatch, "/:id/archive",
		archiveH, archiveSpec,
		fwopenapi.Doc{
			Summary:     "Archive a claim",
			Description: "Archives the claim: the row stays but is hidden from reads unless they ask for archived rows. This service mounts no unarchive: the row stays as history and nothing brings it back into the active set.",
			Tags:        []string{"Claims"},
		},
		fwopenapi.RequirePermission("claim:archive"))

	byParamsH, byParamsSpec := fwweb.QueryWithParamsSpec(d.Pipeline,
		requests.FindClaimsRequest{},
		requests.FindClaimsResponse{}.FromResult,
		&handlers.FindByParamsQueryHandler[*appqueries.FindClaimsByParamsQuery, appqueries.FindClaimsByParamsResult]{
			Reader: d.ViewReader, View: viewName,
		})
	fwopenapi.Mount(d.OpenAPIRegistry, group, fiber.MethodGet, "/",
		byParamsH, byParamsSpec,
		fwopenapi.Doc{
			Summary:     "List claims",
			Description: "Paged listing of claims. Unknown filter keys and operators are rejected with a typed 400 rather than silently ignored.",
			Tags:        []string{"Claims"},
		},
		fwopenapi.RequirePermission("claim:read"))

	byIdH, byIdSpec := fwweb.QueryByIDSpec(d.Pipeline,
		requests.FindClaimByIDRequest{},
		requests.FindClaimByIDResponse{}.FromResult,
		&handlers.FindByIDQueryHandler[*appqueries.FindClaimByIDQuery, appqueries.FindClaimByIDResult]{
			Reader: d.ViewReader, View: viewName,
		})
	fwopenapi.Mount(d.OpenAPIRegistry, group, fiber.MethodGet, "/:id",
		byIdH, byIdSpec,
		fwopenapi.Doc{
			Summary:     "Get a claim by id",
			Description: "Reads one claim. Only the controls this endpoint declares are accepted; anything else is rejected with a typed 400.",
			Tags:        []string{"Claims"},
		},
		fwopenapi.RequirePermission("claim:read"))

}

// MountClaimsGraphQL exposes claim on the GraphQL surface.
//
// Every field here reuses the handler its REST twin uses, with the same
// permission attached. There is no second implementation to keep in step.
func MountClaimsGraphQL(
	reg *fwgraphql.Registry,
	repo persistence.ScopedRepository[*appdomain.Claim],
	svc domain.Service,
	view *query.RelationalViewDefinition,
	d bootstrap.Deps,
) {
	// A paged connection over the same view the REST listing reads — same
	// handler, same Response, so the node type and the JSON body cannot drift.
	reg.Register(fwgraphql.QueryWithParams[requests.FindClaimsRequest](
		"claims", "Claim",
		requests.FindClaimsResponse{}.FromResult,
		&handlers.FindByParamsQueryHandler[*appqueries.FindClaimsByParamsQuery, appqueries.FindClaimsByParamsResult]{
			Reader: d.ViewReader, View: view.Name(),
		},
		fwgraphql.RequirePermission("claim:read")))

	// The singular twin of the connection: one nullable node, the same
	// entity name, so both fields resolve to ONE type in the schema. A
	// missing id answers null with the canonical not-found in errors[].
	reg.Register(fwgraphql.QueryByID[requests.FindClaimByIDRequest](
		"claim", "Claim",
		requests.FindClaimByIDResponse{}.FromResult,
		&handlers.FindByIDQueryHandler[*appqueries.FindClaimByIDQuery, appqueries.FindClaimByIDResult]{
			Reader: d.ViewReader, View: view.Name(),
		},
		fwgraphql.RequirePermission("claim:read")))

	reg.Register(fwgraphql.MutationWithBody[requests.InsertClaimRequest](
		"createClaim", requests.InsertClaimResponse{}.FromResult,
		&handlers.InsertCommandHandler[*appdomain.Claim, *commands.InsertClaimCommand, commands.InsertClaimResult]{
			Repo: repo, Service: svc,
		},
		fwgraphql.RequirePermission("claim:insert")))

	reg.Register(fwgraphql.MutationWithBodyID[requests.PatchClaimRequest](
		"patchClaim", requests.PatchClaimResponse{}.FromResult,
		&handlers.PartialUpdateCommandHandler[*appdomain.Claim, *commands.PatchClaimCommand, commands.PatchClaimResult]{
			Repo: repo, Service: svc,
		},
		fwgraphql.RequirePermission("claim:update")))

	reg.Register(fwgraphql.MutationByID(
		"archiveClaim",
		&handlers.ArchiveCommandHandler[*appdomain.Claim, *commands.ArchiveClaimCommand, fwresults.None]{
			Repo: repo, Service: svc,
		},
		fwgraphql.RequirePermission("claim:archive")))

}
