// Code generated by omnicore-gen. DO NOT EDIT.
//
// The 5 group endpoints.
//
// entity:     Group
// spec:       specs/omnicore-gen/group.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-01
// checksum:   sha256:62690a70a860ae2bd34ebc27951be880fa7a922348db3a28521e97e9feeb8787
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package web

import (
	"github.com/ClaudioSchirmer/omnicore/application/handlers"
	"github.com/ClaudioSchirmer/omnicore/application/persistence"
	fwresults "github.com/ClaudioSchirmer/omnicore/application/results"
	"github.com/ClaudioSchirmer/omnicore/bootstrap"
	"github.com/ClaudioSchirmer/omnicore/domain"
	"github.com/ClaudioSchirmer/omnicore/infra/db/query"
	fwweb "github.com/ClaudioSchirmer/omnicore/web"
	fwopenapi "github.com/ClaudioSchirmer/omnicore/web/openapi"
	fwresponses "github.com/ClaudioSchirmer/omnicore/web/responses"

	"github.com/ClaudioSchirmer/authcore/internal/application/commands"
	appqueries "github.com/ClaudioSchirmer/authcore/internal/application/queries"
	appdomain "github.com/ClaudioSchirmer/authcore/internal/domain"
	"github.com/ClaudioSchirmer/authcore/internal/web/requests"
	fwgraphql "github.com/ClaudioSchirmer/omnicore/web/graphql"
	"github.com/gofiber/fiber/v3"
)

// MountGroups registers every group endpoint.
//
// The repository arrives as an interface, not as the concrete infra type: the
// web layer must not depend on infra.
func MountGroups(
	app *fiber.App,
	repo persistence.ScopedRepository[*appdomain.Group],
	svc domain.Service,
	view *query.RelationalViewDefinition,
	d bootstrap.Deps,
) {
	group := app.Group("/groups")
	viewName := view.Name()

	insertH, insertSpec := fwweb.CommandWithBodySpec(d.Pipeline,
		requests.InsertGroupRequest{},
		requests.InsertGroupResponse{}.FromResult,
		&handlers.InsertCommandHandler[*appdomain.Group, *commands.InsertGroupCommand, commands.InsertGroupResult]{
			Repo: repo, Service: svc,
		}, fiber.StatusCreated)
	fwopenapi.Mount(d.OpenAPIRegistry, group, fiber.MethodPost, "/",
		insertH, insertSpec,
		fwopenapi.Doc{
			Summary:     "Create a group",
			Description: "Creates a group and returns it as stored — the response reflects any value the domain normalised or defaulted, not an echo of the request.",
			Tags:        []string{"Groups"},
		},
		fwopenapi.RequirePermission("group:insert"))

	patchH, patchSpec := fwweb.CommandWithBodyIDSpec(d.Pipeline,
		requests.PatchGroupRequest{},
		requests.PatchGroupResponse{}.FromResult,
		&handlers.PartialUpdateCommandHandler[*appdomain.Group, *commands.PatchGroupCommand, commands.PatchGroupResult]{
			Repo: repo, Service: svc,
		}, fiber.StatusOK)
	fwopenapi.Mount(d.OpenAPIRegistry, group, fiber.MethodPatch, "/:id",
		patchH, patchSpec,
		fwopenapi.Doc{
			Summary:     "Update a group (partial)",
			Description: "Partial update: only the fields present in the body change. Because an absent field and an explicit null cannot be told apart here, this verb cannot set a value back to null.",
			Tags:        []string{"Groups"},
		},
		fwopenapi.RequirePermission("group:update"))

	archiveH, archiveSpec := fwweb.CommandByIDSpec(d.Pipeline,
		fwresponses.NoBody,
		&handlers.ArchiveCommandHandler[*appdomain.Group, *commands.ArchiveGroupCommand, fwresults.None]{
			Repo: repo, Service: svc,
		}, fiber.StatusNoContent)
	fwopenapi.Mount(d.OpenAPIRegistry, group, fiber.MethodPatch, "/:id/archive",
		archiveH, archiveSpec,
		fwopenapi.Doc{
			Summary:     "Archive a group",
			Description: "Archives the group: the row stays but is hidden from reads unless they ask for archived rows. This service mounts no unarchive: the row stays as history and nothing brings it back into the active set.",
			Tags:        []string{"Groups"},
		},
		fwopenapi.RequirePermission("group:archive"))

	byParamsH, byParamsSpec := fwweb.QueryWithParamsSpec(d.Pipeline,
		requests.FindGroupsRequest{},
		requests.FindGroupsResponse{}.FromResult,
		&handlers.FindByParamsQueryHandler[*appqueries.FindGroupsByParamsQuery, appqueries.FindGroupsByParamsResult]{
			Reader: d.ViewReader, View: viewName,
		})
	fwopenapi.Mount(d.OpenAPIRegistry, group, fiber.MethodGet, "/",
		byParamsH, byParamsSpec,
		fwopenapi.Doc{
			Summary:     "List groups",
			Description: "Paged listing of groups. Unknown filter keys and operators are rejected with a typed 400 rather than silently ignored.",
			Tags:        []string{"Groups"},
		},
		fwopenapi.RequirePermission("group:read"))

	byIdH, byIdSpec := fwweb.QueryByIDSpec(d.Pipeline,
		requests.FindGroupByIDRequest{},
		requests.FindGroupByIDResponse{}.FromResult,
		&handlers.FindByIDQueryHandler[*appqueries.FindGroupByIDQuery, appqueries.FindGroupByIDResult]{
			Reader: d.ViewReader, View: viewName,
		})
	fwopenapi.Mount(d.OpenAPIRegistry, group, fiber.MethodGet, "/:id",
		byIdH, byIdSpec,
		fwopenapi.Doc{
			Summary:     "Get a group by id",
			Description: "Reads one group. Only the controls this endpoint declares are accepted; anything else is rejected with a typed 400.",
			Tags:        []string{"Groups"},
		},
		fwopenapi.RequirePermission("group:read"))

	hAddGroupRole, sAddGroupRole := fwweb.CommandWithBodyIDSpec(d.Pipeline,
		requests.AddGroupRoleRequest{},
		requests.AddGroupRoleResponse{}.FromResult,
		&handlers.UpdateCommandHandler[*appdomain.Group, *commands.AddGroupRoleCommand, commands.AddGroupRoleResult]{
			Repo: repo, Service: svc,
		}, fiber.StatusCreated)
	fwopenapi.Mount(d.OpenAPIRegistry, group, fiber.MethodPost, "/:id/roles",
		hAddGroupRole, sAddGroupRole,
		fwopenapi.Doc{
			Summary:     "Add one GroupRole to a Group",
			Description: "Adds ONE entry to the roles collection of an existing Group, in the owner's transaction. 404 when the owner is not there. The response carries the entry AS STORED, including the id the server minted for it — that id is how the caller addresses it afterwards.",
			Tags:        []string{"Groups"},
		},
		fwopenapi.RequirePermission("group:grant"))

	hArchiveGroupRole, sArchiveGroupRole := fwweb.CommandWithBodyIDSpec(d.Pipeline,
		requests.ArchiveGroupRoleRequest{},
		fwresponses.NoBody,
		&handlers.UpdateCommandHandler[*appdomain.Group, *commands.ArchiveGroupRoleCommand, fwresults.None]{
			Repo: repo, Service: svc,
		}, fiber.StatusNoContent)
	fwopenapi.Mount(d.OpenAPIRegistry, group, fiber.MethodPatch, "/:id/roles/:groupRoleId/archive",
		hArchiveGroupRole, sArchiveGroupRole,
		fwopenapi.Doc{
			Summary:     "Archive one GroupRole of a Group",
			Description: "Archives ONE entry: the row stays, stamped, and stops being returned — which is why this is not a DELETE. There is no per-entry unarchive: an entry taken out this way does not come back, and adding the same value again mints a NEW entry with a new id. Answers 204 with no body. 404 when the owner is not there, and 404 when it holds no entry with that id.",
			Tags:        []string{"Groups"},
		},
		fwopenapi.RequirePermission("group:grant"))

}

// MountGroupsGraphQL exposes group on the GraphQL surface.
//
// Every field here reuses the handler its REST twin uses, with the same
// permission attached. There is no second implementation to keep in step.
func MountGroupsGraphQL(
	reg *fwgraphql.Registry,
	repo persistence.ScopedRepository[*appdomain.Group],
	svc domain.Service,
	view *query.RelationalViewDefinition,
	d bootstrap.Deps,
) {
	// A paged connection over the same view the REST listing reads — same
	// handler, same Response, so the node type and the JSON body cannot drift.
	reg.Register(fwgraphql.QueryWithParams[requests.FindGroupsRequest](
		"groups", "Group",
		requests.FindGroupsResponse{}.FromResult,
		&handlers.FindByParamsQueryHandler[*appqueries.FindGroupsByParamsQuery, appqueries.FindGroupsByParamsResult]{
			Reader: d.ViewReader, View: view.Name(),
		},
		fwgraphql.RequirePermission("group:read")))

	// The singular twin of the connection: one nullable node, the same
	// entity name, so both fields resolve to ONE type in the schema. A
	// missing id answers null with the canonical not-found in errors[].
	reg.Register(fwgraphql.QueryByID[requests.FindGroupByIDRequest](
		"group", "Group",
		requests.FindGroupByIDResponse{}.FromResult,
		&handlers.FindByIDQueryHandler[*appqueries.FindGroupByIDQuery, appqueries.FindGroupByIDResult]{
			Reader: d.ViewReader, View: view.Name(),
		},
		fwgraphql.RequirePermission("group:read")))

	reg.Register(fwgraphql.MutationWithBody[requests.InsertGroupRequest](
		"createGroup", requests.InsertGroupResponse{}.FromResult,
		&handlers.InsertCommandHandler[*appdomain.Group, *commands.InsertGroupCommand, commands.InsertGroupResult]{
			Repo: repo, Service: svc,
		},
		fwgraphql.RequirePermission("group:insert")))

	reg.Register(fwgraphql.MutationWithBodyID[requests.PatchGroupRequest](
		"patchGroup", requests.PatchGroupResponse{}.FromResult,
		&handlers.PartialUpdateCommandHandler[*appdomain.Group, *commands.PatchGroupCommand, commands.PatchGroupResult]{
			Repo: repo, Service: svc,
		},
		fwgraphql.RequirePermission("group:update")))

	reg.Register(fwgraphql.MutationByID(
		"archiveGroup",
		&handlers.ArchiveCommandHandler[*appdomain.Group, *commands.ArchiveGroupCommand, fwresults.None]{
			Repo: repo, Service: svc,
		},
		fwgraphql.RequirePermission("group:archive")))

	// The entry is the whole input; the owner is the id. The REST route's
	// own Request travels unchanged — it carries no path segment to lose.
	reg.Register(fwgraphql.MutationWithBodyID[requests.AddGroupRoleRequest](
		"addGroupRole", requests.AddGroupRoleResponse{}.FromResult,
		&handlers.UpdateCommandHandler[*appdomain.Group, *commands.AddGroupRoleCommand, commands.AddGroupRoleResult]{
			Repo: repo, Service: svc,
		},
		fwgraphql.RequirePermission("group:grant")))

	// REST answers 204 with no body; a GraphQL field must answer SOMETHING,
	// so the payload is the acknowledgement and nothing more. The field is
	// named for what the removal DOES here — archive or delete — the same
	// way the REST verb is.
	reg.Register(fwgraphql.MutationWithBodyID[requests.ArchiveGroupRoleGraphQLRequest](
		"archiveGroupRole", requests.ArchiveGroupRoleGraphQLResponse{}.FromResult,
		&handlers.UpdateCommandHandler[*appdomain.Group, *commands.ArchiveGroupRoleCommand, fwresults.None]{
			Repo: repo, Service: svc,
		},
		fwgraphql.RequirePermission("group:grant")))

}
