// Code generated by omnicore-gen. DO NOT EDIT.
//
// The 5 permission endpoints.
//
// entity:     Permission
// spec:       specs/omnicore-gen/permission.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-03
// checksum:   sha256:04d8cdd6567d6d428c357817790825005562eab60e21c45919b5ca7a281f30fb
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package web

import (
	"github.com/ClaudioSchirmer/omnicore/application/handlers"
	"github.com/ClaudioSchirmer/omnicore/application/persistence"
	fwresults "github.com/ClaudioSchirmer/omnicore/application/results"
	"github.com/ClaudioSchirmer/omnicore/bootstrap"
	"github.com/ClaudioSchirmer/omnicore/domain"
	"github.com/ClaudioSchirmer/omnicore/infra/db/query"
	fwweb "github.com/ClaudioSchirmer/omnicore/web"
	fwopenapi "github.com/ClaudioSchirmer/omnicore/web/openapi"
	fwresponses "github.com/ClaudioSchirmer/omnicore/web/responses"

	"github.com/ClaudioSchirmer/authcore/internal/application/commands"
	appqueries "github.com/ClaudioSchirmer/authcore/internal/application/queries"
	appdomain "github.com/ClaudioSchirmer/authcore/internal/domain"
	"github.com/ClaudioSchirmer/authcore/internal/web/requests"
	fwgraphql "github.com/ClaudioSchirmer/omnicore/web/graphql"
	"github.com/gofiber/fiber/v3"
)

// MountPermissions registers every permission endpoint.
//
// The repository arrives as an interface, not as the concrete infra type: the
// web layer must not depend on infra.
func MountPermissions(
	app *fiber.App,
	repo persistence.ScopedRepository[*appdomain.Permission],
	svc domain.Service,
	view *query.RelationalViewDefinition,
	d bootstrap.Deps,
) {
	group := app.Group("/permissions")
	viewName := view.Name()

	insertH, insertSpec := fwweb.CommandWithBodySpec(d.Pipeline,
		requests.InsertPermissionRequest{},
		requests.InsertPermissionResponse{}.FromResult,
		&handlers.InsertCommandHandler[*appdomain.Permission, *commands.InsertPermissionCommand, commands.InsertPermissionResult]{
			Repo: repo, Service: svc,
		}, fiber.StatusCreated)
	fwopenapi.Mount(d.OpenAPIRegistry, group, fiber.MethodPost, "/",
		insertH, insertSpec,
		fwopenapi.Doc{
			Summary: "Create a permission",
			Description: "Creates a permission and returns it as stored — the response reflects any value the domain normalised or defaulted, not an echo of the request.\n\n" +
				"**A permission is `resource:action`** — one pair, written as two keys.\n\n" +
				"- `resource` — what is protected, as the enforcing route names it: `tenant`,\n  `user:profile`, or `*` for every resource.\n- `action` — what may be done to it: `read`, `insert`, or `*` for every action.\n- `permission` — the two joined, `tenant:read`. This is the string a JWT claim carries\n  and a route compares against, byte for byte. Reads return it; no request sends it.\n\n" +
				"A rejection therefore names one of three fields, and which one tells you what to fix:\n`resource` or `action` when that half is malformed on its own, and `permission` when the\ncomplaint is about the PAIR — it is already taken, or it cannot match anything.\n\n" +
				"Send the two halves separately. They are refused, never repaired: `Tenant`, ` tenant `\nand `tenant:*` are all rejected rather than cleaned up, because the rendered pair is\ncompared byte for byte against a token claim and a quietly repaired value would\nauthorize nothing and explain nothing.\n\n" +
				"A pair the catalog already holds answers **409**, naming `permission` and handing the\nrefused pair back as `resource:action`. Only ACTIVE rows hold a pair: archiving one\nfrees it, and re-inserting is the only way a retired permission comes back — as a new\nrow, with a new id.\n\n" +
				"A wildcard `*` is accepted as an ENTIRE half and nowhere else, and a `*` resource\nforces a `*` action: `*:read` is refused, because the claim matcher honours exactly\n`resource:action`, `resource:*` and `*:*`, so such a row would match no route while\nreading like a sweeping grant.",
			Tags: []string{"Permissions"},
		},
		fwopenapi.RequirePermission("permission:insert"))

	patchH, patchSpec := fwweb.CommandWithBodyIDSpec(d.Pipeline,
		requests.PatchPermissionRequest{},
		requests.PatchPermissionResponse{}.FromResult,
		&handlers.PartialUpdateCommandHandler[*appdomain.Permission, *commands.PatchPermissionCommand, commands.PatchPermissionResult]{
			Repo: repo, Service: svc,
		}, fiber.StatusOK)
	fwopenapi.Mount(d.OpenAPIRegistry, group, fiber.MethodPatch, "/:id",
		patchH, patchSpec,
		fwopenapi.Doc{
			Summary: "Update a permission (partial)",
			Description: "Partial update: only the fields present in the body change. Because an absent field and an explicit null cannot be told apart here, this verb cannot set a value back to null.\n\n" +
				"**A permission is `resource:action`** — one pair, written as two keys.\n\n" +
				"- `resource` — what is protected, as the enforcing route names it: `tenant`,\n  `user:profile`, or `*` for every resource.\n- `action` — what may be done to it: `read`, `insert`, or `*` for every action.\n- `permission` — the two joined, `tenant:read`. This is the string a JWT claim carries\n  and a route compares against, byte for byte. Reads return it; no request sends it.\n\n" +
				"A rejection therefore names one of three fields, and which one tells you what to fix:\n`resource` or `action` when that half is malformed on its own, and `permission` when the\ncomplaint is about the PAIR — it is already taken, or it cannot match anything.\n\n" +
				"**The pair cannot be changed** — `resource` and `action` are not part of this body, and\nsending them changes nothing. The pair IS the permission's identity in every issued\ntoken and every existing grant, so editing it would rewrite what all of them mean,\nretroactively and invisibly. A permission that should say something else is a new one.\n\n" +
				"The description is editable, and that is the whole of this operation.",
			Tags: []string{"Permissions"},
		},
		fwopenapi.RequirePermission("permission:update"))

	archiveH, archiveSpec := fwweb.CommandByIDSpec(d.Pipeline,
		fwresponses.NoBody,
		&handlers.ArchiveCommandHandler[*appdomain.Permission, *commands.ArchivePermissionCommand, fwresults.None]{
			Repo: repo, Service: svc,
		}, fiber.StatusNoContent)
	fwopenapi.Mount(d.OpenAPIRegistry, group, fiber.MethodPatch, "/:id/archive",
		archiveH, archiveSpec,
		fwopenapi.Doc{
			Summary: "Archive a permission",
			Description: "Archives the permission: the row stays but is hidden from reads unless they ask for archived rows. This service mounts no unarchive: the row stays as history and nothing brings it back into the active set.\n\n" +
				"**A permission is `resource:action`** — one pair, written as two keys.\n\n" +
				"- `resource` — what is protected, as the enforcing route names it: `tenant`,\n  `user:profile`, or `*` for every resource.\n- `action` — what may be done to it: `read`, `insert`, or `*` for every action.\n- `permission` — the two joined, `tenant:read`. This is the string a JWT claim carries\n  and a route compares against, byte for byte. Reads return it; no request sends it.\n\n" +
				"A rejection therefore names one of three fields, and which one tells you what to fix:\n`resource` or `action` when that half is malformed on its own, and `permission` when the\ncomplaint is about the PAIR — it is already taken, or it cannot match anything.",
			Tags: []string{"Permissions"},
		},
		fwopenapi.RequirePermission("permission:archive"))

	byParamsH, byParamsSpec := fwweb.QueryWithParamsSpec(d.Pipeline,
		requests.FindPermissionsRequest{},
		requests.FindPermissionsResponse{}.FromResult,
		&handlers.FindByParamsQueryHandler[*appqueries.FindPermissionsByParamsQuery, appqueries.FindPermissionsByParamsResult]{
			Reader: d.ViewReader, View: viewName,
		})
	fwopenapi.Mount(d.OpenAPIRegistry, group, fiber.MethodGet, "/",
		byParamsH, byParamsSpec,
		fwopenapi.Doc{
			Summary: "List permissions",
			Description: "Paged listing of permissions. Unknown filter keys and operators are rejected with a typed 400 rather than silently ignored.\n\n" +
				"**A permission is `resource:action`** — one pair, written as two keys.\n\n" +
				"- `resource` — what is protected, as the enforcing route names it: `tenant`,\n  `user:profile`, or `*` for every resource.\n- `action` — what may be done to it: `read`, `insert`, or `*` for every action.\n- `permission` — the two joined, `tenant:read`. This is the string a JWT claim carries\n  and a route compares against, byte for byte. Reads return it; no request sends it.\n\n" +
				"A rejection therefore names one of three fields, and which one tells you what to fix:\n`resource` or `action` when that half is malformed on its own, and `permission` when the\ncomplaint is about the PAIR — it is already taken, or it cannot match anything.\n\n" +
				"Filter and sort the two HALVES — `?filter[resource][eq]=tenant`,\n`?filter[action][in]=read,insert`, `?orderBy=resource`. The rendered `permission` is\nderived per row and backs no column, so it can be SELECTED (`?fields=permission`) but\nnever filtered or ordered; asking for either answers a typed 400.",
			Tags: []string{"Permissions"},
		},
		fwopenapi.RequirePermission("permission:read"))

	byIdH, byIdSpec := fwweb.QueryByIDSpec(d.Pipeline,
		requests.FindPermissionByIDRequest{},
		requests.FindPermissionByIDResponse{}.FromResult,
		&handlers.FindByIDQueryHandler[*appqueries.FindPermissionByIDQuery, appqueries.FindPermissionByIDResult]{
			Reader: d.ViewReader, View: viewName,
		})
	fwopenapi.Mount(d.OpenAPIRegistry, group, fiber.MethodGet, "/:id",
		byIdH, byIdSpec,
		fwopenapi.Doc{
			Summary: "Get a permission by id",
			Description: "Reads one permission. Only the controls this endpoint declares are accepted; anything else is rejected with a typed 400.\n\n" +
				"**A permission is `resource:action`** — one pair, written as two keys.\n\n" +
				"- `resource` — what is protected, as the enforcing route names it: `tenant`,\n  `user:profile`, or `*` for every resource.\n- `action` — what may be done to it: `read`, `insert`, or `*` for every action.\n- `permission` — the two joined, `tenant:read`. This is the string a JWT claim carries\n  and a route compares against, byte for byte. Reads return it; no request sends it.\n\n" +
				"A rejection therefore names one of three fields, and which one tells you what to fix:\n`resource` or `action` when that half is malformed on its own, and `permission` when the\ncomplaint is about the PAIR — it is already taken, or it cannot match anything.",
			Tags: []string{"Permissions"},
		},
		fwopenapi.RequirePermission("permission:read"))

}

// MountPermissionsGraphQL exposes permission on the GraphQL surface.
//
// Every field here reuses the handler its REST twin uses, with the same
// permission attached. There is no second implementation to keep in step.
func MountPermissionsGraphQL(
	reg *fwgraphql.Registry,
	repo persistence.ScopedRepository[*appdomain.Permission],
	svc domain.Service,
	view *query.RelationalViewDefinition,
	d bootstrap.Deps,
) {
	// A paged connection over the same view the REST listing reads — same
	// handler, same Response, so the node type and the JSON body cannot drift.
	reg.Register(fwgraphql.QueryWithParams[requests.FindPermissionsRequest](
		"permissions", "Permission",
		requests.FindPermissionsResponse{}.FromResult,
		&handlers.FindByParamsQueryHandler[*appqueries.FindPermissionsByParamsQuery, appqueries.FindPermissionsByParamsResult]{
			Reader: d.ViewReader, View: view.Name(),
		},
		fwgraphql.RequirePermission("permission:read")))

	// The singular twin of the connection: one nullable node, the same
	// entity name, so both fields resolve to ONE type in the schema. A
	// missing id answers null with the canonical not-found in errors[].
	reg.Register(fwgraphql.QueryByID[requests.FindPermissionByIDRequest](
		"permission", "Permission",
		requests.FindPermissionByIDResponse{}.FromResult,
		&handlers.FindByIDQueryHandler[*appqueries.FindPermissionByIDQuery, appqueries.FindPermissionByIDResult]{
			Reader: d.ViewReader, View: view.Name(),
		},
		fwgraphql.RequirePermission("permission:read")))

	reg.Register(fwgraphql.MutationWithBody[requests.InsertPermissionRequest](
		"createPermission", requests.InsertPermissionResponse{}.FromResult,
		&handlers.InsertCommandHandler[*appdomain.Permission, *commands.InsertPermissionCommand, commands.InsertPermissionResult]{
			Repo: repo, Service: svc,
		},
		fwgraphql.RequirePermission("permission:insert")))

	reg.Register(fwgraphql.MutationWithBodyID[requests.PatchPermissionRequest](
		"patchPermission", requests.PatchPermissionResponse{}.FromResult,
		&handlers.PartialUpdateCommandHandler[*appdomain.Permission, *commands.PatchPermissionCommand, commands.PatchPermissionResult]{
			Repo: repo, Service: svc,
		},
		fwgraphql.RequirePermission("permission:update")))

	reg.Register(fwgraphql.MutationByID(
		"archivePermission",
		&handlers.ArchiveCommandHandler[*appdomain.Permission, *commands.ArchivePermissionCommand, fwresults.None]{
			Repo: repo, Service: svc,
		},
		fwgraphql.RequirePermission("permission:archive")))

}
