// Code generated by omnicore-gen. DO NOT EDIT.
//
// The 5 permission endpoints.
//
// entity:     Permission
// spec:       specs/omnicore-gen/permission.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-24
// checksum:   sha256:3f4749cb53238b4e1b22a6f3c569ae4dbd9c5acfacf43ff39f5a6f9ae6f89b12
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package web

import (
	"github.com/ClaudioSchirmer/omnicore/application/handlers"
	"github.com/ClaudioSchirmer/omnicore/application/persistence"
	fwresults "github.com/ClaudioSchirmer/omnicore/application/results"
	"github.com/ClaudioSchirmer/omnicore/bootstrap"
	"github.com/ClaudioSchirmer/omnicore/domain"
	"github.com/ClaudioSchirmer/omnicore/infra/db/query"
	fwweb "github.com/ClaudioSchirmer/omnicore/web"
	fwopenapi "github.com/ClaudioSchirmer/omnicore/web/openapi"
	fwresponses "github.com/ClaudioSchirmer/omnicore/web/responses"

	"github.com/ClaudioSchirmer/authcore/internal/application/commands"
	appqueries "github.com/ClaudioSchirmer/authcore/internal/application/queries"
	appdomain "github.com/ClaudioSchirmer/authcore/internal/domain"
	"github.com/ClaudioSchirmer/authcore/internal/web/requests"
	fwgraphql "github.com/ClaudioSchirmer/omnicore/web/graphql"
	"github.com/gofiber/fiber/v3"
)

// MountPermissions registers every permission endpoint.
//
// The repository arrives as an interface, not as the concrete infra type: the
// web layer must not depend on infra.
func MountPermissions(
	app *fiber.App,
	repo persistence.ScopedRepository[*appdomain.Permission],
	svc domain.Service,
	view *query.RelationalViewDefinition,
	d bootstrap.Deps,
) {
	group := app.Group("/permissions")
	viewName := view.Name()

	insertH, insertSpec := fwweb.CommandWithBodySpec(d.Pipeline,
		requests.InsertPermissionRequest{},
		requests.InsertPermissionResponse{}.FromResult,
		&handlers.InsertCommandHandler[*appdomain.Permission, *commands.InsertPermissionCommand, commands.InsertPermissionResult]{
			Repo: repo, Service: svc,
		}, fiber.StatusCreated)
	fwopenapi.Mount(d.OpenAPIRegistry, group, fiber.MethodPost, "/",
		insertH, insertSpec,
		fwopenapi.Doc{
			Summary:     "Create a permission",
			Description: "Creates a permission and returns it as stored — the response reflects any value the domain normalised or defaulted, not an echo of the request.",
			Tags:        []string{"Permissions"},
		},
		fwopenapi.RequirePermission("permission:insert"))

	patchH, patchSpec := fwweb.CommandWithBodyIDSpec(d.Pipeline,
		requests.PatchPermissionRequest{},
		requests.PatchPermissionResponse{}.FromResult,
		&handlers.PartialUpdateCommandHandler[*appdomain.Permission, *commands.PatchPermissionCommand, commands.PatchPermissionResult]{
			Repo: repo, Service: svc,
		}, fiber.StatusOK)
	fwopenapi.Mount(d.OpenAPIRegistry, group, fiber.MethodPatch, "/:id",
		patchH, patchSpec,
		fwopenapi.Doc{
			Summary:     "Update a permission (partial)",
			Description: "Partial update: only the fields present in the body change. Because an absent field and an explicit null cannot be told apart here, this verb cannot set a value back to null.",
			Tags:        []string{"Permissions"},
		},
		fwopenapi.RequirePermission("permission:update"))

	archiveH, archiveSpec := fwweb.CommandByIDSpec(d.Pipeline,
		fwresponses.NoBody,
		&handlers.ArchiveCommandHandler[*appdomain.Permission, *commands.ArchivePermissionCommand, fwresults.None]{
			Repo: repo, Service: svc,
		}, fiber.StatusNoContent)
	fwopenapi.Mount(d.OpenAPIRegistry, group, fiber.MethodPatch, "/:id/archive",
		archiveH, archiveSpec,
		fwopenapi.Doc{
			Summary:     "Archive a permission",
			Description: "Archives the permission: the row stays but is hidden from reads unless they ask for archived rows. This service mounts no unarchive: the row stays as history and nothing brings it back into the active set.",
			Tags:        []string{"Permissions"},
		},
		fwopenapi.RequirePermission("permission:archive"))

	byParamsH, byParamsSpec := fwweb.QueryWithParamsSpec(d.Pipeline,
		requests.FindPermissionsRequest{},
		requests.FindPermissionsResponse{}.FromResult,
		&handlers.FindByParamsQueryHandler[*appqueries.FindPermissionsByParamsQuery, appqueries.FindPermissionsByParamsResult]{
			Reader: d.ViewReader, View: viewName,
		})
	fwopenapi.Mount(d.OpenAPIRegistry, group, fiber.MethodGet, "/",
		byParamsH, byParamsSpec,
		fwopenapi.Doc{
			Summary:     "List permissions",
			Description: "Paged listing of permissions. Unknown filter keys and operators are rejected with a typed 400 rather than silently ignored.",
			Tags:        []string{"Permissions"},
		},
		fwopenapi.RequirePermission("permission:read"))

	byIdH, byIdSpec := fwweb.QueryByIDSpec(d.Pipeline,
		requests.FindPermissionByIDRequest{},
		requests.FindPermissionByIDResponse{}.FromResult,
		&handlers.FindByIDQueryHandler[*appqueries.FindPermissionByIDQuery, appqueries.FindPermissionByIDResult]{
			Reader: d.ViewReader, View: viewName,
		})
	fwopenapi.Mount(d.OpenAPIRegistry, group, fiber.MethodGet, "/:id",
		byIdH, byIdSpec,
		fwopenapi.Doc{
			Summary:     "Get a permission by id",
			Description: "Reads one permission. Only the controls this endpoint declares are accepted; anything else is rejected with a typed 400.",
			Tags:        []string{"Permissions"},
		},
		fwopenapi.RequirePermission("permission:read"))

}

// MountPermissionsGraphQL exposes permission on the GraphQL surface.
//
// Every field here reuses the handler its REST twin uses, with the same
// permission attached. There is no second implementation to keep in step.
func MountPermissionsGraphQL(
	reg *fwgraphql.Registry,
	repo persistence.ScopedRepository[*appdomain.Permission],
	svc domain.Service,
	view *query.RelationalViewDefinition,
	d bootstrap.Deps,
) {
	// A paged connection over the same view the REST listing reads — same
	// handler, same Response, so the node type and the JSON body cannot drift.
	reg.Register(fwgraphql.QueryWithParams[requests.FindPermissionsRequest](
		"permissions", "Permission",
		requests.FindPermissionsResponse{}.FromResult,
		&handlers.FindByParamsQueryHandler[*appqueries.FindPermissionsByParamsQuery, appqueries.FindPermissionsByParamsResult]{
			Reader: d.ViewReader, View: view.Name(),
		},
		fwgraphql.RequirePermission("permission:read")))

	// The singular twin of the connection: one nullable node, the same
	// entity name, so both fields resolve to ONE type in the schema. A
	// missing id answers null with the canonical not-found in errors[].
	reg.Register(fwgraphql.QueryByID[requests.FindPermissionByIDRequest](
		"permission", "Permission",
		requests.FindPermissionByIDResponse{}.FromResult,
		&handlers.FindByIDQueryHandler[*appqueries.FindPermissionByIDQuery, appqueries.FindPermissionByIDResult]{
			Reader: d.ViewReader, View: view.Name(),
		},
		fwgraphql.RequirePermission("permission:read")))

	reg.Register(fwgraphql.MutationWithBody[requests.InsertPermissionRequest](
		"createPermission", requests.InsertPermissionResponse{}.FromResult,
		&handlers.InsertCommandHandler[*appdomain.Permission, *commands.InsertPermissionCommand, commands.InsertPermissionResult]{
			Repo: repo, Service: svc,
		},
		fwgraphql.RequirePermission("permission:insert")))

	reg.Register(fwgraphql.MutationWithBodyID[requests.PatchPermissionRequest](
		"patchPermission", requests.PatchPermissionResponse{}.FromResult,
		&handlers.PartialUpdateCommandHandler[*appdomain.Permission, *commands.PatchPermissionCommand, commands.PatchPermissionResult]{
			Repo: repo, Service: svc,
		},
		fwgraphql.RequirePermission("permission:update")))

	reg.Register(fwgraphql.MutationByID(
		"archivePermission",
		&handlers.ArchiveCommandHandler[*appdomain.Permission, *commands.ArchivePermissionCommand, fwresults.None]{
			Repo: repo, Service: svc,
		},
		fwgraphql.RequirePermission("permission:archive")))

}
