// Code generated by omnicore-gen. DO NOT EDIT.
//
// The 5 role endpoints.
//
// entity:     Role
// spec:       specs/omnicore-gen/role.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-21
// checksum:   sha256:5952620a42f27586833f325679c4acf157e1a37a994d34d13c72e206399a3fe4
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package web

import (
	"github.com/ClaudioSchirmer/omnicore/application/handlers"
	"github.com/ClaudioSchirmer/omnicore/application/persistence"
	fwresults "github.com/ClaudioSchirmer/omnicore/application/results"
	"github.com/ClaudioSchirmer/omnicore/bootstrap"
	"github.com/ClaudioSchirmer/omnicore/domain"
	"github.com/ClaudioSchirmer/omnicore/infra/db/query"
	fwweb "github.com/ClaudioSchirmer/omnicore/web"
	fwopenapi "github.com/ClaudioSchirmer/omnicore/web/openapi"
	fwresponses "github.com/ClaudioSchirmer/omnicore/web/responses"

	"github.com/ClaudioSchirmer/authcore/internal/application/commands"
	appqueries "github.com/ClaudioSchirmer/authcore/internal/application/queries"
	appdomain "github.com/ClaudioSchirmer/authcore/internal/domain"
	"github.com/ClaudioSchirmer/authcore/internal/web/requests"
	fwgraphql "github.com/ClaudioSchirmer/omnicore/web/graphql"
	"github.com/gofiber/fiber/v3"
)

// MountRoles registers every role endpoint.
//
// The repository arrives as an interface, not as the concrete infra type: the
// web layer must not depend on infra.
func MountRoles(
	app *fiber.App,
	repo persistence.ScopedRepository[*appdomain.Role],
	svc domain.Service,
	view *query.ViewDefinition,
	d bootstrap.Deps,
) {
	group := app.Group("/roles")
	viewName := view.Name()

	insertH, insertSpec := fwweb.CommandWithBodySpec(d.Pipeline,
		requests.InsertRoleRequest{},
		requests.InsertRoleResponse{}.FromResult,
		&handlers.InsertCommandHandler[*appdomain.Role, *commands.InsertRoleCommand, commands.InsertRoleResult]{
			Repo: repo, Service: svc,
		}, fiber.StatusCreated)
	fwopenapi.Mount(d.OpenAPIRegistry, group, fiber.MethodPost, "/",
		insertH, insertSpec,
		fwopenapi.Doc{
			Summary:     "Create a role",
			Description: "Creates a role and returns it as stored — the response reflects any value the domain normalised or defaulted, not an echo of the request.",
			Tags:        []string{"Roles"},
		},
		fwopenapi.RequirePermission("role:insert"))

	patchH, patchSpec := fwweb.CommandWithBodyIDSpec(d.Pipeline,
		requests.PatchRoleRequest{},
		requests.PatchRoleResponse{}.FromResult,
		&handlers.PartialUpdateCommandHandler[*appdomain.Role, *commands.PatchRoleCommand, commands.PatchRoleResult]{
			Repo: repo, Service: svc,
		}, fiber.StatusOK)
	fwopenapi.Mount(d.OpenAPIRegistry, group, fiber.MethodPatch, "/:id",
		patchH, patchSpec,
		fwopenapi.Doc{
			Summary:     "Update a role (partial)",
			Description: "Partial update: only the fields present in the body change. Because an absent field and an explicit null cannot be told apart here, this verb cannot set a value back to null.",
			Tags:        []string{"Roles"},
		},
		fwopenapi.RequirePermission("role:update"))

	archiveH, archiveSpec := fwweb.CommandByIDSpec(d.Pipeline,
		fwresponses.NoBody,
		&handlers.ArchiveCommandHandler[*appdomain.Role, *commands.ArchiveRoleCommand, fwresults.None]{
			Repo: repo, Service: svc,
		}, fiber.StatusNoContent)
	fwopenapi.Mount(d.OpenAPIRegistry, group, fiber.MethodPatch, "/:id/archive",
		archiveH, archiveSpec,
		fwopenapi.Doc{
			Summary:     "Archive a role",
			Description: "Archives the role: the row stays but is hidden from reads unless they ask for archived rows. This service mounts no unarchive: the row stays as history and nothing brings it back into the active set.",
			Tags:        []string{"Roles"},
		},
		fwopenapi.RequirePermission("role:archive"))

	byParamsH, byParamsSpec := fwweb.QueryWithParamsSpec(d.Pipeline,
		requests.FindRolesRequest{},
		requests.FindRolesResponse{}.FromResult,
		&handlers.FindByParamsQueryHandler[*appqueries.FindRolesByParamsQuery, appqueries.FindRolesByParamsResult]{
			Reader: d.ViewReader, View: viewName,
		})
	fwopenapi.Mount(d.OpenAPIRegistry, group, fiber.MethodGet, "/",
		byParamsH, byParamsSpec,
		fwopenapi.Doc{
			Summary:     "List roles",
			Description: "Paged listing of roles. Unknown filter keys and operators are rejected with a typed 400 rather than silently ignored.",
			Tags:        []string{"Roles"},
		},
		fwopenapi.RequirePermission("role:read"))

	byIdH, byIdSpec := fwweb.QueryByIDSpec(d.Pipeline,
		requests.FindRoleByIDRequest{},
		requests.FindRoleByIDResponse{}.FromResult,
		&handlers.FindByIDQueryHandler[*appqueries.FindRoleByIDQuery, appqueries.FindRoleByIDResult]{
			Reader: d.ViewReader, View: viewName,
		})
	fwopenapi.Mount(d.OpenAPIRegistry, group, fiber.MethodGet, "/:id",
		byIdH, byIdSpec,
		fwopenapi.Doc{
			Summary:     "Get a role by id",
			Description: "Reads one role. Only the controls this endpoint declares are accepted; anything else is rejected with a typed 400.",
			Tags:        []string{"Roles"},
		},
		fwopenapi.RequirePermission("role:read"))

	hAddRolePermission, sAddRolePermission := fwweb.CommandWithBodyIDSpec(d.Pipeline,
		requests.AddRolePermissionRequest{},
		requests.AddRolePermissionResponse{}.FromResult,
		&handlers.UpdateCommandHandler[*appdomain.Role, *commands.AddRolePermissionCommand, commands.AddRolePermissionResult]{
			Repo: repo, Service: svc,
		}, fiber.StatusCreated)
	fwopenapi.Mount(d.OpenAPIRegistry, group, fiber.MethodPost, "/:id/permissions",
		hAddRolePermission, sAddRolePermission,
		fwopenapi.Doc{
			Summary:     "Add one RolePermission to a Role",
			Description: "Adds ONE entry to the permissions collection of an existing Role, in the owner's transaction. 404 when the owner is not there. The response carries the entry AS STORED, including the id the server minted for it — that id is how the caller addresses it afterwards.",
			Tags:        []string{"Roles"},
		},
		fwopenapi.RequirePermission("role:update"))

	hRemoveRolePermission, sRemoveRolePermission := fwweb.CommandWithBodyIDSpec(d.Pipeline,
		requests.RemoveRolePermissionRequest{},
		requests.RemoveRolePermissionResponse{}.FromResult,
		&handlers.UpdateCommandHandler[*appdomain.Role, *commands.RemoveRolePermissionCommand, commands.RemoveRolePermissionResult]{
			Repo: repo, Service: svc,
		}, fiber.StatusOK)
	fwopenapi.Mount(d.OpenAPIRegistry, group, fiber.MethodPatch, "/:id/permissions/:rolePermissionId/archive",
		hRemoveRolePermission, sRemoveRolePermission,
		fwopenapi.Doc{
			Summary:     "Archive one RolePermission of a Role",
			Description: "Archives ONE entry: the row stays, stamped, and stops being returned — reversible, which is why this is not a DELETE. 404 when the owner is not there, and 404 when it holds no entry with that id.",
			Tags:        []string{"Roles"},
		},
		fwopenapi.RequirePermission("role:update"))

}

// MountRolesGraphQL exposes role on the GraphQL surface.
//
// Every field here reuses the handler its REST twin uses, with the same
// permission attached. There is no second implementation to keep in step.
func MountRolesGraphQL(
	reg *fwgraphql.Registry,
	repo persistence.ScopedRepository[*appdomain.Role],
	svc domain.Service,
	view *query.ViewDefinition,
	d bootstrap.Deps,
) {
	// A paged connection over the same view the REST listing reads — same
	// handler, same Response, so the node type and the JSON body cannot drift.
	reg.Register(fwgraphql.QueryWithParams[requests.FindRolesRequest](
		"roles", "Role",
		requests.FindRolesResponse{}.FromResult,
		&handlers.FindByParamsQueryHandler[*appqueries.FindRolesByParamsQuery, appqueries.FindRolesByParamsResult]{
			Reader: d.ViewReader, View: view.Name(),
		},
		fwgraphql.RequirePermission("role:read")))

	// The singular twin of the connection: one nullable node, the same
	// entity name, so both fields resolve to ONE type in the schema. A
	// missing id answers null with the canonical not-found in errors[].
	reg.Register(fwgraphql.QueryByID[requests.FindRoleByIDRequest](
		"role", "Role",
		requests.FindRoleByIDResponse{}.FromResult,
		&handlers.FindByIDQueryHandler[*appqueries.FindRoleByIDQuery, appqueries.FindRoleByIDResult]{
			Reader: d.ViewReader, View: view.Name(),
		},
		fwgraphql.RequirePermission("role:read")))

	reg.Register(fwgraphql.MutationWithBody[requests.InsertRoleRequest](
		"createRole", requests.InsertRoleResponse{}.FromResult,
		&handlers.InsertCommandHandler[*appdomain.Role, *commands.InsertRoleCommand, commands.InsertRoleResult]{
			Repo: repo, Service: svc,
		},
		fwgraphql.RequirePermission("role:insert")))

	reg.Register(fwgraphql.MutationWithBodyID[requests.PatchRoleRequest](
		"patchRole", requests.PatchRoleResponse{}.FromResult,
		&handlers.PartialUpdateCommandHandler[*appdomain.Role, *commands.PatchRoleCommand, commands.PatchRoleResult]{
			Repo: repo, Service: svc,
		},
		fwgraphql.RequirePermission("role:update")))

	reg.Register(fwgraphql.MutationByID(
		"archiveRole",
		&handlers.ArchiveCommandHandler[*appdomain.Role, *commands.ArchiveRoleCommand, fwresults.None]{
			Repo: repo, Service: svc,
		},
		fwgraphql.RequirePermission("role:archive")))

}
