// Code generated by omnicore-gen. DO NOT EDIT.
//
// The clients feature (repository + view + mount).
//
// entity:     Client
// spec:       specs/omnicore-gen/client.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-29
// checksum:   sha256:4384b734fca470dfdd58091f59d56e2ab3e7d94459686bbd62519020ebccef36
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package main

import (
	appinfra "github.com/ClaudioSchirmer/authcore/internal/infra"
	appviews "github.com/ClaudioSchirmer/authcore/internal/infra/views"
	appweb "github.com/ClaudioSchirmer/authcore/internal/web"
	"github.com/ClaudioSchirmer/omnicore/bootstrap"
	"github.com/ClaudioSchirmer/omnicore/infra/db/query"
	fwgraphql "github.com/ClaudioSchirmer/omnicore/web/graphql"
	"github.com/gofiber/fiber/v3"
)

// ClientsFeature holds the client repository and view, built once.
type ClientsFeature struct {
	repo *appinfra.ClientRepository
	svc  *appinfra.ClientServiceImpl
	view *query.RelationalViewDefinition
}

func NewClientsFeature(d bootstrap.Deps) *ClientsFeature {
	repo := appinfra.NewClientRepository(d.DB)
	svc := appinfra.NewClientServiceImpl(repo)
	// The view reads through the SAME loader as the repository. Building a
	// second loader for the same aggregate works and is pure waste — and the
	// loader is what carries the schema, so there is no shape to restate.
	return &ClientsFeature{repo: repo, svc: svc, view: appviews.ClientView(repo.Loader)}
}

// RelationalViews contributes this aggregate's read model through
// bootstrap.RelationalReadableFeature — the sibling seam of Views().
//
// It is a different seam because it is a different KIND of read model: nothing
// here is materialised, so the sync engine, the drift detector and the rebuild
// have nothing to receive.
func (f *ClientsFeature) RelationalViews() []*query.RelationalViewDefinition {
	return []*query.RelationalViewDefinition{f.view}
}

// Mount delegates to the web layer. It stays one line by design.
func (f *ClientsFeature) Mount(app *fiber.App, d bootstrap.Deps) {
	appweb.MountClients(app, f.repo, f.svc, f.view, d)
}

// MountGraphQL opts this feature into the GraphQL surface.
//
// The framework discovers the method by type assertion and builds the single
// shared registry itself — nothing about GraphQL is wired in the composition
// root.
func (f *ClientsFeature) MountGraphQL(reg *fwgraphql.Registry, d bootstrap.Deps) {
	appweb.MountClientsGraphQL(reg, f.repo, f.svc, f.view, d)
}
