// Code generated by omnicore-gen. DO NOT EDIT.
//
// The groups feature (repository + view + mount).
//
// entity:     Group
// spec:       specs/omnicore-gen/group.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-01
// checksum:   sha256:31fa0e53ec5348aa8221fd8c8aeb3677548dbda6ad1243766a5912a128c5cd94
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package main

import (
	appinfra "github.com/ClaudioSchirmer/authcore/internal/infra"
	appviews "github.com/ClaudioSchirmer/authcore/internal/infra/views"
	appweb "github.com/ClaudioSchirmer/authcore/internal/web"
	"github.com/ClaudioSchirmer/omnicore/bootstrap"
	"github.com/ClaudioSchirmer/omnicore/infra/db/query"
	fwgraphql "github.com/ClaudioSchirmer/omnicore/web/graphql"
	"github.com/gofiber/fiber/v3"
)

// GroupsFeature holds the group repository and view, built once.
type GroupsFeature struct {
	repo *appinfra.GroupRepository
	svc  *appinfra.GroupServiceImpl
	view *query.RelationalViewDefinition
}

func NewGroupsFeature(d bootstrap.Deps) *GroupsFeature {
	repo := appinfra.NewGroupRepository(d.DB)
	svc := appinfra.NewGroupServiceImpl(repo)
	// The view reads through the SAME loader as the repository. Building a
	// second loader for the same aggregate works and is pure waste — and the
	// loader is what carries the schema, so there is no shape to restate.
	return &GroupsFeature{repo: repo, svc: svc, view: appviews.GroupView(repo.Loader)}
}

// RelationalViews contributes this aggregate's read model through
// bootstrap.RelationalReadableFeature — the sibling seam of Views().
//
// It is a different seam because it is a different KIND of read model: nothing
// here is materialised, so the sync engine, the drift detector and the rebuild
// have nothing to receive.
func (f *GroupsFeature) RelationalViews() []*query.RelationalViewDefinition {
	return []*query.RelationalViewDefinition{f.view}
}

// Mount delegates to the web layer. It stays one line by design.
func (f *GroupsFeature) Mount(app *fiber.App, d bootstrap.Deps) {
	appweb.MountGroups(app, f.repo, f.svc, f.view, d)
}

// MountGraphQL opts this feature into the GraphQL surface.
//
// The framework discovers the method by type assertion and builds the single
// shared registry itself — nothing about GraphQL is wired in the composition
// root.
func (f *GroupsFeature) MountGraphQL(reg *fwgraphql.Registry, d bootstrap.Deps) {
	appweb.MountGroupsGraphQL(reg, f.repo, f.svc, f.view, d)
}
