// Code generated by omnicore-gen. DO NOT EDIT.
//
// The permissions feature (repository + view + mount).
//
// entity:     Permission
// spec:       specs/omnicore-gen/permission.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-20
// checksum:   sha256:35d7ae382b591458f5272f0950f0c7801d6c901f15e1e6c3895b5f8416768dce
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package main

import (
	appinfra "github.com/ClaudioSchirmer/authcore/internal/infra"
	appviews "github.com/ClaudioSchirmer/authcore/internal/infra/views"
	appweb "github.com/ClaudioSchirmer/authcore/internal/web"
	"github.com/ClaudioSchirmer/omnicore/bootstrap"
	"github.com/ClaudioSchirmer/omnicore/infra/db/query"
	fwgraphql "github.com/ClaudioSchirmer/omnicore/web/graphql"
	"github.com/gofiber/fiber/v3"
)

// PermissionsFeature holds the permission repository and view, built once.
type PermissionsFeature struct {
	repo *appinfra.PermissionRepository
	svc  *appinfra.PermissionServiceImpl
	view *query.ViewDefinition
}

func NewPermissionsFeature(d bootstrap.Deps) *PermissionsFeature {
	repo := appinfra.NewPermissionRepository(d.DB)
	svc := appinfra.NewPermissionServiceImpl(repo)
	// The view reads through the SAME loader as the repository. Building a
	// second loader for the same aggregate works and is pure waste.
	return &PermissionsFeature{repo: repo, svc: svc, view: appviews.PermissionView(repo.Loader)}
}

// Views contributes this aggregate's projection to the framework's sync
// engine.
func (f *PermissionsFeature) Views() []*query.ViewDefinition {
	return []*query.ViewDefinition{f.view}
}

// Mount delegates to the web layer. It stays one line by design.
func (f *PermissionsFeature) Mount(app *fiber.App, d bootstrap.Deps) {
	appweb.MountPermissions(app, f.repo, f.svc, f.view, d)
}

// MountGraphQL opts this feature into the GraphQL surface.
//
// The framework discovers the method by type assertion and builds the single
// shared registry itself — nothing about GraphQL is wired in the composition
// root.
func (f *PermissionsFeature) MountGraphQL(reg *fwgraphql.Registry, d bootstrap.Deps) {
	appweb.MountPermissionsGraphQL(reg, f.repo, f.svc, f.view, d)
}
