// Code generated by omnicore-gen. DO NOT EDIT.
//
// The users feature (repository + view + mount).
//
// entity:     User
// spec:       specs/omnicore-gen/user.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-26
// checksum:   sha256:2dd80a97ae37fb2733b51171931bff504c6864f59f0b6720091d674e7f82693d
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package main

import (
	appinfra "github.com/ClaudioSchirmer/authcore/internal/infra"
	appviews "github.com/ClaudioSchirmer/authcore/internal/infra/views"
	appweb "github.com/ClaudioSchirmer/authcore/internal/web"
	"github.com/ClaudioSchirmer/omnicore/bootstrap"
	"github.com/ClaudioSchirmer/omnicore/infra/db/query"
	fwgraphql "github.com/ClaudioSchirmer/omnicore/web/graphql"
	"github.com/gofiber/fiber/v3"
)

// UsersFeature holds the user repository and view, built once.
type UsersFeature struct {
	repo *appinfra.UserRepository
	svc  *appinfra.UserServiceImpl
	view *query.RelationalViewDefinition
}

func NewUsersFeature(d bootstrap.Deps) *UsersFeature {
	repo := appinfra.NewUserRepository(d.DB)
	svc := appinfra.NewUserServiceImpl(repo)
	// The view reads through the SAME loader as the repository. Building a
	// second loader for the same aggregate works and is pure waste — and the
	// loader is what carries the schema, so there is no shape to restate.
	return &UsersFeature{repo: repo, svc: svc, view: appviews.UserView(repo.Loader)}
}

// RelationalViews contributes this aggregate's read model through
// bootstrap.RelationalReadableFeature — the sibling seam of Views().
//
// It is a different seam because it is a different KIND of read model: nothing
// here is materialised, so the sync engine, the drift detector and the rebuild
// have nothing to receive.
func (f *UsersFeature) RelationalViews() []*query.RelationalViewDefinition {
	return []*query.RelationalViewDefinition{f.view}
}

// Mount delegates to the web layer. It stays one line by design.
func (f *UsersFeature) Mount(app *fiber.App, d bootstrap.Deps) {
	appweb.MountUsers(app, f.repo, f.svc, f.view, d)
}

// MountGraphQL opts this feature into the GraphQL surface.
//
// The framework discovers the method by type assertion and builds the single
// shared registry itself — nothing about GraphQL is wired in the composition
// root.
func (f *UsersFeature) MountGraphQL(reg *fwgraphql.Registry, d bootstrap.Deps) {
	appweb.MountUsersGraphQL(reg, f.repo, f.svc, f.view, d)
}
