// Code generated by omnicore-gen. DO NOT EDIT.
//
// The listing query and its result.
//
// entity:     Client
// spec:       specs/omnicore-gen/client.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-29
// checksum:   sha256:c4302cfab2a7a0587b4cededb8ce66cfac3e40ac47366e5d1ce8964488c99f12
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package queries

import (
	"time"

	"github.com/ClaudioSchirmer/omnicore/application/configuration"
	fwqueries "github.com/ClaudioSchirmer/omnicore/application/queries"
	"github.com/ClaudioSchirmer/omnicore/domain"
)

// FindClientsByParamsQuery is the application-side transport for the paged
// read.
//
// The criteria arrive already parsed from the query string by the framework;
// this type exists so identity-derived restrictions have somewhere to be
// added.
type FindClientsByParamsQuery struct {
	fwqueries.QueryWithParamsBase
	Criteria fwqueries.ReadCriteria
}

func (q FindClientsByParamsQuery) ToCriteria(ctx *configuration.AppContext) (fwqueries.ReadCriteria, error) {
	// Callers see only their tenant's rows. Filter is a map keyed by the Go field
	// path, and the scope is FORCED: a value the caller sent for this field is
	// overwritten, never merged.
	if q.Criteria.Filter == nil {
		q.Criteria.Filter = map[string]any{}
	}
	if id := ctx.Identity(); id != nil {
		// A super-admin crosses the scope: the operator supporting a customer
		// reads across tenants. Not asked through HasPermission — the framework
		// panics when a wildcard is the QUESTION, so the *:* a super-admin
		// carries has a question of its own, and this is it.
		if !id.IsSuperAdmin() {
			q.Criteria.Filter["TenantID"] = id.TenantID()
		}
	} else {
		// No identity at all: the scope stands down, as authz.noIdentity says.
		// Reachable only on a dev bench — auth.mode disabled is refused outside
		// APP_PROFILE=dev — and it serves EVERY row, which is the point: a
		// tenant-scoped entity is otherwise unusable on the machine it is
		// first tried on, answering every listing empty.
	}
	return q.Criteria, nil
}

// FromQueryResult is the read-side twin of a command's FromEntity: the
// framework hands it the Result already filled from the stored document,
// BEFORE any transport sees it.
//
// Nothing is derived on this read, so the filled Result is returned unchanged.
// Declare read.computed in the spec to get a derivation seat.
func (q FindClientsByParamsQuery) FromQueryResult(_ *configuration.AppContext, r FindClientsByParamsResult) (FindClientsByParamsResult, error) {
	return r, nil
}

func (q FindClientsByParamsQuery) ContextName() string { return "Client" }

// FindClientsByParamsResult is one row of the listing, as the application sees
// it.
//
// No wire tags: naming the wire is the Response's job, and a tagged Result is
// refused at boot.
//
// Every field is a pointer because the endpoint serves ?fields=: a column the
// caller did not ask for must fill as ABSENT, not as a zero value, and the
// framework boot-guards that contract on the Result as well as on the
// Response.
type FindClientsByParamsResult struct {
	ID                      *string
	TenantID                *domain.ID
	Name                    *string
	Description             *string
	SecretHash              *string
	SecretChangedAt         *time.Time
	PreviousSecretHash      *string
	PreviousSecretExpiresAt *time.Time
	Status                  *string
	CreatedAt               *time.Time
	UpdatedAt               *time.Time
	TenantWorkspace         *string
	TenantStatus            *string
	Roles                   []ClientRoleRowResult
	AllowedCIDRs            []ClientAllowedCIDRRowResult
	Claims                  []ClientClaimRowResult
}
