// Code generated by omnicore-gen. DO NOT EDIT.
//
// The read tests for find_tenant_by_id_query.go.
//
// entity:     Tenant
// spec:       specs/omnicore-gen/tenant.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-01
// checksum:   sha256:4cdb1d7066c9405d1e929852c80daf2fd8917da92547ba1897d390111a520975
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package queries

import (
	"testing"

	"github.com/ClaudioSchirmer/omnicore/application/configuration"
)

// FindTenantByIDQuery's criteria mapper must not fail on a well-formed query.
//
// A mapper that errors here turns a legitimate read into a 400, and a mapper
// that silently drops a restriction turns it into someone else's rows — so
// the mapping is exercised rather than assumed.
func TestFindTenantByIDQueryCriteriaBuilds(t *testing.T) {
	// No identity attached: the anonymous path, which is the one that
	// applies every restriction rather than skipping them.
	ctx := &configuration.AppContext{}
	if _, err := (FindTenantByIDQuery{}).ToCriteria(ctx); err != nil {
		t.Errorf("the by-id criteria failed: %v", err)
	}
}

// FindTenantByIDQuery's derivation seat must survive a Result with nothing in
// it.
//
// FromQueryResult runs once per document on every read, so an error out of it
// is not a missing field — it is the endpoint answering 500. An empty Result
// is the real case, not a contrived one: a ?fields= selection that named none
// of a computed field's sources produces exactly this.
func TestFindTenantByIDQuerySurvivesAnEmptyResult(t *testing.T) {
	ctx := &configuration.AppContext{}
	if _, err := (FindTenantByIDQuery{}).FromQueryResult(ctx, FindTenantByIDResult{}); err != nil {
		t.Errorf("the by-id derivation failed: %v", err)
	}
}
