// Code generated by omnicore-gen. DO NOT EDIT.
//
// The by-id query and its result.
//
// entity:     Group
// spec:       specs/omnicore-gen/group.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-24
// checksum:   sha256:c0a0259a46b66db91f5cfb1081a3ebaf89583aba50bbd991d5c717a33621486b
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package queries

import (
	"time"

	"github.com/ClaudioSchirmer/omnicore/application/configuration"
	fwqueries "github.com/ClaudioSchirmer/omnicore/application/queries"
	"github.com/ClaudioSchirmer/omnicore/domain"
)

// FindGroupByIDQuery is the application-side transport for the by-id read.
//
// QueryByIDBase supplies SetPathID, which the wrapper calls with the route's
// own :id segment. Criteria arrives whole from the wrapper — the by-id read
// takes its wire criteria the same way the paged one does, so the single
// control this endpoint speaks (?includeArchived) needs no unwrapping by hand.
type FindGroupByIDQuery struct {
	fwqueries.QueryByIDBase
	Criteria fwqueries.ReadCriteria
}

// ToCriteria is where identity-derived read restrictions are injected.
// ReadByID merges Filter into the {id} + archived gate; the paging knobs on
// the same criteria are ignored there by design.
func (q FindGroupByIDQuery) ToCriteria(ctx *configuration.AppContext) (fwqueries.ReadCriteria, error) {
	crit := q.Criteria
	// Callers see only their tenant's rows. Filter is a map keyed by the Go field
	// path, and the scope is FORCED: a value the caller sent for this field is
	// overwritten, never merged.
	if crit.Filter == nil {
		crit.Filter = map[string]any{}
	}
	if id := ctx.Identity(); id != nil {
		// A super-admin crosses the scope: the operator supporting a customer
		// reads across tenants. Not asked through HasPermission — the framework
		// panics when a wildcard is the QUESTION, so the *:* a super-admin
		// carries has a question of its own, and this is it.
		if !id.IsSuperAdmin() {
			crit.Filter["TenantID"] = id.TenantID()
		}
	} else {
		// No identity at all: the scope stands down, as authz.noIdentity says.
		// Reachable only on a dev bench — auth.mode disabled is refused outside
		// APP_PROFILE=dev — and it serves EVERY row, which is the point: a
		// tenant-scoped entity is otherwise unusable on the machine it is
		// first tried on, answering every listing empty.
	}
	return crit, nil
}

// FromQueryResult is the read-side twin of a command's FromEntity: the
// framework hands it the Result already filled from the stored document,
// BEFORE any transport sees it.
//
// Nothing is derived on this read, so the filled Result is returned unchanged.
// Declare read.computed in the spec to get a derivation seat.
func (q FindGroupByIDQuery) FromQueryResult(_ *configuration.AppContext, r FindGroupByIDResult) (FindGroupByIDResult, error) {
	return r, nil
}

// ContextName labels this aggregate in the error envelope.
func (q FindGroupByIDQuery) ContextName() string { return "Group" }

// FindGroupByIDResult is what the by-id read returns.
//
// It carries the WHOLE aggregate — the root's fields, the facets' fields and
// the collections. Reading one record and getting less of it than the listing
// gives for the same record is the shape nobody expects, and there is no
// second request that would fill the gap: the document was already fetched.
//
// No wire tags: naming the wire is the Response's job, and a tagged Result is
// refused at boot. This read declares no ?fields=, so plain values are right
// — an absent key fills as the zero value.
type FindGroupByIDResult struct {
	ID              string
	TenantID        domain.ID
	Key             string
	Name            string
	Description     string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	TenantWorkspace string
	TenantStatus    string
	Roles           []GroupRoleRowResult
}
