// Code generated by omnicore-gen. DO NOT EDIT.
//
// The listing query and its result.
//
// entity:     User
// spec:       specs/omnicore-gen/user.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-01
// checksum:   sha256:d06b5e35aef910bdb41e057c0020bbf2de5cfc4d085c65f81e6e53a425caf8bf
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package queries

import (
	"time"

	"github.com/ClaudioSchirmer/omnicore/application/configuration"
	fwqueries "github.com/ClaudioSchirmer/omnicore/application/queries"
	"github.com/ClaudioSchirmer/omnicore/domain"

	qrydtos "github.com/ClaudioSchirmer/authcore/internal/application/queries/dtos"
)

// FindUsersByParamsQuery is the application-side transport for the paged read.
//
// The criteria arrive already parsed from the query string by the framework;
// this type exists so identity-derived restrictions have somewhere to be
// added.
type FindUsersByParamsQuery struct {
	fwqueries.QueryWithParamsBase
	Criteria fwqueries.ReadCriteria
}

func (q FindUsersByParamsQuery) ToCriteria(ctx *configuration.AppContext) (fwqueries.ReadCriteria, error) {
	// Callers see only their tenant's rows. Filter is a map keyed by the Go field
	// path, and the scope is FORCED: a value the caller sent for this field is
	// overwritten, never merged.
	if q.Criteria.Filter == nil {
		q.Criteria.Filter = map[string]any{}
	}
	if id := ctx.Identity(); id != nil {
		// A super-admin crosses the scope: the operator supporting a customer
		// reads across tenants. Not asked through HasPermission — the framework
		// panics when a wildcard is the QUESTION, so the *:* a super-admin
		// carries has a question of its own, and this is it.
		if !id.IsSuperAdmin() {
			q.Criteria.Filter["TenantID"] = id.TenantID()
		}
	} else {
		// No identity at all: the scope stands down, as authz.noIdentity says.
		// Reachable only on a dev bench — auth.mode disabled is refused outside
		// APP_PROFILE=dev — and it serves EVERY row, which is the point: a
		// tenant-scoped entity is otherwise unusable on the machine it is
		// first tried on, answering every listing empty.
	}
	return q.Criteria, nil
}

// FromQueryResult is the read-side twin of a command's FromEntity: the
// framework hands it the Result already filled from the stored document,
// BEFORE any transport sees it.
//
// This read carries computed fields, so the derivation runs here — in
// internal/application/queries/user_computed_manual.go, which the generator
// wrote once and never touches again.
func (q FindUsersByParamsQuery) FromQueryResult(ctx *configuration.AppContext, r FindUsersByParamsResult) (FindUsersByParamsResult, error) {
	if r.GivenName != nil && r.FamilyName != nil {
		v, err := ComputeUserFullName(ctx, *r.GivenName, *r.FamilyName)
		if err != nil {
			return r, err
		}
		r.FullName = &v
	}
	return r, nil
}

func (q FindUsersByParamsQuery) ContextName() string { return "User" }

// FindUsersByParamsResult is one row of the listing, as the application sees
// it.
//
// No wire tags: naming the wire is the Response's job, and a tagged Result is
// refused at boot.
//
// Every field is a pointer because the endpoint serves ?fields=: a column the
// caller did not ask for must fill as ABSENT, not as a zero value, and the
// framework boot-guards that contract on the Result as well as on the
// Response.
type FindUsersByParamsResult struct {
	ID                 *string
	TenantID           *domain.ID
	GivenName          *string
	FamilyName         *string
	Email              *string
	EmailVerifiedAt    *time.Time
	PasswordHash       *string
	PasswordChangedAt  *time.Time
	MustChangePassword *bool
	Status             *string
	CreatedAt          *time.Time
	UpdatedAt          *time.Time
	TenantWorkspace    *string
	TenantStatus       *string
	// FullName is COMPUTED: no column backs it, and FromQueryResult fills it
	// from GivenName+FamilyName.
	FullName *string
	Groups   []qrydtos.UserGroupRowResult
	Roles    []qrydtos.UserRoleRowResult
	Claims   []qrydtos.UserClaimRowResult
}
