// Code generated by omnicore-gen. DO NOT EDIT.
//
// The listing query and its result.
//
// entity:     Permission
// spec:       specs/omnicore-gen/permission.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-20
// checksum:   sha256:0221f645e18116fedb9b178e63aa6718bb04aabfb994255a21f854875e83d620
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package queries

import (
	"github.com/ClaudioSchirmer/omnicore/application/configuration"
	fwqueries "github.com/ClaudioSchirmer/omnicore/application/queries"
)

// FindPermissionsByParamsQuery is the application-side transport for the paged
// read.
//
// The criteria arrive already parsed from the query string by the framework;
// this type exists so identity-derived restrictions have somewhere to be
// added.
type FindPermissionsByParamsQuery struct {
	fwqueries.QueryWithParamsBase
	Criteria fwqueries.ReadCriteria
}

func (q FindPermissionsByParamsQuery) ToCriteria(ctx *configuration.AppContext) (fwqueries.ReadCriteria, error) {
	return q.Criteria, nil
}

// FromQueryResult is the read-side twin of a command's FromEntity: the
// framework hands it the Result already filled from the stored document,
// BEFORE any transport sees it.
//
// This read carries computed fields, so the derivation runs here — in
// internal/application/queries/permission_computed_manual.go, which the
// generator wrote once and never touches again.
func (q FindPermissionsByParamsQuery) FromQueryResult(ctx *configuration.AppContext, r FindPermissionsByParamsResult) (FindPermissionsByParamsResult, error) {
	if r.Resource != nil && r.Action != nil {
		v, err := ComputePermission(ctx, *r.Resource, *r.Action)
		if err != nil {
			return r, err
		}
		r.Permission = &v
	}
	return r, nil
}

func (q FindPermissionsByParamsQuery) ContextName() string { return "Permission" }

// FindPermissionsByParamsResult is one row of the listing, as the application
// sees it.
//
// No wire tags: naming the wire is the Response's job, and a tagged Result is
// refused at boot.
//
// Every field is a pointer because the endpoint serves ?fields=: a column the
// caller did not ask for must fill as ABSENT, not as a zero value, and the
// framework boot-guards that contract on the Result as well as on the
// Response.
type FindPermissionsByParamsResult struct {
	ID          *string
	Resource    *string
	Action      *string
	Description *string
	// Permission is COMPUTED: no column backs it, and FromQueryResult fills it
	// from Resource+Action.
	Permission *string
}
