// Code generated by omnicore-gen. DO NOT EDIT.
//
// The read tests for find_group_by_id_query.go.
//
// entity:     Group
// spec:       specs/omnicore-gen/group.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-01
// checksum:   sha256:2d791f8e9695e33a2921f202a50fcf40315cdd43d16fe1de3ebe2c7825e79525
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package queries

import (
	"testing"

	"github.com/ClaudioSchirmer/omnicore/application/configuration"
)

// FindGroupByIDQuery's criteria mapper must not fail on a well-formed query.
//
// A mapper that errors here turns a legitimate read into a 400, and a mapper
// that silently drops a restriction turns it into someone else's rows — so
// the mapping is exercised rather than assumed.
func TestFindGroupByIDQueryCriteriaBuilds(t *testing.T) {
	// No identity attached: the anonymous path, which is the one that
	// applies every restriction rather than skipping them.
	ctx := &configuration.AppContext{}
	if _, err := (FindGroupByIDQuery{}).ToCriteria(ctx); err != nil {
		t.Errorf("the by-id criteria failed: %v", err)
	}
}

// FindGroupByIDQuery's derivation seat must survive a Result with nothing in
// it.
//
// FromQueryResult runs once per document on every read, so an error out of it
// is not a missing field — it is the endpoint answering 500. An empty Result
// is the real case, not a contrived one: a ?fields= selection that named none
// of a computed field's sources produces exactly this.
func TestFindGroupByIDQuerySurvivesAnEmptyResult(t *testing.T) {
	ctx := &configuration.AppContext{}
	if _, err := (FindGroupByIDQuery{}).FromQueryResult(ctx, FindGroupByIDResult{}); err != nil {
		t.Errorf("the by-id derivation failed: %v", err)
	}
}
