// Code generated by omnicore-gen. DO NOT EDIT.
//
// The read criteria tests.
//
// entity:     Permission
// spec:       specs/omnicore-gen/permission.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-29
// checksum:   sha256:f4aad98b836b8378f7d4a31c774bb78c1f4b3a04d3951c397903b9aa8a29309e
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package queries

import (
	"testing"

	"github.com/ClaudioSchirmer/omnicore/application/configuration"
)

// The criteria mappers must not fail on a well-formed query.
//
// A mapper that errors here turns a legitimate read into a 400, and a mapper
// that silently drops a restriction turns it into someone else's rows — so
// the mapping is exercised rather than assumed.
func TestPermissionCriteriaBuild(t *testing.T) {
	// No identity attached: the anonymous path, which is the one that
	// applies every restriction rather than skipping them.
	ctx := &configuration.AppContext{}
	if _, err := (FindPermissionByIDQuery{}).ToCriteria(ctx); err != nil {
		t.Errorf("the by-id criteria failed: %v", err)
	}
	if _, err := (FindPermissionsByParamsQuery{}).ToCriteria(ctx); err != nil {
		t.Errorf("the listing criteria failed: %v", err)
	}
}

// The derivation seat must survive a Result with nothing in it.
//
// FromQueryResult runs once per document on every read, so an error out of it
// is not a missing field — it is the endpoint answering 500. An empty Result
// is the real case, not a contrived one: a ?fields= selection that named none
// of a computed field's sources produces exactly this.
func TestPermissionReadsSurviveAnEmptyResult(t *testing.T) {
	ctx := &configuration.AppContext{}
	if _, err := (FindPermissionByIDQuery{}).FromQueryResult(ctx, FindPermissionByIDResult{}); err != nil {
		t.Errorf("the by-id derivation failed: %v", err)
	}
	if _, err := (FindPermissionsByParamsQuery{}).FromQueryResult(ctx, FindPermissionsByParamsResult{}); err != nil {
		t.Errorf("the listing derivation failed: %v", err)
	}
}

// The derivations RUN when the sources they declared are there.
//
// The bodies are hand-written and may legitimately return nothing yet; what is
// under test is the seat around them — that the generated unwrapping, the
// call and the assignment hold together for a Result that carries every
// source.
func TestPermissionDerivationsRun(t *testing.T) {
	ctx := &configuration.AppContext{}
	{
		r := FindPermissionByIDResult{Resource: "tenant", Action: "read"}
		if _, err := (FindPermissionByIDQuery{}).FromQueryResult(ctx, r); err != nil {
			t.Errorf("the by-id derivation failed on a filled result: %v", err)
		}
	}
	{
		resource := string("tenant")
		action := string("read")
		r := FindPermissionsByParamsResult{Resource: &resource, Action: &action}
		if _, err := (FindPermissionsByParamsQuery{}).FromQueryResult(ctx, r); err != nil {
			t.Errorf("the listing derivation failed on a filled result: %v", err)
		}
	}
}

// Both queries report the same context name.
//
// It is the name every notification of this read is grouped under, so two
// spellings split one entity's errors into two piles for whoever reads them.
func TestPermissionQueriesShareAContext(t *testing.T) {
	for _, got := range []string{
		FindPermissionByIDQuery{}.ContextName(),
		FindPermissionsByParamsQuery{}.ContextName(),
	} {
		if got != "Permission" {
			t.Errorf("a query reports the context %q, the entity is %q", got, "Permission")
		}
	}
}
