// Code generated by omnicore-gen. DO NOT EDIT.
//
// The client_claims child schema.
//
// entity:     Client
// spec:       specs/omnicore-gen/client.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-06
// checksum:   sha256:595b7ce27dc8ba2f0c95b57fdee9e97aa0d417e97dfea84165cf32d39e6739d0
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package schemas

import (
	"github.com/ClaudioSchirmer/authcore/internal/domain/aggregatevos"
	"github.com/ClaudioSchirmer/omnicore/infra/db/core"
)

// ClientClaimSchema maps the ClientClaim child to client_claims.
//
// ParentID declares the link back to the owner. It is projected automatically
// as the read-only twin of the id, so the column is never mapped as an
// ordinary field — doing that would have the framework overwrite its own
// value.
//
// There is no revision column here: the framework forbids one on a child,
// because the aggregate's version belongs to the root.
func ClientClaimSchema() *core.TableSchema {
	return core.NewTableSchema[aggregatevos.ClientClaim]("client_claims").
		ID("id").
		ParentID("client_id").
		Field("ClaimID", "claim_id").
		Field("Value", "value").
		ArchivedAt("archived_at").
		CreatedAt("created_at").
		UpdatedAt("updated_at")
}
