// Code generated by omnicore-gen. DO NOT EDIT.
//
// The clients schema (8 columns).
//
// entity:     Client
// spec:       specs/omnicore-gen/client.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-26
// checksum:   sha256:b0dd9e043ae1b6ceb4f019feeb02a213b55f88d013cdf728b71a27a263fca644
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package schemas

import (
	appdomain "github.com/ClaudioSchirmer/authcore/internal/domain"
	"github.com/ClaudioSchirmer/omnicore/infra/db/core"
)

// ClientSchema maps the aggregate's Go fields to columns of clients.
//
// In every Field pair the LEFT side is the Go field and the RIGHT side is the
// column. Swapping them still compiles and is silently wrong, so the order is
// never improvised.
//
// The managed columns are declared by presence: a column that is not named
// here is never mentioned in any SQL the framework writes.
func ClientSchema() *core.TableSchema {
	return core.NewTableSchema[*appdomain.Client]("clients").
		ID("id").
		Revision("revision").
		Child(ClientRoleSchema()).
		Child(ClientAllowedCIDRSchema()).
		Field("TenantID", "tenant_id").
		Field("Name", "name").
		Field("Description", "description").
		RedactedField("SecretHash", "secret_hash",
			core.InSync(core.RedactWith("***")),
			core.InAudit(core.RedactWith("***"))).
		Field("SecretChangedAt", "secret_changed_at").
		RedactedField("PreviousSecretHash", "previous_secret_hash",
			core.InSync(core.RedactWith("***")),
			core.InAudit(core.RedactWith("***"))).
		Field("PreviousSecretExpiresAt", "previous_secret_expires_at").
		Field("Status", "status").
		DeletedAt("deleted_at").
		CreatedAt("created_at").
		UpdatedAt("updated_at")
}
