// Code generated by omnicore-gen. DO NOT EDIT.
//
// The builder tests for client_claim_schema.go — they RUN the builder, so
// a boot panic is a test failure.
//
// entity:     Client
// spec:       specs/omnicore-gen/client.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-01
// checksum:   sha256:b8bc58b42700f117ec0939d56c762da13c53c892716255c703fcad6a146f1e44
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package schemas

import (
	"testing"

	"github.com/ClaudioSchirmer/authcore/internal/domain/aggregatevos"
)

// ClientClaimSchema must build without panicking, and must map a table.
//
// The framework validates a schema as it is declared, by panicking, and that
// panic aborts the boot. Calling the builder here turns a failed start into a
// failed test.
func TestClientClaimBuilds(t *testing.T) {
	schema := ClientClaimSchema()
	if schema == nil {
		t.Fatal("ClientClaimSchema built a nil schema")
	}
	if schema.Table() == "" {
		t.Error("ClientClaimSchema built a schema with no table")
	}
}

// ClientClaim answers the collection name the spec declared.
//
// That name is a PERSISTED key — the segment the projection nests the
// collection under and the field a read DTO must carry — so a change here
// changes the document shape rather than a label.
func TestClientClaimKeepsItsCollectionName(t *testing.T) {
	if got := (aggregatevos.ClientClaim{}).CollectionName(); got != "Claims" {
		t.Errorf("the collection answers %q, the spec says %q", got, "Claims")
	}
}
