// Code generated by omnicore-gen. DO NOT EDIT.
//
// The groups schema (4 columns).
//
// entity:     Group
// spec:       specs/omnicore-gen/group.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-24
// checksum:   sha256:560537622463b2f0477bf8e5531fa0eaf079a2ca20568f5782db6a1ff6a45222
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package schemas

import (
	appdomain "github.com/ClaudioSchirmer/authcore/internal/domain"
	"github.com/ClaudioSchirmer/omnicore/infra/db/core"
)

// GroupSchema maps the aggregate's Go fields to columns of groups.
//
// In every Field pair the LEFT side is the Go field and the RIGHT side is the
// column. Swapping them still compiles and is silently wrong, so the order is
// never improvised.
//
// The managed columns are declared by presence: a column that is not named
// here is never mentioned in any SQL the framework writes.
func GroupSchema() *core.TableSchema {
	return core.NewTableSchema[*appdomain.Group]("groups").
		ID("id").
		Revision("revision").
		Child(GroupRoleSchema()).
		Field("TenantID", "tenant_id").
		Field("Key", "group_key").
		Field("Name", "name").
		Field("Description", "description").
		DeletedAt("deleted_at").
		CreatedAt("created_at").
		UpdatedAt("updated_at")
}
