// Code generated by omnicore-gen. DO NOT EDIT.
//
// The schema builder tests — they run the builders, so a boot panic is a
// test failure.
//
// entity:     Tenant
// spec:       omnicore-gen/tenant.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-19
// checksum:   sha256:39184a353db4e8cc411a1588e0c076bc2e2d9badabe8e450de6e6f7dddb5f574
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package schemas

import (
	"testing"

	"github.com/ClaudioSchirmer/omnicore/infra/db/core"
)

// The builders must not panic, and must map a table.
//
// The framework validates a schema AS IT IS DECLARED, by panicking: a child
// carrying a revision, a facet carrying a lifecycle, a collection whose name
// is not spellable as a Go field. Every one of those aborts the boot. Calling
// the builders here turns a failed start into a failed test.
func TestTenantSchemasBuild(t *testing.T) {
	for name, build := range map[string]func() *core.TableSchema{
		"Tenant": TenantSchema,
	} {
		schema := build()
		if schema == nil {
			t.Fatalf("%s built a nil schema", name)
		}
		if schema.Table() == "" {
			t.Errorf("%s built a schema with no table", name)
		}
	}
}

// Tenant must map the table the spec names.
//
// The table is the one thing a schema cannot get wrong quietly: pointed at
// another table it still compiles, still boots, and reads someone else's rows.
func TestTenantSchemaMapsTheDeclaredTable(t *testing.T) {
	if got := TenantSchema().Table(); got != "tenants" {
		t.Errorf("the schema maps %q, the spec says %q", got, "tenants")
	}
}
