// Code generated by omnicore-gen. DO NOT EDIT.
//
// The schema builder tests — they run the builders, so a boot panic is a
// test failure.
//
// entity:     User
// spec:       specs/omnicore-gen/user.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-29
// checksum:   sha256:707a6b168f584b736630ced5ee6337c7c62a029973d5db5b45313da845e9db11
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package schemas

import (
	"testing"

	"github.com/ClaudioSchirmer/authcore/internal/domain/aggregatevos"
	"github.com/ClaudioSchirmer/omnicore/infra/db/core"
)

// The builders must not panic, and must map a table.
//
// The framework validates a schema AS IT IS DECLARED, by panicking: a child
// carrying a revision, a facet carrying a lifecycle, a collection whose name
// is not spellable as a Go field. Every one of those aborts the boot. Calling
// the builders here turns a failed start into a failed test.
func TestUserSchemasBuild(t *testing.T) {
	for name, build := range map[string]func() *core.TableSchema{
		"User":      UserSchema,
		"UserGroup": UserGroupSchema,
		"UserRole":  UserRoleSchema,
		"UserClaim": UserClaimSchema,
	} {
		schema := build()
		if schema == nil {
			t.Fatalf("%s built a nil schema", name)
		}
		if schema.Table() == "" {
			t.Errorf("%s built a schema with no table", name)
		}
	}
}

// User must map the table the spec names.
//
// The table is the one thing a schema cannot get wrong quietly: pointed at
// another table it still compiles, still boots, and reads someone else's rows.
func TestUserSchemaMapsTheDeclaredTable(t *testing.T) {
	if got := UserSchema().Table(); got != "users" {
		t.Errorf("the schema maps %q, the spec says %q", got, "users")
	}
}

// Each collection answers the name the spec declared.
//
// That name is a PERSISTED key — the segment the projection nests the
// collection under and the field a read DTO must carry — so a change here
// changes the document shape rather than a label.
func TestUserCollectionsKeepTheirNames(t *testing.T) {
	for _, tc := range []struct{ got, want string }{
		{aggregatevos.UserGroup{}.CollectionName(), "Groups"},
		{aggregatevos.UserRole{}.CollectionName(), "Roles"},
		{aggregatevos.UserClaim{}.CollectionName(), "Claims"},
	} {
		if tc.got != tc.want {
			t.Errorf("a collection answers %q, the spec says %q", tc.got, tc.want)
		}
	}
}
