// Code generated by omnicore-gen. DO NOT EDIT.
//
// The builder tests for user_group_schema.go — they RUN the builder, so a
// boot panic is a test failure.
//
// entity:     User
// spec:       specs/omnicore-gen/user.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-01
// checksum:   sha256:0b8cf155a774c3a54c2fb984e87b5d4792dc4e18c9676fd840daca1643e197fb
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package schemas

import (
	"testing"

	"github.com/ClaudioSchirmer/authcore/internal/domain/aggregatevos"
)

// UserGroupSchema must build without panicking, and must map a table.
//
// The framework validates a schema as it is declared, by panicking, and that
// panic aborts the boot. Calling the builder here turns a failed start into a
// failed test.
func TestUserGroupBuilds(t *testing.T) {
	schema := UserGroupSchema()
	if schema == nil {
		t.Fatal("UserGroupSchema built a nil schema")
	}
	if schema.Table() == "" {
		t.Error("UserGroupSchema built a schema with no table")
	}
}

// UserGroup answers the collection name the spec declared.
//
// That name is a PERSISTED key — the segment the projection nests the
// collection under and the field a read DTO must carry — so a change here
// changes the document shape rather than a label.
func TestUserGroupKeepsItsCollectionName(t *testing.T) {
	if got := (aggregatevos.UserGroup{}).CollectionName(); got != "Groups" {
		t.Errorf("the collection answers %q, the spec says %q", got, "Groups")
	}
}
