-- THIS FILE IS YOURS. Written once by omnicore-gen, never again.
--
-- The roles table on postgres.
--
-- entity:     Role
-- spec:       specs/omnicore-gen/role.omnicore.yaml
-- generator:  omnicore-gen (created this file, does not maintain it)
-- created:    2026-08-21
--
-- This pair was created once and is now yours. The generator will not
-- rewrite it, and you should not either once it has run anywhere: the
-- framework records an applied migration in its tracking table, so editing
-- the file changes the file and not the database. To change the shape, add a
-- NEW numbered pair in this folder — and remember that adding a NOT NULL
-- column to a table that already has rows needs a default, and that a rename
-- done as drop-then-add takes the data with it.
--
-- There is no checksum here on purpose: this file exists to be edited, so
-- hashing it would report drift every time you did the thing it is for.

-- roles
-- Generated by omnicore-gen from the Role spec.

CREATE TABLE "roles" (
  "id" UUID NOT NULL,
  "tenant_id" UUID NOT NULL,
  "role_key" VARCHAR(64) NOT NULL,
  "name" VARCHAR(120) NOT NULL,
  "description" VARCHAR(500) NOT NULL,
  "revision" BIGINT NOT NULL DEFAULT 0,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "deleted_at" TIMESTAMPTZ NULL,
  CONSTRAINT "roles_pkey" PRIMARY KEY ("id")
);
COMMENT ON TABLE "roles" IS 'A tenant''s own bundle of catalog permissions — the unit a user or a group is granted. Owned by exactly one tenant; the platform''s own roles live in the reserved platform tenant rather than in a null scope.';
COMMENT ON COLUMN "roles"."id" IS 'Row id — a UUID v7 minted by the framework, not a sequence.';
COMMENT ON COLUMN "roles"."tenant_id" IS 'The tenant that owns this role. Immutable after creation — a role never moves between tenants.';
COMMENT ON COLUMN "roles"."role_key" IS 'Stable machine handle of the role, unique within its tenant and immutable. What an API caller and an audit line reference; never the display name.';
COMMENT ON COLUMN "roles"."name" IS 'Human-readable name of the role as operators and end users see it. Not unique — two tenants, or two roles, may share a label.';
COMMENT ON COLUMN "roles"."description" IS 'What holding this role actually lets a user do, in the tenant''s own words.';
COMMENT ON COLUMN "roles"."revision" IS 'Optimistic-concurrency stamp: bumped on every write, and the value each update is guarded on. Maintained by the framework.';
COMMENT ON COLUMN "roles"."created_at" IS 'When the row was created; written by the database default.';
COMMENT ON COLUMN "roles"."updated_at" IS 'When the row was last written, maintained by the framework.';
COMMENT ON COLUMN "roles"."deleted_at" IS 'Archive stamp; a non-null value hides the row from reads.';

CREATE TABLE "role_permissions" (
  "id" UUID NOT NULL,
  "role_id" UUID NOT NULL,
  "permission_id" UUID NOT NULL,
  "deleted_at" TIMESTAMPTZ NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "role_permissions_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "role_permissions_parent_fk" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON DELETE CASCADE
);
COMMENT ON TABLE "role_permissions" IS 'The permissions a role grants. One row per permission in the bundle, holding nothing but the catalog row''s id — so a retired-and-recreated permission is never silently re-granted, and the pair is never stored twice. The permissions collection of roles.';
COMMENT ON COLUMN "role_permissions"."id" IS 'Row id — a UUID v7 minted by the framework, not a sequence.';
COMMENT ON COLUMN "role_permissions"."role_id" IS 'The roles row this entry belongs to.';
COMMENT ON COLUMN "role_permissions"."permission_id" IS 'The catalog row this grant points at — the id and not the string, so a retired-and-recreated permission needs an explicit re-grant.';
COMMENT ON COLUMN "role_permissions"."deleted_at" IS 'Archive stamp; a non-null value hides the entry from reads.';
COMMENT ON COLUMN "role_permissions"."created_at" IS 'When the entry was created; written by the database default.';
COMMENT ON COLUMN "role_permissions"."updated_at" IS 'When the entry was last written, maintained by the framework.';
-- every read of the aggregate loads this collection by the key below.
CREATE INDEX "role_permissions_parent_idx" ON "role_permissions" ("role_id");

-- the repository binds this constraint's violation to a clean 409.
-- Scoped by TenantID: the value is unique WITHIN that, not across the
-- table. The domain's pre-check asks exactly this question, and
-- check refuses the two disagreeing.
-- Scoped to the ACTIVE rows: an archived row releases the value, so it
-- can be taken again while the old row stays as history.
CREATE UNIQUE INDEX "roles_tenant_id_role_key_key" ON "roles" ("tenant_id", "role_key") WHERE "deleted_at" IS NULL;

-- the repository binds this constraint's violation to a clean 409.
-- Scoped by role_id, the owner: an entry has no identity outside its
-- collection, and the same value under a different owner is a
-- different, legitimate row. This is the backstop businessIdentity
-- cannot be: that check sees ONE write, never the concurrent one.
-- Scoped to the ACTIVE rows: an archived row releases the value, so it
-- can be taken again while the old row stays as history.
CREATE UNIQUE INDEX "role_permissions_role_id_permission_id_key" ON "role_permissions" ("role_id", "permission_id") WHERE "deleted_at" IS NULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- Cross-aggregate foreign keys — added by hand, and not by the generator.
--
-- omnicore-gen writes the PARENT key (role_permissions.role_id → roles.id)
-- because a collection's owner is part of the aggregate it declares. A
-- reference to ANOTHER aggregate is outside what the spec language can say, so
-- these two are ours. The spec calls for both by name (§1 and §2).
-- ─────────────────────────────────────────────────────────────────────────────

-- The owner tenant. The target is tenants.tenant_id — the PUBLIC derived key
-- the tenant_id JWT claim carries and every tenant-scoped row references — and
-- NOT the surrogate tenants.id, so the row-level isolation filter compares the
-- claim directly instead of paying a lookup on every read. Postgres accepts the
-- unique INDEX tenants_tenant_id_key as an FK target; the index is unpartitioned
-- (the tenant handle is never reused, archived rows included), which is what
-- makes it eligible where a partial index would not be.
--
-- NO ACTION, deliberately: a tenant is archived and never purged, so this can
-- only ever fire against a hard DELETE nobody has a route for — and if one is
-- ever added, refusing to orphan a customer's roles is the answer we want.
ALTER TABLE "roles"
  ADD CONSTRAINT "roles_tenant_id_fk"
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("tenant_id");

-- The catalog row a grant points at. This is the EXISTENCE half of the
-- granted-permission-must-be-in-catalog rule, enforced by the database for
-- free; the domain rule still earns its keep for the ACTIVE half — an archived
-- permission satisfies this constraint and must still be refused — and for
-- turning a violation into a readable 422 instead of a raw constraint error.
--
-- The target is the PK, which is what makes it FK-able: the pair's own
-- uniqueness lives in a PARTIAL index, and Postgres will not point a foreign
-- key at one of those.
ALTER TABLE "role_permissions"
  ADD CONSTRAINT "role_permissions_permission_id_fk"
  FOREIGN KEY ("permission_id") REFERENCES "permissions" ("id");
