-- The reverse of 0007_authentication_attempts_manual.up.sql.
--
-- THIS DROP SILENTLY DISABLES THE LOCKOUT. With the table gone the sign-in has
-- nothing to count and password guessing becomes unlimited again — no error, no
-- warning, a service that boots perfectly green and no longer protects anything.
-- That is the reason to think before running it.
--
-- WHAT IT NO LONGER DESTROYS. The earlier shape of this table was also the
-- forensic record, and dropping it deleted the only copy of who had been trying
-- to get in. It is not any more: every attempt is published to the service's log
-- stream as it happens, so the narrative survives this statement. What dies here
-- is the lockout state and the lifetime totals — the counters, not the story.
--
-- The indexes and constraints go with the table; naming them would be noise.
DROP TABLE IF EXISTS "authentication_attempts";
