-- THIS FILE IS YOURS. Written once by omnicore-gen, never again.
--
-- The claims table on postgres.
--
-- entity:     Claim
-- spec:       specs/omnicore-gen/claim.omnicore.yaml
-- generator:  omnicore-gen (created this file, does not maintain it)
-- created:    2026-08-28
--
-- This pair was created once and is now yours. The generator will not
-- rewrite it, and you should not either once it has run anywhere: the
-- framework records an applied migration in its tracking table, so editing
-- the file changes the file and not the database. To change the shape, add a
-- NEW numbered pair in this folder — and remember that adding a NOT NULL
-- column to a table that already has rows needs a default, and that a rename
-- done as drop-then-add takes the data with it.
--
-- There is no checksum here on purpose: this file exists to be edited, so
-- hashing it would report drift every time you did the thing it is for.

-- claims
-- Generated by omnicore-gen from the Claim spec.

CREATE TABLE "claims" (
  "id" UUID NOT NULL,
  "tenant_id" UUID NOT NULL,
  "name" VARCHAR(64) NOT NULL,
  "value_type" VARCHAR(16) NOT NULL,
  "applies_to" VARCHAR(16) NOT NULL,
  "default_value" VARCHAR(256) NULL,
  "description" VARCHAR(500) NOT NULL,
  "revision" BIGINT NOT NULL DEFAULT 0,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "deleted_at" TIMESTAMPTZ NULL,
  CONSTRAINT "claims_pkey" PRIMARY KEY ("id")
);
COMMENT ON TABLE "claims" IS 'The vocabulary of tenant-defined claims: one row per claim name a token of this tenant may carry, holding the type its values must have, which identity kinds may hold one, and the default used when no principal-level value is set.';
COMMENT ON COLUMN "claims"."id" IS 'Row id — a UUID v7 minted by the framework, not a sequence.';
COMMENT ON COLUMN "claims"."tenant_id" IS 'The tenant that owns this claim definition. Immutable after creation — a claim never moves between tenants.';
COMMENT ON COLUMN "claims"."name" IS 'The exact name minted into the token, carrying the reserved x_ prefix. Unique within its tenant and immutable — every consuming service branches on this string.';
COMMENT ON COLUMN "claims"."value_type" IS 'What a value for this claim must parse as. The default below and every principal-level value are validated against it.';
COMMENT ON COLUMN "claims"."applies_to" IS 'Which identity kinds may hold a value for this claim: a user, a machine client, or both.';
COMMENT ON COLUMN "claims"."default_value" IS 'Level 2 of the resolution chain: the value every principal of this tenant gets when none is set on the principal itself. Null means there is no default and the claim is absent from the token.';
COMMENT ON COLUMN "claims"."description" IS 'What the value means, in the tenant''s own words, for the operator filling it in.';
COMMENT ON COLUMN "claims"."revision" IS 'Optimistic-concurrency stamp: bumped on every write, and the value each update is guarded on. Maintained by the framework.';
COMMENT ON COLUMN "claims"."created_at" IS 'When the row was created; written by the database default.';
COMMENT ON COLUMN "claims"."updated_at" IS 'When the row was last written, maintained by the framework.';
COMMENT ON COLUMN "claims"."deleted_at" IS 'Archive stamp; a non-null value hides the row from reads.';

-- the repository binds this constraint's violation to a clean 409.
-- Scoped by TenantID: the value is unique WITHIN that, not across the
-- table. The domain's pre-check asks exactly this question, and
-- check refuses the two disagreeing.
-- Scoped to the ACTIVE rows: an archived row releases the value, so it
-- can be taken again while the old row stays as history.
CREATE UNIQUE INDEX "claims_tenant_id_name_key" ON "claims" ("tenant_id", "name") WHERE "deleted_at" IS NULL;

-- Added by hand: a reference to ANOTHER aggregate is outside the generator's
-- spec language, so this block is the part of the pair that is not emitted.
-- The same append roles and groups both carry.
--
-- claims.tenant_id targets tenants.id — the primary key, and the tenant's ONLY
-- identifier. Because the tenant_id token claim carries this same value, the
-- row-level isolation filter compares a plain local column against the claim,
-- with no translation step anywhere.
--
-- It is also what makes the repository's INNER join safe: the column is NOT
-- NULL and referential integrity guarantees the counterpart, so no definition
-- is ever silently dropped from a read — including the FindByID the write
-- handlers load through, where a dropped row would answer 404 for a row that
-- exists.
--
-- NO ACTION: a tenant is archived, never hard-deleted, so there is no cascade
-- to define — and if anyone ever tries the delete, refusing it while claim
-- definitions still point at the tenant is the correct answer.
ALTER TABLE "claims"
  ADD CONSTRAINT "claims_tenant_fk"
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id");
