// Code generated by omnicore-gen. DO NOT EDIT.
//
// The translation coverage test — every notification must be translatable
// in every catalog.
//
// entity:     Role
// spec:       specs/omnicore-gen/role.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-21
// checksum:   sha256:a7b70af7151c68247fa6b7071ca7719230b8d43edce7f18e9b5115ec96d85eff
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package translations

import (
	"testing"

	"github.com/ClaudioSchirmer/omnicore/application/configuration"
	"github.com/ClaudioSchirmer/omnicore/application/translation"
)

// Each of the seven catalogs answers every notification this entity raises.
//
// A missing entry is not a compile error and not a crash: the caller simply
// receives the key instead of a sentence, in one language, usually the one
// nobody on the team reads.
func TestRoleNotificationsAreTranslated(t *testing.T) {
	keys := []string{
		"RoleKeyAlreadyExistsNotification",
		"RoleKeyIsImmutableNotification",
		"RoleTenantIsImmutableNotification",
		"RoleTenantDoesNotExistNotification",
		"PermissionNotInCatalogNotification",
		"RoleAlreadyGrantsPermissionNotification",
		"TooManyPermissionsInRoleNotification",
		"CannotGrantUnheldPermissionNotification",
		"CannotGrantWildcardPermissionNotification",
		"InvalidRoleKeyNotification",
	}
	catalogs := map[string]map[string]string{
		"ptbr": ptbr{}.Translations(),
		"eng":  eng{}.Translations(),
		"esp":  esp{}.Translations(),
		"fra":  fra{}.Translations(),
		"deu":  deu{}.Translations(),
		"ita":  ita{}.Translations(),
		"nld":  nld{}.Translations(),
	}
	for lang, catalog := range catalogs {
		for _, key := range keys {
			if text, ok := catalog[key]; !ok || text == "" {
				t.Errorf("%s has no text in %s", key, lang)
			}
		}
	}
}

// Each catalog is registered as the language it claims.
//
// The framework picks a catalog by the constant the module answers, and the
// constants are not spelled like the files (esp/ES, fra/FR, deu/DE, ita/IT,
// nld/NL) — a pairing that is easy to write once and wrong forever.
func TestRoleCatalogsAnswerTheirOwnLanguage(t *testing.T) {
	for want, module := range map[configuration.Language]translation.Module{
		configuration.LangPTBR: PTBR(),
		configuration.LangENG:  ENG(),
		configuration.LangES:   ESP(),
		configuration.LangFR:   FRA(),
		configuration.LangDE:   DEU(),
		configuration.LangIT:   ITA(),
		configuration.LangNL:   NLD(),
	} {
		if got := module.Language(); got != want {
			t.Errorf("a catalog answers %v, it is registered as %v", got, want)
		}
	}
}
