// Code generated by omnicore-gen. DO NOT EDIT.
//
// Tests for the claim_applies_to value object.
//
// entity:     Claim
// spec:       specs/omnicore-gen/claim.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-01
// checksum:   sha256:3b613023076f04007cddb1b29c0f3337a8680aeec2c6a1437795bc227a4c2752
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package vos

import "testing"

// ClaimAppliesTo declares its members; the framework validates membership
// against exactly this set.
func TestClaimAppliesToMembers(t *testing.T) {
	members := ClaimAppliesTo("").Values()
	if len(members) != 3 {
		t.Fatalf("expected 3 members, got %d", len(members))
	}
	// The unknown sentinel must NOT be a member: it is where an out-of-set
	// value lands, so accepting it would defeat the whole check.
	for _, m := range members {
		if m == ClaimAppliesToUnknown {
			t.Error("the unknown sentinel must not be a declared member")
		}
	}
}

// A declared member of ClaimAppliesTo is accepted and reads back unchanged.
//
// The pair matters: a value object that rejects everything passes the negative
// test below and is still broken.
// A value outside ClaimAppliesTo's set is not one of its members.
//
// An enum declares no rule of its own: the framework decides membership from
// Values(), and answers with the unknown notification. So what is under test
// is the SET — that a member is in it and a stranger is not.
func TestClaimAppliesToMembership(t *testing.T) {
	in := func(v ClaimAppliesTo) bool {
		for _, m := range v.Values() {
			if m == v {
				return true
			}
		}
		return false
	}
	if !in(ClaimAppliesToUser) {
		t.Error("a declared member is not in its own set")
	}
	if in(ClaimAppliesTo("!!not-valid!!")) {
		t.Error("a value outside the set was found in it")
	}
	if ClaimAppliesToUser.Value() == "" {
		t.Error("a member reads back empty")
	}
	if ClaimAppliesToUser.UnknownNotification() == nil {
		t.Error("the enum has no notification for an unknown value")
	}
}
