// Code generated by omnicore-gen. DO NOT EDIT.
//
// Tests for 1 value object(s).
//
// entity:     Client
// spec:       specs/omnicore-gen/client.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-26
// checksum:   sha256:ab988a5bf687b70d921eec5e2b98c074ce8acb58ec90b417b7ed5a6c2d9858ea
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package vos

import "testing"

// ClientStatus declares its members; the framework validates membership
// against exactly this set.
func TestClientStatusMembers(t *testing.T) {
	members := ClientStatus("").Values()
	if len(members) != 2 {
		t.Fatalf("expected 2 members, got %d", len(members))
	}
	// The unknown sentinel must NOT be a member: it is where an out-of-set
	// value lands, so accepting it would defeat the whole check.
	for _, m := range members {
		if m == ClientStatusUnknown {
			t.Error("the unknown sentinel must not be a declared member")
		}
	}
}

// A declared member of ClientStatus is accepted and reads back unchanged.
//
// The pair matters: a value object that rejects everything passes the negative
// test below and is still broken.
// A value outside ClientStatus's set is not one of its members.
//
// An enum declares no rule of its own: the framework decides membership from
// Values(), and answers with the unknown notification. So what is under test
// is the SET — that a member is in it and a stranger is not.
func TestClientStatusMembership(t *testing.T) {
	in := func(v ClientStatus) bool {
		for _, m := range v.Values() {
			if m == v {
				return true
			}
		}
		return false
	}
	if !in(ClientStatusActive) {
		t.Error("a declared member is not in its own set")
	}
	if in(ClientStatus("!!not-valid!!")) {
		t.Error("a value outside the set was found in it")
	}
	if ClientStatusActive.Value() == "" {
		t.Error("a member reads back empty")
	}
	if ClientStatusActive.UnknownNotification() == nil {
		t.Error("the enum has no notification for an unknown value")
	}
}
