// Code generated by omnicore-gen. DO NOT EDIT.
//
// The vos package documentation.
//
// entity:     Permission
// spec:       specs/omnicore-gen/permission.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-24
// checksum:   sha256:841d8959483564911160ebd0f88e46abe85637b1ad20d6d57545827b043273da
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

// Package vos holds the value objects: the types that carry a field's own
// rule.
//
// The framework discovers a field of one of these types and validates it on
// every write, with no registration. That is why an aggregate's BuildRules
// never repeats a format, length, range or membership check — the rule has
// exactly one home, here.
//
// This package is a leaf: it imports nothing from the rest of the domain.
package vos
