// Code generated by omnicore-gen. DO NOT EDIT.
//
// Tests for 4 value object(s).
//
// entity:     Tenant
// spec:       specs/omnicore-gen/tenant.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-19
// checksum:   sha256:6bd8981e08f8c8b97712895e9b1b1d080194f8fcdd7048d0b4905526321ce5d0
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package vos

import "testing"

// TenantStatus declares its members; the framework validates membership
// against exactly this set.
func TestTenantStatusMembers(t *testing.T) {
	members := TenantStatus("").Values()
	if len(members) != 3 {
		t.Fatalf("expected 3 members, got %d", len(members))
	}
	// The unknown sentinel must NOT be a member: it is where an out-of-set
	// value lands, so accepting it would defeat the whole check.
	for _, m := range members {
		if m == TenantStatusUnknown {
			t.Error("the unknown sentinel must not be a declared member")
		}
	}
}

// A declared member of TenantStatus is accepted and reads back unchanged.
//
// The pair matters: a value object that rejects everything passes the negative
// test below and is still broken.
// A value outside TenantStatus's set is not one of its members.
//
// An enum declares no rule of its own: the framework decides membership from
// Values(), and answers with the unknown notification. So what is under test
// is the SET — that a member is in it and a stranger is not.
func TestTenantStatusMembership(t *testing.T) {
	in := func(v TenantStatus) bool {
		for _, m := range v.Values() {
			if m == v {
				return true
			}
		}
		return false
	}
	if !in(TenantStatusTrial) {
		t.Error("a declared member is not in its own set")
	}
	if in(TenantStatus("!!not-valid!!")) {
		t.Error("a value outside the set was found in it")
	}
	if TenantStatusTrial.Value() == "" {
		t.Error("a member reads back empty")
	}
	if TenantStatusTrial.UnknownNotification() == nil {
		t.Error("the enum has no notification for an unknown value")
	}
}
