// Code generated by omnicore-gen. DO NOT EDIT.
//
// Tests for the user_status value object.
//
// entity:     User
// spec:       specs/omnicore-gen/user.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-01
// checksum:   sha256:6194803f5183ce1c4d2fb745ccd24a417a7740c4db6d62bd5b50369b2ace0cfb
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package vos

import "testing"

// UserStatus declares its members; the framework validates membership against
// exactly this set.
func TestUserStatusMembers(t *testing.T) {
	members := UserStatus("").Values()
	if len(members) != 2 {
		t.Fatalf("expected 2 members, got %d", len(members))
	}
	// The unknown sentinel must NOT be a member: it is where an out-of-set
	// value lands, so accepting it would defeat the whole check.
	for _, m := range members {
		if m == UserStatusUnknown {
			t.Error("the unknown sentinel must not be a declared member")
		}
	}
}

// A declared member of UserStatus is accepted and reads back unchanged.
//
// The pair matters: a value object that rejects everything passes the negative
// test below and is still broken.
// A value outside UserStatus's set is not one of its members.
//
// An enum declares no rule of its own: the framework decides membership from
// Values(), and answers with the unknown notification. So what is under test
// is the SET — that a member is in it and a stranger is not.
func TestUserStatusMembership(t *testing.T) {
	in := func(v UserStatus) bool {
		for _, m := range v.Values() {
			if m == v {
				return true
			}
		}
		return false
	}
	if !in(UserStatusActive) {
		t.Error("a declared member is not in its own set")
	}
	if in(UserStatus("!!not-valid!!")) {
		t.Error("a value outside the set was found in it")
	}
	if UserStatusActive.Value() == "" {
		t.Error("a member reads back empty")
	}
	if UserStatusActive.UnknownNotification() == nil {
		t.Error("the enum has no notification for an unknown value")
	}
}
