// Code generated by omnicore-gen. DO NOT EDIT.
//
// The Claim service implementation.
//
// entity:     Claim
// spec:       specs/omnicore-gen/claim.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-28
// checksum:   sha256:b55f63c37e1f705e4baa415899cb9f4167541f5b12f248b677fe9a75a5809942
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package infra

import (
	"context"
	"github.com/ClaudioSchirmer/omnicore/application/configuration"
	"github.com/ClaudioSchirmer/omnicore/application/persistence"
	"github.com/ClaudioSchirmer/omnicore/domain"

	appdomain "github.com/ClaudioSchirmer/authcore/internal/domain"
	"github.com/ClaudioSchirmer/omnicore/infra/db/criteria"
)

// ClaimServiceImpl answers the port's questions straight from the store.
//
// It carries a request context so its queries run under the request's deadline
// and cancellation. The wired instance is a singleton shared by every request,
// so binding is done by returning a COPY rather than by mutating the receiver.
type ClaimServiceImpl struct {
	domain.ServiceBase
	repo *ClaimRepository
	ctx  *configuration.AppContext
}

func NewClaimServiceImpl(repo *ClaimRepository) *ClaimServiceImpl {
	return &ClaimServiceImpl{repo: repo}
}

// ScopedService binds this service to one request.
//
// The framework calls it before the rules run. Without it, every probe would
// query on a background context — outside the request's timeout, its
// cancellation and its trace.
func (s *ClaimServiceImpl) ScopedService(ctx *configuration.AppContext) domain.Service {
	bound := *s
	bound.ctx = ctx
	return &bound
}

// queryContext falls back to a background context only for use outside a
// request — tests and background jobs.
func (s *ClaimServiceImpl) queryContext() context.Context {
	if s.ctx != nil {
		return s.ctx
	}
	return context.Background()
}

// ClaimNameTaken Reports whether another ACTIVE claim in the same tenant
// already holds this name. Excludes the row being updated.
//
// It asks the database the question directly instead of loading aggregates and
// counting them in Go — the probe exists precisely so a yes/no question does
// not pay for full hydration.
//
// On a query failure it PANICS, and that is the intended behaviour: the
// pipeline turns the panic into a 500 and the write never happens. Returning a
// plausible answer instead would skip the very invariant this exists to
// enforce.
func (s *ClaimServiceImpl) ClaimNameTaken(tenantID domain.ID, name string, selfID domain.ID) bool {
	conds := []criteria.Expr{
		criteria.Eq("TenantID", tenantID),
		criteria.Eq("Name", name),
	}
	// Exclude the row being updated: without this, updating a unique field
	// would always report the row colliding with itself.
	if !selfID.IsEmpty() {
		conds = append(conds, criteria.Ne("ID", selfID))
	}
	q := criteria.Where(criteria.And(conds...))
	// Archived rows do not take part: a removed row must not block a new one.
	// The active scope is the query default, so nothing is added here.

	found, err := s.repo.Loader.Exists(s.queryContext(), q)
	if err != nil {
		panic("Claim: ClaimNameTaken probe failed")
	}
	return found
}

var (
	_ appdomain.ClaimService            = (*ClaimServiceImpl)(nil)
	_ persistence.ScopedServiceProvider = (*ClaimServiceImpl)(nil)
)
