// Code generated by omnicore-gen. DO NOT EDIT.
//
// The Claim repository and its constraint bindings.
//
// entity:     Claim
// spec:       specs/omnicore-gen/claim.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-28
// checksum:   sha256:3f38d2371e9f9ac151a7fc2b4a5d3fc206f1807cfe39383a2f5abe8a8b7177a4
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package infra

import (
	appdomain "github.com/ClaudioSchirmer/authcore/internal/domain"
	"github.com/ClaudioSchirmer/authcore/internal/infra/schemas"
	"github.com/ClaudioSchirmer/omnicore/application/persistence"
	"github.com/ClaudioSchirmer/omnicore/domain"
	"github.com/ClaudioSchirmer/omnicore/infra/db/command/read"
	"github.com/ClaudioSchirmer/omnicore/infra/db/command/write"
	"github.com/ClaudioSchirmer/omnicore/infra/db/core"
)

// ClaimRepository persists the aggregate.
//
// The engine parameter is the neutral relational engine, so changing dialect
// never edits this file — it is a configuration change plus the engine's
// build tag.
type ClaimRepository struct {
	read.BaseAggregateRepository[*appdomain.Claim]
}

func NewClaimRepository(engine core.RelationalEngine) *ClaimRepository {
	r := &ClaimRepository{
		BaseAggregateRepository: read.NewBaseAggregateRepository[*appdomain.Claim](
			engine,
			func() *appdomain.Claim { return &appdomain.Claim{} },
		),
	}

	// A violation reaches the caller as the notification bound here; without a
	// binding it would surface as a raw 500. Each dialect reports the violation
	// differently, so every target dialect's key form is bound.
	r.Constraints = map[string]write.ConstraintBinding{
		"claims_pkey":               {Notification: domain.EntityAlreadyAddedNotification{}, Field: "id"},
		"claims_tenant_id_name_key": {Notification: appdomain.ClaimNameAlreadyExistsNotification{}, Field: "name"},
	}

	r.WithSchema(schemas.ClaimSchema())

	// Read joins: read-only traversals across a foreign key into another
	// aggregate. They fill ordinary fields of the entity on every load and are
	// absent from the TableSchema, so no write can carry them.
	r.WithJoins(
		// → Tenant, always in the FROM. No counterpart drops the aggregate
		// from EVERY read, FindByID included — which is why the framework
		// allows it only over a non-nullable key.
		read.InnerJoin(schemas.TenantSchema()).
			On("tenant_id").
			Field("TenantWorkspace", "workspace").
			Field("TenantStatus", "status"),
	)
	return r
}

var _ persistence.ScopedRepository[*appdomain.Claim] = (*ClaimRepository)(nil)
