// Code generated by omnicore-gen. DO NOT EDIT.
//
// The Group repository and its constraint bindings.
//
// entity:     Group
// spec:       specs/omnicore-gen/group.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-31
// checksum:   sha256:799cfef8524752c07abc491bd7a2a72b4d22586b69360e5ff58e7485f0ecb546
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package infra

import (
	appdomain "github.com/ClaudioSchirmer/authcore/internal/domain"
	"github.com/ClaudioSchirmer/authcore/internal/infra/schemas"
	"github.com/ClaudioSchirmer/omnicore/application/persistence"
	"github.com/ClaudioSchirmer/omnicore/domain"
	"github.com/ClaudioSchirmer/omnicore/infra/db/command/read"
	"github.com/ClaudioSchirmer/omnicore/infra/db/command/write"
	"github.com/ClaudioSchirmer/omnicore/infra/db/core"
)

// GroupRepository persists the aggregate.
//
// The engine parameter is the neutral relational engine, so changing dialect
// never edits this file — it is a configuration change plus the engine's
// build tag.
type GroupRepository struct {
	read.BaseAggregateRepository[*appdomain.Group]
}

func NewGroupRepository(engine core.RelationalEngine) *GroupRepository {
	r := &GroupRepository{
		BaseAggregateRepository: read.NewBaseAggregateRepository[*appdomain.Group](
			engine,
			func() *appdomain.Group { return &appdomain.Group{} },
		),
	}

	// A violation reaches the caller as the notification bound here; without a
	// binding it would surface as a raw 500. Each dialect reports the violation
	// differently, so every target dialect's key form is bound.
	r.Constraints = map[string]write.ConstraintBinding{
		"groups_pkey":                      {Notification: domain.EntityAlreadyAddedNotification{}, Field: "id"},
		"groups_tenant_id_group_key_key":   {Notification: appdomain.GroupKeyAlreadyExistsNotification{}, Field: "key"},
		"group_roles_group_id_role_id_key": {Notification: appdomain.GroupAlreadyGrantsRoleNotification{}, Field: "roles"},
	}

	r.WithSchema(schemas.GroupSchema())

	// Read joins: read-only traversals across a foreign key into another
	// aggregate. They fill ordinary fields of the entity on every load and are
	// absent from the TableSchema, so no write can carry them.
	//
	// Each target is reduced with AsDirectSchema(): a traversal puts ONE table
	// in the FROM, so it takes a schema that IS one table. The reduction is a
	// copy — the target's own declaration is untouched — and it drops exactly
	// what a join never enters: that aggregate's children, facets and shared
	// base.
	r.WithJoins(
		// → Tenant, always in the FROM. No counterpart drops the aggregate
		// from EVERY read, FindByID included — which is why the framework
		// allows it only over a non-nullable key.
		read.InnerJoin(schemas.TenantSchema().AsDirectSchema()).
			On("tenant_id").
			Field("TenantWorkspace", "workspace").
			Field("TenantStatus", "status"),
		// GroupRole → Role, on every loaded entry. No counterpart drops the
		// ENTRY, not the root — a hole in the collection.
		read.InnerJoinInChild(schemas.GroupRoleSchema()).
			To(schemas.RoleSchema().AsDirectSchema()).
			On("role_id").
			Field("RoleKey", "role_key").
			Field("RoleName", "name"),
	)
	return r
}

var _ persistence.ScopedRepository[*appdomain.Group] = (*GroupRepository)(nil)
