// Code generated by omnicore-gen. DO NOT EDIT.
//
// The Role repository and its constraint bindings.
//
// entity:     Role
// spec:       specs/omnicore-gen/role.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-21
// checksum:   sha256:741da5efcbe9cc199773a6b3704a0276950621085a9e527fe87fac9680c20610
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package infra

import (
	appdomain "github.com/ClaudioSchirmer/authcore/internal/domain"
	"github.com/ClaudioSchirmer/authcore/internal/infra/schemas"
	"github.com/ClaudioSchirmer/omnicore/application/persistence"
	"github.com/ClaudioSchirmer/omnicore/domain"
	"github.com/ClaudioSchirmer/omnicore/infra/db/command/read"
	"github.com/ClaudioSchirmer/omnicore/infra/db/command/write"
	"github.com/ClaudioSchirmer/omnicore/infra/db/core"
)

// RoleRepository persists the aggregate.
//
// The engine parameter is the neutral relational engine, so changing dialect
// never edits this file — it is a configuration change plus the engine's
// build tag.
type RoleRepository struct {
	read.BaseAggregateRepository[*appdomain.Role]
}

func NewRoleRepository(engine core.RelationalEngine) *RoleRepository {
	r := &RoleRepository{
		BaseAggregateRepository: read.NewBaseAggregateRepository[*appdomain.Role](
			engine,
			func() *appdomain.Role { return &appdomain.Role{} },
		),
	}

	// A violation reaches the caller as the notification bound here; without a
	// binding it would surface as a raw 500. Each dialect reports the violation
	// differently, so every target dialect's key form is bound.
	r.Constraints = map[string]write.ConstraintBinding{
		"roles_pkey":                                 {Notification: domain.EntityAlreadyAddedNotification{}, Field: "id"},
		"roles_tenant_id_role_key_key":               {Notification: appdomain.RoleKeyAlreadyExistsNotification{}, Field: "key"},
		"role_permissions_role_id_permission_id_key": {Notification: appdomain.RoleAlreadyGrantsPermissionNotification{}, Field: "permissions"},
	}

	r.WithSchema(schemas.RoleSchema())
	return r
}

var _ persistence.ScopedRepository[*appdomain.Role] = (*RoleRepository)(nil)
