// Code generated by omnicore-gen. DO NOT EDIT.
//
// The Tenant service implementation.
//
// entity:     Tenant
// spec:       specs/omnicore-gen/tenant.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-24
// checksum:   sha256:f05581c6cea0c5bcd3ee8336bab6a4053be985380b06e02bf69bd62069dab09c
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package infra

import (
	"context"
	"github.com/ClaudioSchirmer/omnicore/application/configuration"
	"github.com/ClaudioSchirmer/omnicore/application/persistence"
	"github.com/ClaudioSchirmer/omnicore/domain"

	appdomain "github.com/ClaudioSchirmer/authcore/internal/domain"
	"github.com/ClaudioSchirmer/omnicore/infra/db/criteria"
)

// TenantServiceImpl answers the port's questions straight from the store.
//
// It carries a request context so its queries run under the request's deadline
// and cancellation. The wired instance is a singleton shared by every request,
// so binding is done by returning a COPY rather than by mutating the receiver.
type TenantServiceImpl struct {
	domain.ServiceBase
	repo *TenantRepository
	ctx  *configuration.AppContext
}

func NewTenantServiceImpl(repo *TenantRepository) *TenantServiceImpl {
	return &TenantServiceImpl{repo: repo}
}

// ScopedService binds this service to one request.
//
// The framework calls it before the rules run. Without it, every probe would
// query on a background context — outside the request's timeout, its
// cancellation and its trace.
func (s *TenantServiceImpl) ScopedService(ctx *configuration.AppContext) domain.Service {
	bound := *s
	bound.ctx = ctx
	return &bound
}

// queryContext falls back to a background context only for use outside a
// request — tests and background jobs.
func (s *TenantServiceImpl) queryContext() context.Context {
	if s.ctx != nil {
		return s.ctx
	}
	return context.Background()
}

// WorkspaceTaken Whether any tenant, archived ones included, already holds
// this workspace handle.
//
// It asks the database the question directly instead of loading aggregates and
// counting them in Go — the probe exists precisely so a yes/no question does
// not pay for full hydration.
//
// On a query failure it PANICS, and that is the intended behaviour: the
// pipeline turns the panic into a 500 and the write never happens. Returning a
// plausible answer instead would skip the very invariant this exists to
// enforce.
func (s *TenantServiceImpl) WorkspaceTaken(workspace string, selfID domain.ID) bool {
	conds := []criteria.Expr{
		criteria.Eq("Workspace", workspace),
	}
	// Exclude the row being updated: without this, updating a unique field
	// would always report the row colliding with itself.
	if !selfID.IsEmpty() {
		conds = append(conds, criteria.Ne("ID", selfID))
	}
	q := criteria.Where(criteria.And(conds...))
	q = q.IncludeArchived()

	found, err := s.repo.Loader.Exists(s.queryContext(), q)
	if err != nil {
		panic("Tenant: WorkspaceTaken probe failed")
	}
	return found
}

var (
	_ appdomain.TenantService           = (*TenantServiceImpl)(nil)
	_ persistence.ScopedServiceProvider = (*TenantServiceImpl)(nil)
)
