// Code generated by omnicore-gen. DO NOT EDIT.
//
// The Tenant service implementation.
//
// entity:     Tenant
// spec:       specs/omnicore-gen/tenant.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-29
// checksum:   sha256:1c45f1f10e5ada597c85b399c2011312a52469efba0d99c0341a7de52046ff04
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package infra

import (
	"context"

	"github.com/ClaudioSchirmer/omnicore/application/configuration"
	"github.com/ClaudioSchirmer/omnicore/application/persistence"
	"github.com/ClaudioSchirmer/omnicore/domain"

	appdomain "github.com/ClaudioSchirmer/authcore/internal/domain"
	"github.com/ClaudioSchirmer/omnicore/infra/db/criteria"
)

// TenantServiceImpl answers the port's questions straight from the store.
//
// It carries a request context so its queries run under the request's deadline
// and cancellation. The wired instance is a singleton shared by every request,
// so binding is done by returning a COPY rather than by mutating the receiver.
type TenantServiceImpl struct {
	domain.ServiceBase
	repo *TenantRepository
	ctx  *configuration.AppContext
}

func NewTenantServiceImpl(repo *TenantRepository) *TenantServiceImpl {
	return &TenantServiceImpl{repo: repo}
}

// ScopedService binds this service to one request.
//
// The framework calls it before the rules run. Without it, every probe would
// query on a background context — outside the request's timeout, its
// cancellation and its trace.
func (s *TenantServiceImpl) ScopedService(ctx *configuration.AppContext) domain.Service {
	bound := *s
	bound.ctx = ctx
	return &bound
}

// queryContext falls back to a background context only for use outside a
// request — tests and background jobs.
func (s *TenantServiceImpl) queryContext() context.Context {
	if s.ctx != nil {
		return s.ctx
	}
	return context.Background()
}

// WorkspaceTaken Whether any tenant, archived ones included, already holds
// this workspace handle.
//
// It asks the database the question directly instead of loading aggregates and
// counting them in Go — the probe exists precisely so a yes/no question does
// not pay for full hydration.
//
// On a query failure it PANICS, and that is the intended behaviour: the
// pipeline turns the panic into a 500 and the write never happens. Returning a
// plausible answer instead would skip the very invariant this exists to
// enforce.
func (s *TenantServiceImpl) WorkspaceTaken(workspace string, selfID domain.ID) bool {
	conds := []criteria.Expr{
		criteria.Eq("Workspace", workspace),
	}
	// Exclude the row being updated: without this, updating a unique field
	// would always report the row colliding with itself.
	if !selfID.IsEmpty() {
		conds = append(conds, criteria.Ne("ID", selfID))
	}
	q := criteria.Where(criteria.And(conds...))
	q = q.IncludeArchived()

	found, err := s.repo.Loader.Exists(s.queryContext(), q)
	if err != nil {
		panic("Tenant: WorkspaceTaken probe failed")
	}
	return found
}

var (
	_ appdomain.TenantService           = (*TenantServiceImpl)(nil)
	_ persistence.ScopedServiceProvider = (*TenantServiceImpl)(nil)
)
