// Code generated by omnicore-gen. DO NOT EDIT.
//
// The Tenant repository and its constraint bindings.
//
// entity:     Tenant
// spec:       specs/omnicore-gen/tenant.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-29
// checksum:   sha256:dcedd04325afde3185ac4c36da5d018b9461cf631068e2745d2e65538100cf2d
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package infra

import (
	appdomain "github.com/ClaudioSchirmer/authcore/internal/domain"
	"github.com/ClaudioSchirmer/authcore/internal/infra/schemas"
	"github.com/ClaudioSchirmer/omnicore/application/persistence"
	"github.com/ClaudioSchirmer/omnicore/domain"
	"github.com/ClaudioSchirmer/omnicore/infra/db/command/read"
	"github.com/ClaudioSchirmer/omnicore/infra/db/command/write"
	"github.com/ClaudioSchirmer/omnicore/infra/db/core"
)

// TenantRepository persists the aggregate.
//
// The engine parameter is the neutral relational engine, so changing dialect
// never edits this file — it is a configuration change plus the engine's
// build tag.
type TenantRepository struct {
	read.BaseAggregateRepository[*appdomain.Tenant]
}

func NewTenantRepository(engine core.RelationalEngine) *TenantRepository {
	r := &TenantRepository{
		BaseAggregateRepository: read.NewBaseAggregateRepository[*appdomain.Tenant](
			engine,
			func() *appdomain.Tenant { return &appdomain.Tenant{} },
		),
	}

	// A violation reaches the caller as the notification bound here; without a
	// binding it would surface as a raw 500. Each dialect reports the violation
	// differently, so every target dialect's key form is bound.
	r.Constraints = map[string]write.ConstraintBinding{
		"tenants_pkey":          {Notification: domain.EntityAlreadyAddedNotification{}, Field: "id"},
		"tenants_workspace_key": {Notification: appdomain.TenantWorkspaceAlreadyExistsNotification{}, Field: "workspace"},
	}

	r.WithSchema(schemas.TenantSchema())
	return r
}

var _ persistence.ScopedRepository[*appdomain.Tenant] = (*TenantRepository)(nil)
