// Code generated by omnicore-gen. DO NOT EDIT.
//
// The view definition test — it builds the definition, so a boot panic is
// a test failure.
//
// entity:     Permission
// spec:       specs/omnicore-gen/permission.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-24
// checksum:   sha256:5b4502278e757a2bc3d0daf1b24ee2abb4ede72d266900e36d5cb1007fcaa5ff
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package views

import "testing"

// The view builds and answers the name the spec declared.
//
// A view is validated as it is declared: an index on a path it cannot resolve,
// a projection of a field that is not there. Every one of those aborts the
// boot, and building the definition here turns that into a test failure.
//
// The loader is nil on purpose — nothing is read here; the declaration
// itself is what is under test. The framework's own boot validation rejects a
// nil loader, which is a service-wide check over every declared read model
// rather than a property of this one.
func TestPermissionViewBuilds(t *testing.T) {
	v := PermissionView(nil)
	if v == nil {
		t.Fatal("the view definition is nil")
	}
	if got := v.Name(); got != "permissions" {
		t.Errorf("the view is named %q, the spec says %q", got, "permissions")
	}
}
