// Code generated by omnicore-gen. DO NOT EDIT.
//
// The permissions view (relational-backed).
//
// entity:     Permission
// spec:       specs/omnicore-gen/permission.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-20
// checksum:   sha256:a601e1c5cf878dcd3c699cee0d5ff4f66ceb5a23e204965a2eebf0de41435f3b
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package views

import (
	"github.com/ClaudioSchirmer/authcore/internal/infra/schemas"
	"github.com/ClaudioSchirmer/omnicore/infra/db/query"
)

// PermissionView is the read side of the aggregate.
//
// The schema alone materialises the document — the fields it maps are what
// the view serves, with no field list repeated here.
//
// This view reads straight from the relational tables, so it has no separate
// collection and a write is visible to the very next read.
//
// Version identifies the shape. Bump it whenever the projected shape changes,
// or the framework aborts the boot rather than serving a stale projection.
func PermissionView(source query.RelationalReader) *query.ViewDefinition {
	v := query.View("permissions").
		Version(1).
		Schema(schemas.PermissionSchema())
	// A ceiling on how much one request may pull back.
	v = v.MaxLimit(200)
	// The aggregate's OWN loader, shared with the repository — never a second one.
	v = v.RelationalSource(source)
	return v
}
