// Code generated by omnicore-gen. DO NOT EDIT.
//
// The tenants view (relational-backed).
//
// entity:     Tenant
// spec:       specs/omnicore-gen/tenant.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-24
// checksum:   sha256:24052f9c01e77966e5310834b780fcb26b3cb4e18bc897675fadf7343e05d3aa
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package views

import "github.com/ClaudioSchirmer/omnicore/infra/db/query"

// TenantView is the read side of the aggregate, served straight from the
// relational tables.
//
// There is no projection between the write and this read: a write is visible
// to the very next read, with no CDC hop to wait for.
//
// The loader carries the schema, so nothing about the shape is restated here
// — and there is no Version, because a read model with no materialisation
// has no stored shape to grow stale against.
func TenantView(loader query.AggregateReader) *query.RelationalViewDefinition {
	// The aggregate's OWN loader, shared with the repository — never a second one.
	v := query.RelationalView("tenants", loader)
	return v
}
