// Code generated by omnicore-gen. DO NOT EDIT.
//
// The users view (relational-backed).
//
// entity:     User
// spec:       specs/omnicore-gen/user.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-29
// checksum:   sha256:22f3c4f0ca5ee6a8188e5e94dae4a0f8871300803a837cf25315ad52004d53e0
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package views

import "github.com/ClaudioSchirmer/omnicore/infra/db/query"

// UserView is the read side of the aggregate, served straight from the
// relational tables.
//
// There is no projection between the write and this read: a write is visible
// to the very next read, with no CDC hop to wait for.
//
// The loader carries the schema, so nothing about the shape is restated here
// — and there is no Version, because a read model with no materialisation
// has no stored shape to grow stale against.
func UserView(loader query.AggregateReader) *query.RelationalViewDefinition {
	// The aggregate's OWN loader, shared with the repository — never a second one.
	v := query.RelationalView("users", loader)
	return v
}
