// Code generated by omnicore-gen. DO NOT EDIT.
//
// The wire mapper tests for add_user_group.go.
//
// entity:     User
// spec:       specs/omnicore-gen/user.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-01
// checksum:   sha256:57fac41c75ca9570511f7f14b68d3f33f6e4c9766c6a3507bb29f2209525b998
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package requests

import (
	"testing"

	"github.com/ClaudioSchirmer/omnicore/domain"

	"github.com/ClaudioSchirmer/authcore/internal/application/commands"

	cmddtos "github.com/ClaudioSchirmer/authcore/internal/application/commands/dtos"
	webdtos "github.com/ClaudioSchirmer/authcore/internal/web/requests/dtos"
)

// AddUserGroupRequest carries the entry into its command.
//
// The body is the same entry shape the root's own body carries, so a field
// forgotten here is saved as missing on a request that answered 201.
func TestAddUserGroupRequest_CarriesEveryField(t *testing.T) {
	r := AddUserGroupRequest{UserGroupRequest: webdtos.UserGroupRequest{
		GroupID: domain.NewID("0198f3e0-9c25-7a1f-b73d-5e08c4a29f61"),
	}}
	cmd := r.ToCommand()
	if cmd.GroupID != domain.NewID("0198f3e0-9c25-7a1f-b73d-5e08c4a29f61") {
		t.Errorf("GroupID did not reach the command")
	}
}

// The UserGroup responses carry the stored entry back to the caller.
//
// The entry comes back with the id the SERVER minted, which is how the caller
// addresses it afterwards — a response mapper that drops it answers 201 with
// nothing to act on.
func TestAddUserGroupResponse_CarriesTheStoredEntry(t *testing.T) {
	ownerID := domain.NewRandomID()
	entryID := domain.NewRandomID()
	res := AddUserGroupResponse{}.FromResult(commands.AddUserGroupResult{
		UserID: ownerID,
		UserGroup: cmddtos.UserGroupResult{ID: entryID,
			GroupID: domain.NewID("0198f3e0-9c25-7a1f-b73d-5e08c4a29f61"),
		},
	})
	if res.UserID != ownerID {
		t.Error("the owner id did not reach the response")
	}
	if res.UserGroup.ID != entryID {
		t.Error("the entry id the server minted did not reach the response")
	}
	if res.UserGroup.GroupID != domain.NewID("0198f3e0-9c25-7a1f-b73d-5e08c4a29f61") {
		t.Errorf("GroupID did not reach the response")
	}
}
