// Code generated by omnicore-gen. DO NOT EDIT.
//
// The add wire pair for one user_groups entry.
//
// entity:     User
// spec:       specs/omnicore-gen/user.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-01
// checksum:   sha256:c01c2fa09d4725d368c76f30305916ce8a2162b7d251ae2095d606a3191dde64
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package requests

import (
	"github.com/ClaudioSchirmer/omnicore/domain"

	fwrequests "github.com/ClaudioSchirmer/omnicore/web/requests"
	fwresponses "github.com/ClaudioSchirmer/omnicore/web/responses"

	"github.com/ClaudioSchirmer/authcore/internal/application/commands"
	webdtos "github.com/ClaudioSchirmer/authcore/internal/web/requests/dtos"
)

// AddUserGroupRequest adds one entry to an existing User.
//
// The owner comes from the path; the body is the entry, in the same shape it
// has inside the root's own body.
type AddUserGroupRequest struct {
	fwrequests.Auto
	webdtos.UserGroupRequest
}

// ToCommand hands the body to the application layer unchanged. No
// normalisation happens here: the domain is what decides a value's final form.
//
// The embedded marker opts this Request into the framework's generic
// Request→Command mapping: every field travels to the same-named Command
// field, and the pair is checked at boot. A shape that needed renaming or
// reshaping would drop the marker and write ToCommand by hand instead.
func (r AddUserGroupRequest) ToCommand() *commands.AddUserGroupCommand {
	return fwrequests.AutoFromRequest[*commands.AddUserGroupCommand](r)
}

// AddUserGroupResponse is the owner's id plus the entry as stored.
type AddUserGroupResponse struct {
	fwresponses.Auto

	UserID    domain.ID                 `json:"userId"`
	UserGroup webdtos.UserGroupResponse `json:"userGroup"`
}

// FromResult projects the application Result onto AddUserGroupResponse.
//
// The embedded marker opts this Response into the framework's generic
// Result→Response mapping: every field is read from the same-named Result
// field, and the pair is checked at boot. A shape that needed renaming or
// reshaping would drop the marker and write FromResult by hand instead.
func (AddUserGroupResponse) FromResult(r commands.AddUserGroupResult) AddUserGroupResponse {
	return fwresponses.AutoFromResult[AddUserGroupResponse](r)
}
