// Code generated by omnicore-gen. DO NOT EDIT.
//
// The wire mapper tests for add_user_role.go.
//
// entity:     User
// spec:       specs/omnicore-gen/user.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-01
// checksum:   sha256:bd9505c1d50186f453f5ded7ba1d017280a3150dfa911e6458b04f7c12966848
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package requests

import (
	"testing"

	"github.com/ClaudioSchirmer/omnicore/domain"

	"github.com/ClaudioSchirmer/authcore/internal/application/commands"

	cmddtos "github.com/ClaudioSchirmer/authcore/internal/application/commands/dtos"
	webdtos "github.com/ClaudioSchirmer/authcore/internal/web/requests/dtos"
)

// AddUserRoleRequest carries the entry into its command.
//
// The body is the same entry shape the root's own body carries, so a field
// forgotten here is saved as missing on a request that answered 201.
func TestAddUserRoleRequest_CarriesEveryField(t *testing.T) {
	r := AddUserRoleRequest{UserRoleRequest: webdtos.UserRoleRequest{
		RoleID: domain.NewID("0198f3e0-1a44-7bb2-9c31-77c0d5e1b904"),
	}}
	cmd := r.ToCommand()
	if cmd.RoleID != domain.NewID("0198f3e0-1a44-7bb2-9c31-77c0d5e1b904") {
		t.Errorf("RoleID did not reach the command")
	}
}

// The UserRole responses carry the stored entry back to the caller.
//
// The entry comes back with the id the SERVER minted, which is how the caller
// addresses it afterwards — a response mapper that drops it answers 201 with
// nothing to act on.
func TestAddUserRoleResponse_CarriesTheStoredEntry(t *testing.T) {
	ownerID := domain.NewRandomID()
	entryID := domain.NewRandomID()
	res := AddUserRoleResponse{}.FromResult(commands.AddUserRoleResult{
		UserID: ownerID,
		UserRole: cmddtos.UserRoleResult{ID: entryID,
			RoleID: domain.NewID("0198f3e0-1a44-7bb2-9c31-77c0d5e1b904"),
		},
	})
	if res.UserID != ownerID {
		t.Error("the owner id did not reach the response")
	}
	if res.UserRole.ID != entryID {
		t.Error("the entry id the server minted did not reach the response")
	}
	if res.UserRole.RoleID != domain.NewID("0198f3e0-1a44-7bb2-9c31-77c0d5e1b904") {
		t.Errorf("RoleID did not reach the response")
	}
}
