// Code generated by omnicore-gen. DO NOT EDIT.
//
// The wire mapper tests for archive_user_role.go.
//
// entity:     User
// spec:       specs/omnicore-gen/user.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-01
// checksum:   sha256:81f893c6de6f0d88b9ec4bb558f648f910e26d3894c8a061b0e76496550ec59f
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package requests

import (
	"testing"

	fwresults "github.com/ClaudioSchirmer/omnicore/application/results"
)

// ArchiveUserRoleRequest carries the addressed entry into its command.
func TestArchiveUserRoleRequest_NamesTheEntry(t *testing.T) {
	r := ArchiveUserRoleRequest{UserRoleID: "01890000-0000-7000-8000-000000000000"}
	if r.ToCommand().UserRoleID != "01890000-0000-7000-8000-000000000000" {
		t.Error("the entry id did not reach the command, so the wrong entry would be removed")
	}
}

// ArchiveUserRoleGraphQLRequest names the entry through its input.
func TestArchiveUserRoleGraphQLRequest_NamesTheEntry(t *testing.T) {
	r := ArchiveUserRoleGraphQLRequest{UserRoleID: "01890000-0000-7000-8000-000000000000"}
	if r.ToCommand().UserRoleID != "01890000-0000-7000-8000-000000000000" {
		t.Error("the entry id did not reach the command, so the wrong entry would be removed")
	}
}

// ArchiveUserRoleGraphQLResponse acknowledges, since a mutation must answer
// something.
//
// Its REST twin answers 204 with no body at all. This one is the only
// projection in the collection's wire types that is not the generic mapper,
// which is exactly why it is asserted rather than assumed.
func TestArchiveUserRoleGraphQLResponse_Acknowledges(t *testing.T) {
	if !(ArchiveUserRoleGraphQLResponse{}).FromResult(fwresults.None{}).Success {
		t.Error("a successful removal answered success: false")
	}
}
