// Code generated by omnicore-gen. DO NOT EDIT.
//
// The wire mapper tests for archive_client_allowed_cidr.go.
//
// entity:     Client
// spec:       specs/omnicore-gen/client.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-01
// checksum:   sha256:bfafc45c62cbd67bf5c5d40bf9821737e559cedc4ecfcecd34d1fcd57607d85f
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package requests

import (
	"testing"

	fwresults "github.com/ClaudioSchirmer/omnicore/application/results"
)

// ArchiveClientAllowedCIDRRequest carries the addressed entry into its
// command.
func TestArchiveClientAllowedCIDRRequest_NamesTheEntry(t *testing.T) {
	r := ArchiveClientAllowedCIDRRequest{ClientAllowedCIDRID: "01890000-0000-7000-8000-000000000000"}
	if r.ToCommand().ClientAllowedCIDRID != "01890000-0000-7000-8000-000000000000" {
		t.Error("the entry id did not reach the command, so the wrong entry would be removed")
	}
}

// ArchiveClientAllowedCIDRGraphQLRequest names the entry through its input.
func TestArchiveClientAllowedCIDRGraphQLRequest_NamesTheEntry(t *testing.T) {
	r := ArchiveClientAllowedCIDRGraphQLRequest{ClientAllowedCIDRID: "01890000-0000-7000-8000-000000000000"}
	if r.ToCommand().ClientAllowedCIDRID != "01890000-0000-7000-8000-000000000000" {
		t.Error("the entry id did not reach the command, so the wrong entry would be removed")
	}
}

// ArchiveClientAllowedCIDRGraphQLResponse acknowledges, since a mutation must
// answer something.
//
// Its REST twin answers 204 with no body at all. This one is the only
// projection in the collection's wire types that is not the generic mapper,
// which is exactly why it is asserted rather than assumed.
func TestArchiveClientAllowedCIDRGraphQLResponse_Acknowledges(t *testing.T) {
	if !(ArchiveClientAllowedCIDRGraphQLResponse{}).FromResult(fwresults.None{}).Success {
		t.Error("a successful removal answered success: false")
	}
}
