// Code generated by omnicore-gen. DO NOT EDIT.
//
// The per-entry wire types for client_roles.
//
// entity:     Client
// spec:       specs/omnicore-gen/client.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-28
// checksum:   sha256:da5857dfb6373cfb64331a1e23045442b5d603d262d819e135849c32ec78acca
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package requests

import (
	"github.com/ClaudioSchirmer/authcore/internal/application/commands"
	"github.com/ClaudioSchirmer/omnicore/domain"
	fwrequests "github.com/ClaudioSchirmer/omnicore/web/requests"
	fwresponses "github.com/ClaudioSchirmer/omnicore/web/responses"
)

// AddClientRoleRequest adds one entry to an existing Client.
//
// The owner comes from the path; the body is the entry, in the same shape it
// has inside the root's own body.
type AddClientRoleRequest struct {
	fwrequests.Auto
	ClientRoleRequest
}

// ToCommand hands the body to the application layer unchanged. No
// normalisation happens here: the domain is what decides a value's final form.
//
// The embedded marker opts this Request into the framework's generic
// Request→Command mapping: every field travels to the same-named Command
// field, and the pair is checked at boot. A shape that needed renaming or
// reshaping would drop the marker and write ToCommand by hand instead.
func (r AddClientRoleRequest) ToCommand() *commands.AddClientRoleCommand {
	return fwrequests.AutoFromRequest[*commands.AddClientRoleCommand](r)
}

// AddClientRoleResponse is the owner's id plus the entry as stored.
type AddClientRoleResponse struct {
	fwresponses.Auto

	ClientID   domain.ID          `json:"clientId"`
	ClientRole ClientRoleResponse `json:"clientRole"`
}

// FromResult projects the application Result onto AddClientRoleResponse.
//
// The embedded marker opts this Response into the framework's generic
// Result→Response mapping: every field is read from the same-named Result
// field, and the pair is checked at boot. A shape that needed renaming or
// reshaping would drop the marker and write FromResult by hand instead.
func (AddClientRoleResponse) FromResult(r commands.AddClientRoleResult) AddClientRoleResponse {
	return fwresponses.AutoFromResult[AddClientRoleResponse](r)
}

// RemoveClientRoleRequest names the entry to take out.
//
// There is no body: everything the verb needs is in the path. Nothing comes
// back either — the endpoint answers 204.
type RemoveClientRoleRequest struct {
	fwrequests.Auto

	ClientRoleID string `path:"clientRoleId"`
}

// ToCommand hands the body to the application layer unchanged. No
// normalisation happens here: the domain is what decides a value's final form.
//
// The embedded marker opts this Request into the framework's generic
// Request→Command mapping: every field travels to the same-named Command
// field, and the pair is checked at boot. A shape that needed renaming or
// reshaping would drop the marker and write ToCommand by hand instead.
func (r RemoveClientRoleRequest) ToCommand() *commands.RemoveClientRoleCommand {
	return fwrequests.AutoFromRequest[*commands.RemoveClientRoleCommand](r)
}
