// Code generated by omnicore-gen. DO NOT EDIT.
//
// The listing request and response.
//
// entity:     Tenant
// spec:       specs/omnicore-gen/tenant.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-06
// checksum:   sha256:0decb12a28c756bd228226767db3a49f69b87386da469ab53185f8d877632665
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package requests

import (
	"time"

	fwqueries "github.com/ClaudioSchirmer/omnicore/application/queries"

	fwresponses "github.com/ClaudioSchirmer/omnicore/web/responses"

	appqueries "github.com/ClaudioSchirmer/authcore/internal/application/queries"
)

// FindTenantsRequest declares the filters and read controls this listing
// serves.
//
// Every scalar is a pointer on purpose. The OpenAPI generator marks a
// non-pointer parameter as required, so one value-typed filter would make an
// optional query parameter mandatory and Swagger would refuse the call without
// it.
type FindTenantsRequest struct {
	Name            *string    `query:"name" filter:"eq,in,startswith,contains,istartswith,icontains" sort:"asc,desc" description:"Human-readable display name of the tenant organization, as operators and end users see it. Not unique — two genuinely different customers may share a name."`
	Workspace       *string    `query:"workspace" filter:"eq,in,startswith,istartswith" sort:"asc,desc" description:"Immutable handle of the tenant; reaches URLs, logs and external configuration, and is what URLs, logs and external configuration carry. Never reused, archived rows included."`
	Description     *string    `query:"description" filter:"contains,icontains" description:"What this tenant is, in the platform operators' own words."`
	Status          *string    `query:"status" filter:"eq,in" description:"Commercial lifecycle of the tenant. Orthogonal to archiving — a suspended tenant is still listed and still authenticates for billing."`
	CreatedAt       *time.Time `query:"createdAt" filter:"eq,gte,lte,gt,lt" sort:"asc,desc" description:"Stamped by the framework: when the row was inserted."`
	UpdatedAt       *time.Time `query:"updatedAt" filter:"eq,gte,lte,gt,lt" description:"Stamped by the framework: when the row was last written."`
	First           *int64     `query:"first"`
	Last            *int64     `query:"last"`
	After           *string    `query:"after"`
	Before          *string    `query:"before"`
	OrderBy         *string    `query:"orderBy"`
	Fields          *string    `query:"fields"`
	OnlyTotal       *bool      `query:"onlyTotal"`
	IncludeArchived *bool      `query:"includeArchived"`
}

func (r FindTenantsRequest) ToQuery(criteria fwqueries.ReadCriteria) *appqueries.FindTenantsByParamsQuery {
	return &appqueries.FindTenantsByParamsQuery{Criteria: criteria}
}

// FindTenantsResponse is one row of the listing.
//
// This type is the SINGLE wire authority for the read, on every surface: REST,
// GraphQL and the tabular exports all render exactly the fields declared here,
// under these json names. A field outside it reaches no wire — and ?fields=
// speaks this same vocabulary, so the JSON listing and the CSV export accept
// the same selection.
//
// Every field is a pointer with omitempty because this listing serves
// ?fields=: partial projection has to be able to leave a field out, and the
// framework refuses to build the endpoint otherwise.
type FindTenantsResponse struct {
	fwresponses.Auto

	ID          *string    `json:"id,omitempty" example:"7b3c1f10-3c7e-4a8d-9f0e-9d2a8e6d4b51"`
	Name        *string    `json:"name,omitempty" exportLabelKey:"TenantNameField" example:"Acme Comércio e Serviços Ltda"`
	Workspace   *string    `json:"workspace,omitempty" exportLabelKey:"TenantWorkspaceField" example:"acme-comercio"`
	Description *string    `json:"description,omitempty" exportLabelKey:"TenantDescriptionField" example:"Retail operations of the Acme group in Brazil."`
	Status      *string    `json:"status,omitempty" exportLabelKey:"TenantStatusField" example:"active"`
	CreatedAt   *time.Time `json:"createdAt,omitempty" exportLabelKey:"TenantCreatedAtField" example:"2026-02-01T09:00:00Z"`
	UpdatedAt   *time.Time `json:"updatedAt,omitempty" exportLabelKey:"TenantUpdatedAtField" example:"2026-02-01T09:00:00Z"`
	DeletedAt   *time.Time `json:"deletedAt,omitempty" exportLabelKey:"TenantDeletedAtField" example:"2026-02-01T09:00:00Z"`
}

// FromResult projects the application Result onto FindTenantsResponse.
//
// Read-side COMPUTATION does not belong here: it would run once per SURFACE,
// and the export would disagree with the JSON. It belongs in the query's
// FromQueryResult, which runs once per document.
//
// The embedded marker opts this Response into the framework's generic
// Result→Response mapping: every field is read from the same-named Result
// field, and the pair is checked at boot. A shape that needed renaming or
// reshaping would drop the marker and write FromResult by hand instead.
func (FindTenantsResponse) FromResult(r appqueries.FindTenantsByParamsResult) FindTenantsResponse {
	return fwresponses.AutoFromResult[FindTenantsResponse](r)
}
