// Code generated by omnicore-gen. DO NOT EDIT.
//
// The listing request and response.
//
// entity:     Role
// spec:       specs/omnicore-gen/role.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-06
// checksum:   sha256:a73880115e93d48f0c30fcb04038fb0a060e8afbb216403b746e30b7c96b9ed3
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package requests

import (
	fwqueries "github.com/ClaudioSchirmer/omnicore/application/queries"
	"github.com/ClaudioSchirmer/omnicore/domain"
	"time"

	fwresponses "github.com/ClaudioSchirmer/omnicore/web/responses"

	appqueries "github.com/ClaudioSchirmer/authcore/internal/application/queries"
	webdtos "github.com/ClaudioSchirmer/authcore/internal/web/requests/dtos"
)

// FindRolesRequest declares the filters and read controls this listing serves.
//
// Every scalar is a pointer on purpose. The OpenAPI generator marks a
// non-pointer parameter as required, so one value-typed filter would make an
// optional query parameter mandatory and Swagger would refuse the call without
// it.
type FindRolesRequest struct {
	TenantID        *domain.ID `query:"tenantID" filter:"eq,in" sort:"asc,desc" description:"The tenant that owns this role. Immutable after creation — a role never moves between tenants."`
	Key             *string    `query:"key" filter:"eq,ne,in,startswith,istartswith,contains,icontains" sort:"asc,desc" description:"Stable machine handle of the role, unique within its tenant and immutable. What an API caller and an audit line reference; never the display name."`
	Name            *string    `query:"name" filter:"eq,in,startswith,istartswith,contains,icontains" sort:"asc,desc" description:"Human-readable name of the role as operators and end users see it. Not unique — two tenants, or two roles, may share a label."`
	Description     *string    `query:"description" filter:"contains,icontains" description:"What holding this role actually lets a user do, in the tenant's own words."`
	TenantWorkspace *string    `query:"tenantWorkspace" filter:"eq,in,startswith,istartswith,contains,icontains" sort:"asc,desc" description:"The owning tenant's immutable handle — what URLs, logs and support conversations say. Read-only, filled on every load, never written through this aggregate."`
	TenantStatus    *string    `query:"tenantStatus" filter:"eq,in" sort:"asc,desc" description:"The owning tenant's commercial lifecycle — trial, active or suspended. Read-only, filled on every load, never written through this aggregate."`
	CreatedAt       *time.Time `query:"createdAt" filter:"gte,lte" sort:"asc,desc" description:"Stamped by the framework: when the row was inserted."`
	UpdatedAt       *time.Time `query:"updatedAt" filter:"gte,lte" sort:"asc,desc" description:"Stamped by the framework: when the row was last written."`
	First           *int64     `query:"first"`
	Last            *int64     `query:"last"`
	After           *string    `query:"after"`
	Before          *string    `query:"before"`
	OrderBy         *string    `query:"orderBy"`
	Fields          *string    `query:"fields"`
	OnlyTotal       *bool      `query:"onlyTotal"`
	IncludeArchived *bool      `query:"includeArchived"`
}

func (r FindRolesRequest) ToQuery(criteria fwqueries.ReadCriteria) *appqueries.FindRolesByParamsQuery {
	return &appqueries.FindRolesByParamsQuery{Criteria: criteria}
}

// FindRolesResponse is one row of the listing.
//
// This type is the SINGLE wire authority for the read, on every surface: REST,
// GraphQL and the tabular exports all render exactly the fields declared here,
// under these json names. A field outside it reaches no wire — and ?fields=
// speaks this same vocabulary, so the JSON listing and the CSV export accept
// the same selection.
//
// Every field is a pointer with omitempty because this listing serves
// ?fields=: partial projection has to be able to leave a field out, and the
// framework refuses to build the endpoint otherwise.
type FindRolesResponse struct {
	fwresponses.Auto

	ID               *string                     `json:"id,omitempty" example:"7b3c1f10-3c7e-4a8d-9f0e-9d2a8e6d4b51"`
	TenantID         *domain.ID                  `json:"tenantID,omitempty" exportLabelKey:"RoleTenantIDField" example:"0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410"`
	Key              *string                     `json:"key,omitempty" exportLabelKey:"RoleKeyField" example:"billing-manager"`
	Name             *string                     `json:"name,omitempty" exportLabelKey:"RoleNameField" example:"Billing Manager"`
	Description      *string                     `json:"description,omitempty" exportLabelKey:"RoleDescriptionField" example:"Grants read access to the tenant registry and the permission catalog, without any write verb."`
	CreatedAt        *time.Time                  `json:"createdAt,omitempty" exportLabelKey:"RoleCreatedAtField" example:"2026-02-01T09:00:00Z"`
	UpdatedAt        *time.Time                  `json:"updatedAt,omitempty" exportLabelKey:"RoleUpdatedAtField" example:"2026-02-01T09:00:00Z"`
	ArchivedAt       *time.Time                  `json:"archivedAt,omitempty" exportLabelKey:"RoleArchivedAtField" example:"2026-02-01T09:00:00Z"`
	TenantWorkspace  *string                     `json:"tenantWorkspace,omitempty" exportLabelKey:"RoleTenantWorkspaceField" example:"acme-comercio"`
	TenantStatus     *string                     `json:"tenantStatus,omitempty" exportLabelKey:"RoleTenantStatusField" example:"active"`
	TenantArchivedAt *time.Time                  `json:"tenantArchivedAt,omitempty" exportLabelKey:"RoleTenantArchivedAtField" example:"2026-01-31T12:00:00Z"`
	Permissions      []webdtos.RolePermissionRow `json:"permissions,omitempty"`
}

// FromResult projects the application Result onto FindRolesResponse.
//
// Read-side COMPUTATION does not belong here: it would run once per SURFACE,
// and the export would disagree with the JSON. It belongs in the query's
// FromQueryResult, which runs once per document.
//
// The embedded marker opts this Response into the framework's generic
// Result→Response mapping: every field is read from the same-named Result
// field, and the pair is checked at boot. A shape that needed renaming or
// reshaping would drop the marker and write FromResult by hand instead.
func (FindRolesResponse) FromResult(r appqueries.FindRolesByParamsResult) FindRolesResponse {
	return fwresponses.AutoFromResult[FindRolesResponse](r)
}
