// Code generated by omnicore-gen. DO NOT EDIT.
//
// The listing request and response.
//
// entity:     Group
// spec:       specs/omnicore-gen/group.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-24
// checksum:   sha256:da5ef28e6b41fe4ec0f0feafb114730ed7d8852bc8857756bc95f8720337fb29
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package requests

import (
	fwqueries "github.com/ClaudioSchirmer/omnicore/application/queries"
	"github.com/ClaudioSchirmer/omnicore/domain"
	"time"

	fwresponses "github.com/ClaudioSchirmer/omnicore/web/responses"

	appqueries "github.com/ClaudioSchirmer/authcore/internal/application/queries"
)

// FindGroupsRequest declares the filters and read controls this listing
// serves.
//
// Every scalar is a pointer on purpose. The OpenAPI generator marks a
// non-pointer parameter as required, so one value-typed filter would make an
// optional query parameter mandatory and Swagger would refuse the call without
// it.
type FindGroupsRequest struct {
	TenantID        *domain.ID `query:"tenantID" filter:"eq,in" sort:"asc,desc"`
	Key             *string    `query:"key" filter:"eq,ne,in,startswith,istartswith,contains,icontains" sort:"asc,desc"`
	Name            *string    `query:"name" filter:"eq,ne,in,startswith,istartswith,contains,icontains" sort:"asc,desc"`
	Description     *string    `query:"description" filter:"contains,icontains"`
	TenantWorkspace *string    `query:"tenantWorkspace" filter:"eq,in,startswith,istartswith,contains,icontains" sort:"asc,desc"`
	TenantStatus    *string    `query:"tenantStatus" filter:"eq,in" sort:"asc,desc"`
	CreatedAt       *time.Time `query:"createdAt" filter:"gte,lte" sort:"asc,desc"`
	UpdatedAt       *time.Time `query:"updatedAt" filter:"gte,lte" sort:"asc,desc"`
	First           *int64     `query:"first"`
	Last            *int64     `query:"last"`
	After           *string    `query:"after"`
	Before          *string    `query:"before"`
	OrderBy         *string    `query:"orderBy"`
	Fields          *string    `query:"fields"`
	OnlyTotal       *bool      `query:"onlyTotal"`
	IncludeArchived *bool      `query:"includeArchived"`
}

func (r FindGroupsRequest) ToQuery(criteria fwqueries.ReadCriteria) *appqueries.FindGroupsByParamsQuery {
	return &appqueries.FindGroupsByParamsQuery{Criteria: criteria}
}

// FindGroupsResponse is one row of the listing.
//
// This type is the SINGLE wire authority for the read, on every surface: REST,
// GraphQL and the tabular exports all render exactly the fields declared here,
// under these json names. A field outside it reaches no wire — and ?fields=
// speaks this same vocabulary, so the JSON listing and the CSV export accept
// the same selection.
//
// Every field is a pointer with omitempty because this listing serves
// ?fields=: partial projection has to be able to leave a field out, and the
// framework refuses to build the endpoint otherwise.
type FindGroupsResponse struct {
	fwresponses.Auto

	ID              *string        `json:"id,omitempty" example:"7b3c1f10-3c7e-4a8d-9f0e-9d2a8e6d4b51"`
	TenantID        *domain.ID     `json:"tenantID,omitempty" exportLabelKey:"GroupTenantIDField" example:"0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410"`
	Key             *string        `json:"key,omitempty" exportLabelKey:"GroupKeyField" example:"engineering"`
	Name            *string        `json:"name,omitempty" exportLabelKey:"GroupNameField" example:"Engineering"`
	Description     *string        `json:"description,omitempty" exportLabelKey:"GroupDescriptionField" example:"Everyone in the product engineering org: read access to the tenant registry and the permission catalog, plus deploy rights."`
	CreatedAt       *time.Time     `json:"createdAt,omitempty" exportLabelKey:"GroupCreatedAtField" example:"2026-02-01T09:00:00Z"`
	UpdatedAt       *time.Time     `json:"updatedAt,omitempty" exportLabelKey:"GroupUpdatedAtField" example:"2026-02-01T09:00:00Z"`
	TenantWorkspace *string        `json:"tenantWorkspace,omitempty" exportLabelKey:"GroupTenantWorkspaceField" example:"acme-comercio"`
	TenantStatus    *string        `json:"tenantStatus,omitempty" exportLabelKey:"GroupTenantStatusField" example:"active"`
	Roles           []GroupRoleRow `json:"roles,omitempty"`
}

// FromResult projects the application Result onto FindGroupsResponse.
//
// Read-side COMPUTATION does not belong here: it would run once per SURFACE,
// and the export would disagree with the JSON. It belongs in the query's
// FromQueryResult, which runs once per document.
//
// The embedded marker opts this Response into the framework's generic
// Result→Response mapping: every field is read from the same-named Result
// field, and the pair is checked at boot. A shape that needed renaming or
// reshaping would drop the marker and write FromResult by hand instead.
func (FindGroupsResponse) FromResult(r appqueries.FindGroupsByParamsResult) FindGroupsResponse {
	return fwresponses.AutoFromResult[FindGroupsResponse](r)
}
