// Code generated by omnicore-gen. DO NOT EDIT.
//
// The wire mapper tests for find_claims_by_params.go.
//
// entity:     Claim
// spec:       specs/omnicore-gen/claim.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-01
// checksum:   sha256:4d06ee5c8369154afef09fa4282fda2bee9d7eab7394dc57528ec399bc53b663
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package requests

import (
	"testing"

	fwqueries "github.com/ClaudioSchirmer/omnicore/application/queries"

	appqueries "github.com/ClaudioSchirmer/authcore/internal/application/queries"
)

// The listing request maps onto the query it stands for.
//
// Every control it carries is one the spec declared; one dropped here is a
// parameter the caller sends and the read silently ignores.
func TestFindClaimsRequestBuildsItsQuery(t *testing.T) {
	q := FindClaimsRequest{}.ToQuery(fwqueries.ReadCriteria{})
	if q == nil {
		t.Fatal("the listing request produced no query")
	}
}

// FindClaimsResponse is filled from FindClaimsByParamsResult and from nothing
// else.
//
// The mapping is name-based, so a rename on one side and not the other
// produces a field that is silently always empty rather than a compile error.
// The framework catches it at mount; this catches it here, where it is cheap.
func TestFindClaimsResponse_IsFilledFromTheResult(t *testing.T) {
	id := "7b3c1f10-3c7e-4a8d-9f0e-9d2a8e6d4b51"
	out := FindClaimsResponse{}.FromResult(appqueries.FindClaimsByParamsResult{ID: &id})
	if out.ID == nil || *out.ID != id {
		t.Fatalf("the id did not survive the mapping: %v", out.ID)
	}
}
