// Code generated by omnicore-gen. DO NOT EDIT.
//
// The listing request and response.
//
// entity:     Claim
// spec:       specs/omnicore-gen/claim.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-06
// checksum:   sha256:32eff831d5e79714c68129795453c58144d9d211e572d70dc5ecfe09594d38b4
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package requests

import (
	fwqueries "github.com/ClaudioSchirmer/omnicore/application/queries"
	"github.com/ClaudioSchirmer/omnicore/domain"
	"time"

	fwresponses "github.com/ClaudioSchirmer/omnicore/web/responses"

	appqueries "github.com/ClaudioSchirmer/authcore/internal/application/queries"
)

// FindClaimsRequest declares the filters and read controls this listing
// serves.
//
// Every scalar is a pointer on purpose. The OpenAPI generator marks a
// non-pointer parameter as required, so one value-typed filter would make an
// optional query parameter mandatory and Swagger would refuse the call without
// it.
type FindClaimsRequest struct {
	TenantID        *domain.ID `query:"tenantID" filter:"eq,in" sort:"asc,desc" description:"The tenant that owns this claim definition. Immutable after creation — a claim never moves between tenants."`
	Name            *string    `query:"name" filter:"eq,ne,in,startswith,istartswith,contains,icontains" sort:"asc,desc" description:"The exact name minted into the token, carrying the reserved x_ prefix. Unique within its tenant and immutable — every consuming service branches on this string."`
	ValueType       *string    `query:"valueType" filter:"eq,in" sort:"asc,desc" description:"What a value for this claim must parse as. The default below and every principal-level value are validated against it."`
	AppliesTo       *string    `query:"appliesTo" filter:"eq,in" sort:"asc,desc" description:"Which identity kinds may hold a value for this claim: a user, a machine client, or both."`
	DefaultValue    *string    `query:"defaultValue" filter:"eq,in,contains,icontains" description:"Level 2 of the resolution chain: the value every principal of this tenant gets when none is set on the principal itself. Null means there is no default and the claim is absent from the token."`
	Description     *string    `query:"description" filter:"contains,icontains" description:"What the value means, in the tenant's own words, for the operator filling it in."`
	TenantWorkspace *string    `query:"tenantWorkspace" filter:"eq,in,startswith,istartswith" sort:"asc,desc" description:"The owning tenant's immutable handle — what URLs, logs and support conversations say. Read-only, filled on every load, never written through this aggregate."`
	TenantStatus    *string    `query:"tenantStatus" filter:"eq,in" description:"The owning tenant's commercial lifecycle — trial, active or suspended. Read-only, filled on every load, never written through this aggregate."`
	CreatedAt       *time.Time `query:"createdAt" filter:"gte,lte" sort:"asc,desc" description:"Stamped by the framework: when the row was inserted."`
	UpdatedAt       *time.Time `query:"updatedAt" filter:"gte,lte" sort:"asc,desc" description:"Stamped by the framework: when the row was last written."`
	First           *int64     `query:"first"`
	Last            *int64     `query:"last"`
	After           *string    `query:"after"`
	Before          *string    `query:"before"`
	OrderBy         *string    `query:"orderBy"`
	Fields          *string    `query:"fields"`
	OnlyTotal       *bool      `query:"onlyTotal"`
	IncludeArchived *bool      `query:"includeArchived"`
}

func (r FindClaimsRequest) ToQuery(criteria fwqueries.ReadCriteria) *appqueries.FindClaimsByParamsQuery {
	return &appqueries.FindClaimsByParamsQuery{Criteria: criteria}
}

// FindClaimsResponse is one row of the listing.
//
// This type is the SINGLE wire authority for the read, on every surface: REST,
// GraphQL and the tabular exports all render exactly the fields declared here,
// under these json names. A field outside it reaches no wire — and ?fields=
// speaks this same vocabulary, so the JSON listing and the CSV export accept
// the same selection.
//
// Every field is a pointer with omitempty because this listing serves
// ?fields=: partial projection has to be able to leave a field out, and the
// framework refuses to build the endpoint otherwise.
type FindClaimsResponse struct {
	fwresponses.Auto

	ID               *string    `json:"id,omitempty" example:"7b3c1f10-3c7e-4a8d-9f0e-9d2a8e6d4b51"`
	TenantID         *domain.ID `json:"tenantID,omitempty" exportLabelKey:"ClaimTenantIDField" example:"0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410"`
	Name             *string    `json:"name,omitempty" exportLabelKey:"ClaimNameField" example:"x_cost_center"`
	ValueType        *string    `json:"valueType,omitempty" exportLabelKey:"ClaimValueTypeField" example:"string"`
	AppliesTo        *string    `json:"appliesTo,omitempty" exportLabelKey:"ClaimAppliesToField" example:"both"`
	DefaultValue     *string    `json:"defaultValue,omitempty" exportLabelKey:"ClaimDefaultValueField" example:"1000"`
	Description      *string    `json:"description,omitempty" exportLabelKey:"ClaimDescriptionField" example:"Internal cost center this account is billed against, as the ERP knows it."`
	CreatedAt        *time.Time `json:"createdAt,omitempty" exportLabelKey:"ClaimCreatedAtField" example:"2026-02-01T09:00:00Z"`
	UpdatedAt        *time.Time `json:"updatedAt,omitempty" exportLabelKey:"ClaimUpdatedAtField" example:"2026-02-01T09:00:00Z"`
	ArchivedAt       *time.Time `json:"archivedAt,omitempty" exportLabelKey:"ClaimArchivedAtField" example:"2026-02-01T09:00:00Z"`
	TenantWorkspace  *string    `json:"tenantWorkspace,omitempty" exportLabelKey:"ClaimTenantWorkspaceField" example:"acme-comercio"`
	TenantStatus     *string    `json:"tenantStatus,omitempty" exportLabelKey:"ClaimTenantStatusField" example:"active"`
	TenantArchivedAt *time.Time `json:"tenantArchivedAt,omitempty" exportLabelKey:"ClaimTenantArchivedAtField" example:"2026-01-31T12:00:00Z"`
}

// FromResult projects the application Result onto FindClaimsResponse.
//
// Read-side COMPUTATION does not belong here: it would run once per SURFACE,
// and the export would disagree with the JSON. It belongs in the query's
// FromQueryResult, which runs once per document.
//
// The embedded marker opts this Response into the framework's generic
// Result→Response mapping: every field is read from the same-named Result
// field, and the pair is checked at boot. A shape that needed renaming or
// reshaping would drop the marker and write FromResult by hand instead.
func (FindClaimsResponse) FromResult(r appqueries.FindClaimsByParamsResult) FindClaimsResponse {
	return fwresponses.AutoFromResult[FindClaimsResponse](r)
}
