// Code generated by omnicore-gen. DO NOT EDIT.
//
// The by-id request and response.
//
// entity:     Tenant
// spec:       specs/omnicore-gen/tenant.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-24
// checksum:   sha256:18f0460ee91475c7bfb57a7d73ff70cce296376f0d16c114798658f9d8ee3001
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package requests

import (
	"time"

	fwqueries "github.com/ClaudioSchirmer/omnicore/application/queries"

	fwresponses "github.com/ClaudioSchirmer/omnicore/web/responses"

	appqueries "github.com/ClaudioSchirmer/authcore/internal/application/queries"
)

// FindTenantByIDRequest declares the read controls this endpoint serves.
//
// The set is a contract, not a convenience: a reserved control that is not
// declared here is rejected with a typed 400 when it appears on the wire. The
// route's own :id is bound by the framework and must never be declared.
type FindTenantByIDRequest struct {
	IncludeArchived *bool `query:"includeArchived"`
}

// ToQuery is the web→application boundary: pure mapping, no ctx.
// Identity-derived overlays layer onto the criteria inside the query's
// ToCriteria(ctx), which is the only layer below the web boundary that may
// read the AppContext.
func (r FindTenantByIDRequest) ToQuery(criteria fwqueries.ReadCriteria) *appqueries.FindTenantByIDQuery {
	return &appqueries.FindTenantByIDQuery{Criteria: criteria}
}

// FindTenantByIDResponse is the projected document.
//
// It carries the WHOLE aggregate — the root's fields, the facets' fields and
// the collections. Reading one record and getting less of it than the listing
// gives for the same record is the shape nobody expects, and there is no
// second request that would fill the gap: the document was already fetched.
//
// This type is the SINGLE wire authority for the read, on every surface: REST,
// GraphQL and the tabular exports all render exactly the fields declared here,
// under these json names. A field outside it reaches no wire — and ?fields=
// speaks this same vocabulary, so the JSON listing and the CSV export accept
// the same selection.
type FindTenantByIDResponse struct {
	fwresponses.Auto

	ID          string    `json:"id" example:"7b3c1f10-3c7e-4a8d-9f0e-9d2a8e6d4b51"`
	Name        string    `json:"name" exportLabelKey:"TenantNameField" example:"Acme Comércio e Serviços Ltda"`
	Workspace   string    `json:"workspace" exportLabelKey:"TenantWorkspaceField" example:"acme-comercio"`
	Description string    `json:"description" exportLabelKey:"TenantDescriptionField" example:"Retail operations of the Acme group in Brazil."`
	Status      string    `json:"status" exportLabelKey:"TenantStatusField" example:"active"`
	CreatedAt   time.Time `json:"createdAt" exportLabelKey:"TenantCreatedAtField" example:"2026-02-01T09:00:00Z"`
	UpdatedAt   time.Time `json:"updatedAt" exportLabelKey:"TenantUpdatedAtField" example:"2026-02-01T09:00:00Z"`
}

// FromResult projects the application Result onto FindTenantByIDResponse.
//
// Read-side COMPUTATION does not belong here: it would run once per SURFACE,
// and the export would disagree with the JSON. It belongs in the query's
// FromQueryResult, which runs once per document.
//
// The embedded marker opts this Response into the framework's generic
// Result→Response mapping: every field is read from the same-named Result
// field, and the pair is checked at boot. A shape that needed renaming or
// reshaping would drop the marker and write FromResult by hand instead.
func (FindTenantByIDResponse) FromResult(r appqueries.FindTenantByIDResult) FindTenantByIDResponse {
	return fwresponses.AutoFromResult[FindTenantByIDResponse](r)
}
