// Code generated by omnicore-gen. DO NOT EDIT.
//
// The listing request and response.
//
// entity:     Permission
// spec:       specs/omnicore-gen/permission.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-20
// checksum:   sha256:5434eba7a62ab027ece1406ff730241d4ceba079fe4e47b6798569eda6f1db11
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package requests

import (
	fwqueries "github.com/ClaudioSchirmer/omnicore/application/queries"

	fwresponses "github.com/ClaudioSchirmer/omnicore/web/responses"

	appqueries "github.com/ClaudioSchirmer/authcore/internal/application/queries"
)

// FindPermissionsRequest declares the filters and read controls this listing
// serves.
//
// Every scalar is a pointer on purpose. The OpenAPI generator marks a
// non-pointer parameter as required, so one value-typed filter would make an
// optional query parameter mandatory and Swagger would refuse the call without
// it.
type FindPermissionsRequest struct {
	Resource        *string `query:"resource" filter:"eq,ne,in,contains,startswith" sort:"asc,desc"`
	Action          *string `query:"action" filter:"eq,ne,in,contains" sort:"asc,desc"`
	Description     *string `query:"description" filter:"contains" sort:"asc,desc"`
	First           *int64  `query:"first"`
	Last            *int64  `query:"last"`
	After           *string `query:"after"`
	Before          *string `query:"before"`
	OrderBy         *string `query:"orderBy"`
	Fields          *string `query:"fields"`
	OnlyTotal       *bool   `query:"onlyTotal"`
	IncludeArchived *bool   `query:"includeArchived"`
}

func (r FindPermissionsRequest) ToQuery(criteria fwqueries.ReadCriteria) *appqueries.FindPermissionsByParamsQuery {
	return &appqueries.FindPermissionsByParamsQuery{Criteria: criteria}
}

// FindPermissionsResponse is one row of the listing.
//
// This type is the SINGLE wire authority for the read, on every surface: REST,
// GraphQL and the tabular exports all render exactly the fields declared here,
// under these json names. A field outside it reaches no wire — and ?fields=
// speaks this same vocabulary, so the JSON listing and the CSV export accept
// the same selection.
//
// Every field is a pointer with omitempty because this listing serves
// ?fields=: partial projection has to be able to leave a field out, and the
// framework refuses to build the endpoint otherwise.
type FindPermissionsResponse struct {
	fwresponses.Auto

	ID          *string `json:"id,omitempty" example:"7b3c1f10-3c7e-4a8d-9f0e-9d2a8e6d4b51"`
	Description *string `json:"description,omitempty" exportLabelKey:"PermissionDescriptionField" example:"Read tenants: list the tenant registry and fetch a tenant by id."`
	// The permission as a JWT claim carries it and RequirePermission
	// compares it — resource:action, rendered from the two stored columns.
	Permission *string `json:"permission,omitempty" exportLabelKey:"PermissionPermissionField" computed:"Resource,Action" example:"tenant:read"`
}

// FromResult projects the application Result onto FindPermissionsResponse.
//
// Read-side COMPUTATION does not belong here: it would run once per SURFACE,
// and the export would disagree with the JSON. It belongs in the query's
// FromQueryResult, which runs once per document.
//
// The embedded marker opts this Response into the framework's generic
// Result→Response mapping: every field is read from the same-named Result
// field, and the pair is checked at boot. A shape that needed renaming or
// reshaping would drop the marker and write FromResult by hand instead.
func (FindPermissionsResponse) FromResult(r appqueries.FindPermissionsByParamsResult) FindPermissionsResponse {
	return fwresponses.AutoFromResult[FindPermissionsResponse](r)
}
