// Code generated by omnicore-gen. DO NOT EDIT.
//
// The per-entry wire types for group_roles.
//
// entity:     Group
// spec:       specs/omnicore-gen/group.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-28
// checksum:   sha256:373889a48b4280cde239798f94455a218a85fef32e7f7426e491424d6edfbf4c
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package requests

import (
	"github.com/ClaudioSchirmer/authcore/internal/application/commands"
	fwresults "github.com/ClaudioSchirmer/omnicore/application/results"
	"github.com/ClaudioSchirmer/omnicore/domain"
	fwrequests "github.com/ClaudioSchirmer/omnicore/web/requests"
	fwresponses "github.com/ClaudioSchirmer/omnicore/web/responses"
)

// AddGroupRoleRequest adds one entry to an existing Group.
//
// The owner comes from the path; the body is the entry, in the same shape it
// has inside the root's own body.
type AddGroupRoleRequest struct {
	fwrequests.Auto
	GroupRoleRequest
}

// ToCommand hands the body to the application layer unchanged. No
// normalisation happens here: the domain is what decides a value's final form.
//
// The embedded marker opts this Request into the framework's generic
// Request→Command mapping: every field travels to the same-named Command
// field, and the pair is checked at boot. A shape that needed renaming or
// reshaping would drop the marker and write ToCommand by hand instead.
func (r AddGroupRoleRequest) ToCommand() *commands.AddGroupRoleCommand {
	return fwrequests.AutoFromRequest[*commands.AddGroupRoleCommand](r)
}

// AddGroupRoleResponse is the owner's id plus the entry as stored.
type AddGroupRoleResponse struct {
	fwresponses.Auto

	GroupID   domain.ID         `json:"groupId"`
	GroupRole GroupRoleResponse `json:"groupRole"`
}

// FromResult projects the application Result onto AddGroupRoleResponse.
//
// The embedded marker opts this Response into the framework's generic
// Result→Response mapping: every field is read from the same-named Result
// field, and the pair is checked at boot. A shape that needed renaming or
// reshaping would drop the marker and write FromResult by hand instead.
func (AddGroupRoleResponse) FromResult(r commands.AddGroupRoleResult) AddGroupRoleResponse {
	return fwresponses.AutoFromResult[AddGroupRoleResponse](r)
}

// RemoveGroupRoleRequest names the entry to take out.
//
// There is no body: everything the verb needs is in the path. Nothing comes
// back either — the endpoint answers 204.
type RemoveGroupRoleRequest struct {
	fwrequests.Auto

	GroupRoleID string `path:"groupRoleId"`
}

// ToCommand hands the body to the application layer unchanged. No
// normalisation happens here: the domain is what decides a value's final form.
//
// The embedded marker opts this Request into the framework's generic
// Request→Command mapping: every field travels to the same-named Command
// field, and the pair is checked at boot. A shape that needed renaming or
// reshaping would drop the marker and write ToCommand by hand instead.
func (r RemoveGroupRoleRequest) ToCommand() *commands.RemoveGroupRoleCommand {
	return fwrequests.AutoFromRequest[*commands.RemoveGroupRoleCommand](r)
}

// RemoveGroupRoleGraphQLRequest names the entry to take out.
//
// The entry id is an input field rather than a path segment: GraphQL has no
// path, and the framework's decoder skips a path-tagged field instead of
// inventing a value for it.
type RemoveGroupRoleGraphQLRequest struct {
	fwrequests.Auto

	GroupRoleID string `json:"groupRoleId"`
}

// ToCommand hands the body to the application layer unchanged. No
// normalisation happens here: the domain is what decides a value's final form.
//
// The embedded marker opts this Request into the framework's generic
// Request→Command mapping: every field travels to the same-named Command
// field, and the pair is checked at boot. A shape that needed renaming or
// reshaping would drop the marker and write ToCommand by hand instead.
func (r RemoveGroupRoleGraphQLRequest) ToCommand() *commands.RemoveGroupRoleCommand {
	return fwrequests.AutoFromRequest[*commands.RemoveGroupRoleCommand](r)
}

// RemoveGroupRoleGraphQLResponse acknowledges the removal, and says nothing
// else.
//
// The REST verb answers 204 with no body. A GraphQL field cannot: it must
// resolve to a type, and a payload with no fields is not publishable. So the
// payload is a single true — the owner id is what the caller passed in, and
// the entry is gone by definition.
//
// No generic mapper here, and it is not an oversight: the command projects the
// framework's None, so there is no Result field for a mapped one to read.
type RemoveGroupRoleGraphQLResponse struct {
	Success bool `json:"success"`
}

// FromResult answers true: the pipeline only projects a result it succeeded
// with.
func (RemoveGroupRoleGraphQLResponse) FromResult(fwresults.None) RemoveGroupRoleGraphQLResponse {
	return RemoveGroupRoleGraphQLResponse{Success: true}
}
