// Code generated by omnicore-gen. DO NOT EDIT.
//
// The wire types for 1 child collection(s).
//
// entity:     Group
// spec:       specs/omnicore-gen/group.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-24
// checksum:   sha256:12df2f49a3a6bd9986780517d99269b71e2aad6cead71e6f6c6321d668f91579
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package requests

import "github.com/ClaudioSchirmer/omnicore/domain"

// GroupRoleRow is one entry of the roles collection as a read returns it.
type GroupRoleRow struct {
	ID       *string    `json:"id,omitempty"`
	RoleID   *domain.ID `json:"roleID,omitempty" exportLabelKey:"GroupRoleRoleIDField" example:"0198f3e0-9c25-7a1f-b73d-5e08c4a29f61"`
	RoleKey  *string    `json:"roleKey,omitempty" exportLabelKey:"GroupRoleRoleKeyField" example:"billing-manager"`
	RoleName *string    `json:"roleName,omitempty" exportLabelKey:"GroupRoleRoleNameField" example:"Billing Manager"`
}

// GroupRoleRequest is one entry sent in the roles collection.
//
// It carries no id: the server mints one.
//
// It declares no mapper of its own. This type is never the top of a request
// — it is reached as an element of the root's collection or through the
// per-entry verbs' embed — and the generic Request→Command mapping
// recurses into it by field name, so the entry travels without a seat here.
// The marker rides the type at the TOP of each walk.
type GroupRoleRequest struct {
	RoleID domain.ID `json:"roleID" example:"0198f3e0-9c25-7a1f-b73d-5e08c4a29f61"`
}

// GroupRoleResponse is one entry as stored, with the id it was given.
type GroupRoleResponse struct {
	ID     domain.ID `json:"id"`
	RoleID domain.ID `json:"roleID" example:"0198f3e0-9c25-7a1f-b73d-5e08c4a29f61"`
}
