// Code generated by omnicore-gen. DO NOT EDIT.
//
// The insert request and response.
//
// entity:     Role
// spec:       specs/omnicore-gen/role.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-28
// checksum:   sha256:f68e2bae018dc0cb251c00e29a3682525940d45795f5fb778c8bc5c7fb1075b8
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package requests

import (
	"github.com/ClaudioSchirmer/authcore/internal/application/commands"
	"github.com/ClaudioSchirmer/omnicore/domain"
	fwrequests "github.com/ClaudioSchirmer/omnicore/web/requests"
	fwresponses "github.com/ClaudioSchirmer/omnicore/web/responses"
)

// InsertRoleRequest is the body of Create a role.
type InsertRoleRequest struct {
	fwrequests.Auto

	Key         string `json:"key" example:"billing-manager"`
	Name        string `json:"name" example:"Billing Manager"`
	Description string `json:"description" example:"Grants read access to the tenant registry and the permission catalog, without any write verb."`
	// Optional, and server-assigned for almost everyone: leave it out and
	// the value is read from the caller's own identity. It is here for a
	// super-admin (*:*), who crosses the row scope and has to be able to
	// say which one a NEW record belongs to. A value from anyone else is
	// not ignored — it reaches the aggregate, where the row-scope guard
	// refuses it exactly as it refuses a write into a record that is not
	// the caller's.
	TenantID    *domain.ID              `json:"tenantID,omitempty" example:"0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410"`
	Permissions []RolePermissionRequest `json:"permissions"`
}

// ToCommand hands the body to the application layer unchanged. No
// normalisation happens here: the domain is what decides a value's final form.
//
// The embedded marker opts this Request into the framework's generic
// Request→Command mapping: every field travels to the same-named Command
// field, and the pair is checked at boot. A shape that needed renaming or
// reshaping would drop the marker and write ToCommand by hand instead.
func (r InsertRoleRequest) ToCommand() *commands.InsertRoleCommand {
	return fwrequests.AutoFromRequest[*commands.InsertRoleCommand](r)
}

// InsertRoleResponse is what Create a role returns.
type InsertRoleResponse struct {
	fwresponses.Auto

	ID          domain.ID                `json:"id" example:"7b3c1f10-3c7e-4a8d-9f0e-9d2a8e6d4b51"`
	TenantID    domain.ID                `json:"tenantID" example:"0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410"`
	Key         string                   `json:"key" example:"billing-manager"`
	Name        string                   `json:"name" example:"Billing Manager"`
	Description string                   `json:"description" example:"Grants read access to the tenant registry and the permission catalog, without any write verb."`
	Permissions []RolePermissionResponse `json:"permissions"`
}

// FromResult projects the application Result onto InsertRoleResponse.
//
// It reads the entity as STORED, never an echo of the request: the domain may
// have normalised or defaulted a value, and echoing the input back would hide
// that from the caller.
//
// The embedded marker opts this Response into the framework's generic
// Result→Response mapping: every field is read from the same-named Result
// field, and the pair is checked at boot. A shape that needed renaming or
// reshaping would drop the marker and write FromResult by hand instead.
func (InsertRoleResponse) FromResult(r commands.InsertRoleResult) InsertRoleResponse {
	return fwresponses.AutoFromResult[InsertRoleResponse](r)
}
