// Code generated by omnicore-gen. DO NOT EDIT.
//
// The wire mapper tests for insert_tenant.go.
//
// entity:     Tenant
// spec:       specs/omnicore-gen/tenant.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-01
// checksum:   sha256:9361fbae176a9d6694e6b3c4b6a980a8789b294dd1caf99bd5b2f6f69a45bcfd
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package requests

import (
	"testing"

	"github.com/ClaudioSchirmer/authcore/internal/application/commands"
)

// InsertTenantRequest must carry every field into the command.
//
// A field dropped here is invisible: the request parses, the write succeeds,
// and the value the caller sent is not in the row.
func TestInsertTenantRequest_CarriesEveryField(t *testing.T) {
	r := InsertTenantRequest{
		Name:        "Acme Comércio e Serviços Ltda",
		Workspace:   "acme-comercio",
		Description: "Retail operations of the Acme group in Brazil.",
		Status:      "active",
	}
	cmd := r.ToCommand()
	if cmd == nil {
		t.Fatal("the mapper produced no command")
	}
	if cmd.Name != r.Name {
		t.Errorf("Name did not reach the command")
	}
	if cmd.Workspace != r.Workspace {
		t.Errorf("Workspace did not reach the command")
	}
	if cmd.Description != r.Description {
		t.Errorf("Description did not reach the command")
	}
	if cmd.Status != r.Status {
		t.Errorf("Status did not reach the command")
	}
}

// InsertTenantResponse must carry the result back out.
//
// The response is the caller's only view of what was written, so a field lost
// here reads as a field that was never saved.
func TestInsertTenantResponse_CarriesTheResult(t *testing.T) {
	var in commands.InsertTenantResult
	_ = InsertTenantResponse{}.FromResult(in)
}
