// Code generated by omnicore-gen. DO NOT EDIT.
//
// The insert request and response.
//
// entity:     Client
// spec:       specs/omnicore-gen/client.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-29
// checksum:   sha256:de5f2ce9a46ec74202f70ba830b5b40c506dc35df1d341d3cb66964323d05a65
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package requests

import (
	"github.com/ClaudioSchirmer/authcore/internal/application/commands"
	"github.com/ClaudioSchirmer/omnicore/domain"
	fwrequests "github.com/ClaudioSchirmer/omnicore/web/requests"
	fwresponses "github.com/ClaudioSchirmer/omnicore/web/responses"
	"time"
)

// InsertClientRequest is the body of Create a client.
type InsertClientRequest struct {
	fwrequests.Auto

	Name        string `json:"name" example:"Billing integration"`
	Description string `json:"description" example:"Posts invoices from the billing system into the ledger."`
	Status      string `json:"status" example:"active"`
	// Optional, and server-assigned for almost everyone: leave it out and
	// the value is read from the caller's own identity. It is here for a
	// super-admin (*:*), who crosses the row scope and has to be able to
	// say which one a NEW record belongs to. A value from anyone else is
	// not ignored — it reaches the aggregate, where the row-scope guard
	// refuses it exactly as it refuses a write into a record that is not
	// the caller's.
	TenantID     *domain.ID                 `json:"tenantID,omitempty" example:"0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410"`
	Roles        []ClientRoleRequest        `json:"roles"`
	AllowedCIDRs []ClientAllowedCIDRRequest `json:"allowedCIDRs"`
	Claims       []ClientClaimRequest       `json:"claims"`
}

// ToCommand hands the body to the application layer unchanged. No
// normalisation happens here: the domain is what decides a value's final form.
//
// The embedded marker opts this Request into the framework's generic
// Request→Command mapping: every field travels to the same-named Command
// field, and the pair is checked at boot. A shape that needed renaming or
// reshaping would drop the marker and write ToCommand by hand instead.
func (r InsertClientRequest) ToCommand() *commands.InsertClientCommand {
	return fwrequests.AutoFromRequest[*commands.InsertClientCommand](r)
}

// InsertClientResponse is what Create a client returns.
type InsertClientResponse struct {
	fwresponses.Auto

	ID                      domain.ID                   `json:"id" example:"7b3c1f10-3c7e-4a8d-9f0e-9d2a8e6d4b51"`
	TenantID                domain.ID                   `json:"tenantID" example:"0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410"`
	Name                    string                      `json:"name" example:"Billing integration"`
	Description             string                      `json:"description" example:"Posts invoices from the billing system into the ledger."`
	SecretChangedAt         time.Time                   `json:"secretChangedAt" example:"2026-08-26T14:03:11Z"`
	PreviousSecretExpiresAt *time.Time                  `json:"previousSecretExpiresAt,omitempty" example:"2026-08-27T14:03:11Z"`
	Status                  string                      `json:"status" example:"active"`
	Secret                  string                      `json:"secret" example:"acs_8xQvR2mK9dLpN4wZ7tYcB1hJ6sF3gA5eU0iO8rTvXyM"`
	Roles                   []ClientRoleResponse        `json:"roles"`
	AllowedCIDRs            []ClientAllowedCIDRResponse `json:"allowedCIDRs"`
	Claims                  []ClientClaimResponse       `json:"claims"`
}

// FromResult projects the application Result onto InsertClientResponse.
//
// It reads the entity as STORED, never an echo of the request: the domain may
// have normalised or defaulted a value, and echoing the input back would hide
// that from the caller.
//
// The embedded marker opts this Response into the framework's generic
// Result→Response mapping: every field is read from the same-named Result
// field, and the pair is checked at boot. A shape that needed renaming or
// reshaping would drop the marker and write FromResult by hand instead.
func (InsertClientResponse) FromResult(r commands.InsertClientResult) InsertClientResponse {
	return fwresponses.AutoFromResult[InsertClientResponse](r)
}
