// Code generated by omnicore-gen. DO NOT EDIT.
//
// The wire mapper tests for insert_role.go.
//
// entity:     Role
// spec:       specs/omnicore-gen/role.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-01
// checksum:   sha256:0e8f7bc347f9342df52ff795e8e4617fbabdc7f2c5b1897810edd2ea0e3fdac9
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package requests

import (
	"testing"

	"github.com/ClaudioSchirmer/omnicore/domain"

	"github.com/ClaudioSchirmer/authcore/internal/application/commands"

	webdtos "github.com/ClaudioSchirmer/authcore/internal/web/requests/dtos"
)

// InsertRoleRequest must carry every field into the command.
//
// A field dropped here is invisible: the request parses, the write succeeds,
// and the value the caller sent is not in the row.
func TestInsertRoleRequest_CarriesEveryField(t *testing.T) {
	r := InsertRoleRequest{
		Key:         "billing-manager",
		Name:        "Billing Manager",
		Description: "Grants read access to the tenant registry and the permission catalog, without any write verb.",
		TenantID:    func() *domain.ID { v := domain.ID(domain.NewID("0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410")); return &v }(),
	}
	r.Permissions = []webdtos.RolePermissionRequest{{
		PermissionID: domain.NewID("0198f3d4-1a77-7b52-8e04-2c9f5a13d6b8"),
	}}
	cmd := r.ToCommand()
	if cmd == nil {
		t.Fatal("the mapper produced no command")
	}
	if len(cmd.Permissions) != 1 {
		t.Errorf("the RolePermission collection did not reach the command")
	}
	if cmd.Key != r.Key {
		t.Errorf("Key did not reach the command")
	}
	if cmd.Name != r.Name {
		t.Errorf("Name did not reach the command")
	}
	if cmd.Description != r.Description {
		t.Errorf("Description did not reach the command")
	}
}

// InsertRoleResponse must carry the result back out.
//
// The response is the caller's only view of what was written, so a field lost
// here reads as a field that was never saved.
func TestInsertRoleResponse_CarriesTheResult(t *testing.T) {
	var in commands.InsertRoleResult
	_ = InsertRoleResponse{}.FromResult(in)
}
