// Code generated by omnicore-gen. DO NOT EDIT.
//
// The wire mapper tests for patch_permission.go.
//
// entity:     Permission
// spec:       specs/omnicore-gen/permission.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-01
// checksum:   sha256:1e7f6584b06e19e9c4def83771b3425dfc28db9b7b0c80a69a90fc672ff8c641
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package requests

import (
	"testing"

	"github.com/ClaudioSchirmer/authcore/internal/application/commands"
)

// PatchPermissionRequest must carry every field into the command.
//
// A field dropped here is invisible: the request parses, the write succeeds,
// and the value the caller sent is not in the row.
func TestPatchPermissionRequest_CarriesEveryField(t *testing.T) {
	r := PatchPermissionRequest{
		Description: func() *string {
			v := string("Read tenants: list the tenant registry and fetch a tenant by id.")
			return &v
		}(),
	}
	cmd := r.ToCommand()
	if cmd == nil {
		t.Fatal("the mapper produced no command")
	}
}

// PatchPermissionResponse must carry the result back out.
//
// The response is the caller's only view of what was written, so a field lost
// here reads as a field that was never saved.
func TestPatchPermissionResponse_CarriesTheResult(t *testing.T) {
	var in commands.PatchPermissionResult
	_ = PatchPermissionResponse{}.FromResult(in)
}
