// Code generated by omnicore-gen. DO NOT EDIT.
//
// The patch request and response.
//
// entity:     Role
// spec:       specs/omnicore-gen/role.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-29
// checksum:   sha256:0253000c22e03f342ec2472795ced76a0e6320a42bdaccf161d0582bad363489
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package requests

import (
	"github.com/ClaudioSchirmer/authcore/internal/application/commands"
	"github.com/ClaudioSchirmer/omnicore/domain"
	fwrequests "github.com/ClaudioSchirmer/omnicore/web/requests"
	fwresponses "github.com/ClaudioSchirmer/omnicore/web/responses"
)

// PatchRoleRequest is the body of Update a role (partial).
//
// Every field is optional: omitting one leaves the stored value untouched.
type PatchRoleRequest struct {
	fwrequests.Auto

	Key         *string `json:"key,omitempty" example:"billing-manager"`
	Name        *string `json:"name,omitempty" example:"Billing Manager"`
	Description *string `json:"description,omitempty" example:"Grants read access to the tenant registry and the permission catalog, without any write verb."`
}

// ToCommand hands the body to the application layer unchanged. No
// normalisation happens here: the domain is what decides a value's final form.
//
// The embedded marker opts this Request into the framework's generic
// Request→Command mapping: every field travels to the same-named Command
// field, and the pair is checked at boot. A shape that needed renaming or
// reshaping would drop the marker and write ToCommand by hand instead.
func (r PatchRoleRequest) ToCommand() *commands.PatchRoleCommand {
	return fwrequests.AutoFromRequest[*commands.PatchRoleCommand](r)
}

// PatchRoleResponse is what Update a role (partial) returns.
type PatchRoleResponse struct {
	fwresponses.Auto

	ID          domain.ID                `json:"id" example:"7b3c1f10-3c7e-4a8d-9f0e-9d2a8e6d4b51"`
	TenantID    domain.ID                `json:"tenantID" example:"0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410"`
	Key         string                   `json:"key" example:"billing-manager"`
	Name        string                   `json:"name" example:"Billing Manager"`
	Description string                   `json:"description" example:"Grants read access to the tenant registry and the permission catalog, without any write verb."`
	Permissions []RolePermissionResponse `json:"permissions"`
}

// FromResult projects the application Result onto PatchRoleResponse.
//
// It reads the entity as STORED, never an echo of the request: the domain may
// have normalised or defaulted a value, and echoing the input back would hide
// that from the caller.
//
// The embedded marker opts this Response into the framework's generic
// Result→Response mapping: every field is read from the same-named Result
// field, and the pair is checked at boot. A shape that needed renaming or
// reshaping would drop the marker and write FromResult by hand instead.
func (PatchRoleResponse) FromResult(r commands.PatchRoleResult) PatchRoleResponse {
	return fwresponses.AutoFromResult[PatchRoleResponse](r)
}
