// Code generated by omnicore-gen. DO NOT EDIT.
//
// The patch request and response.
//
// entity:     Permission
// spec:       specs/omnicore-gen/permission.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-24
// checksum:   sha256:dd841bdb77b939734333531628fe5ded10633d581aa5df21ef3182a465e1e80a
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package requests

import (
	"github.com/ClaudioSchirmer/authcore/internal/application/commands"
	"github.com/ClaudioSchirmer/omnicore/domain"
	fwrequests "github.com/ClaudioSchirmer/omnicore/web/requests"
	fwresponses "github.com/ClaudioSchirmer/omnicore/web/responses"
)

// PatchPermissionRequest is the body of Update a permission (partial).
//
// Every field is optional: omitting one leaves the stored value untouched.
type PatchPermissionRequest struct {
	fwrequests.Auto

	Description *string `json:"description,omitempty" example:"Read tenants: list the tenant registry and fetch a tenant by id."`
}

// ToCommand hands the body to the application layer unchanged. No
// normalisation happens here: the domain is what decides a value's final form.
//
// The embedded marker opts this Request into the framework's generic
// Request→Command mapping: every field travels to the same-named Command
// field, and the pair is checked at boot. A shape that needed renaming or
// reshaping would drop the marker and write ToCommand by hand instead.
func (r PatchPermissionRequest) ToCommand() *commands.PatchPermissionCommand {
	return fwrequests.AutoFromRequest[*commands.PatchPermissionCommand](r)
}

// PatchPermissionResponse is what Update a permission (partial) returns.
type PatchPermissionResponse struct {
	fwresponses.Auto

	ID          domain.ID `json:"id" example:"7b3c1f10-3c7e-4a8d-9f0e-9d2a8e6d4b51"`
	Description string    `json:"description" example:"Read tenants: list the tenant registry and fetch a tenant by id."`
	Permission  string    `json:"permission" computed:"Resource,Action" example:"tenant:read"`
}

// FromResult projects the application Result onto PatchPermissionResponse.
//
// It reads the entity as STORED, never an echo of the request: the domain may
// have normalised or defaulted a value, and echoing the input back would hide
// that from the caller.
//
// The embedded marker opts this Response into the framework's generic
// Result→Response mapping: every field is read from the same-named Result
// field, and the pair is checked at boot. A shape that needed renaming or
// reshaping would drop the marker and write FromResult by hand instead.
func (PatchPermissionResponse) FromResult(r commands.PatchPermissionResult) PatchPermissionResponse {
	return fwresponses.AutoFromResult[PatchPermissionResponse](r)
}
