// Code generated by omnicore-gen. DO NOT EDIT.
//
// The per-entry wire types for user_groups.
//
// entity:     User
// spec:       specs/omnicore-gen/user.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-28
// checksum:   sha256:4d007f72da28af3dc4a2169abbc47f101e6f2e14b6f89c72838556c294c6cf04
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package requests

import (
	"github.com/ClaudioSchirmer/authcore/internal/application/commands"
	fwresults "github.com/ClaudioSchirmer/omnicore/application/results"
	"github.com/ClaudioSchirmer/omnicore/domain"
	fwrequests "github.com/ClaudioSchirmer/omnicore/web/requests"
	fwresponses "github.com/ClaudioSchirmer/omnicore/web/responses"
)

// AddUserGroupRequest adds one entry to an existing User.
//
// The owner comes from the path; the body is the entry, in the same shape it
// has inside the root's own body.
type AddUserGroupRequest struct {
	fwrequests.Auto
	UserGroupRequest
}

// ToCommand hands the body to the application layer unchanged. No
// normalisation happens here: the domain is what decides a value's final form.
//
// The embedded marker opts this Request into the framework's generic
// Request→Command mapping: every field travels to the same-named Command
// field, and the pair is checked at boot. A shape that needed renaming or
// reshaping would drop the marker and write ToCommand by hand instead.
func (r AddUserGroupRequest) ToCommand() *commands.AddUserGroupCommand {
	return fwrequests.AutoFromRequest[*commands.AddUserGroupCommand](r)
}

// AddUserGroupResponse is the owner's id plus the entry as stored.
type AddUserGroupResponse struct {
	fwresponses.Auto

	UserID    domain.ID         `json:"userId"`
	UserGroup UserGroupResponse `json:"userGroup"`
}

// FromResult projects the application Result onto AddUserGroupResponse.
//
// The embedded marker opts this Response into the framework's generic
// Result→Response mapping: every field is read from the same-named Result
// field, and the pair is checked at boot. A shape that needed renaming or
// reshaping would drop the marker and write FromResult by hand instead.
func (AddUserGroupResponse) FromResult(r commands.AddUserGroupResult) AddUserGroupResponse {
	return fwresponses.AutoFromResult[AddUserGroupResponse](r)
}

// RemoveUserGroupRequest names the entry to take out.
//
// There is no body: everything the verb needs is in the path. Nothing comes
// back either — the endpoint answers 204.
type RemoveUserGroupRequest struct {
	fwrequests.Auto

	UserGroupID string `path:"userGroupId"`
}

// ToCommand hands the body to the application layer unchanged. No
// normalisation happens here: the domain is what decides a value's final form.
//
// The embedded marker opts this Request into the framework's generic
// Request→Command mapping: every field travels to the same-named Command
// field, and the pair is checked at boot. A shape that needed renaming or
// reshaping would drop the marker and write ToCommand by hand instead.
func (r RemoveUserGroupRequest) ToCommand() *commands.RemoveUserGroupCommand {
	return fwrequests.AutoFromRequest[*commands.RemoveUserGroupCommand](r)
}

// RemoveUserGroupGraphQLRequest names the entry to take out.
//
// The entry id is an input field rather than a path segment: GraphQL has no
// path, and the framework's decoder skips a path-tagged field instead of
// inventing a value for it.
type RemoveUserGroupGraphQLRequest struct {
	fwrequests.Auto

	UserGroupID string `json:"userGroupId"`
}

// ToCommand hands the body to the application layer unchanged. No
// normalisation happens here: the domain is what decides a value's final form.
//
// The embedded marker opts this Request into the framework's generic
// Request→Command mapping: every field travels to the same-named Command
// field, and the pair is checked at boot. A shape that needed renaming or
// reshaping would drop the marker and write ToCommand by hand instead.
func (r RemoveUserGroupGraphQLRequest) ToCommand() *commands.RemoveUserGroupCommand {
	return fwrequests.AutoFromRequest[*commands.RemoveUserGroupCommand](r)
}

// RemoveUserGroupGraphQLResponse acknowledges the removal, and says nothing
// else.
//
// The REST verb answers 204 with no body. A GraphQL field cannot: it must
// resolve to a type, and a payload with no fields is not publishable. So the
// payload is a single true — the owner id is what the caller passed in, and
// the entry is gone by definition.
//
// No generic mapper here, and it is not an oversight: the command projects the
// framework's None, so there is no Result field for a mapped one to read.
type RemoveUserGroupGraphQLResponse struct {
	Success bool `json:"success"`
}

// FromResult answers true: the pipeline only projects a result it succeeded
// with.
func (RemoveUserGroupGraphQLResponse) FromResult(fwresults.None) RemoveUserGroupGraphQLResponse {
	return RemoveUserGroupGraphQLResponse{Success: true}
}
