// Code generated by omnicore-gen. DO NOT EDIT.
//
// The per-entry wire types for user_groups.
//
// entity:     User
// spec:       specs/omnicore-gen/user.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-29
// checksum:   sha256:32ae3dd0732a08bef5a4226a857e235d2a0d72556877f11a30d6dbd0e834d1b1
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package requests

import (
	"github.com/ClaudioSchirmer/omnicore/domain"

	"github.com/ClaudioSchirmer/authcore/internal/application/commands"
	fwresults "github.com/ClaudioSchirmer/omnicore/application/results"
	fwrequests "github.com/ClaudioSchirmer/omnicore/web/requests"
	fwresponses "github.com/ClaudioSchirmer/omnicore/web/responses"
)

// AddUserGroupRequest adds one entry to an existing User.
//
// The owner comes from the path; the body is the entry, in the same shape it
// has inside the root's own body.
type AddUserGroupRequest struct {
	fwrequests.Auto
	UserGroupRequest
}

// ToCommand hands the body to the application layer unchanged. No
// normalisation happens here: the domain is what decides a value's final form.
//
// The embedded marker opts this Request into the framework's generic
// Request→Command mapping: every field travels to the same-named Command
// field, and the pair is checked at boot. A shape that needed renaming or
// reshaping would drop the marker and write ToCommand by hand instead.
func (r AddUserGroupRequest) ToCommand() *commands.AddUserGroupCommand {
	return fwrequests.AutoFromRequest[*commands.AddUserGroupCommand](r)
}

// AddUserGroupResponse is the owner's id plus the entry as stored.
type AddUserGroupResponse struct {
	fwresponses.Auto

	UserID    domain.ID         `json:"userId"`
	UserGroup UserGroupResponse `json:"userGroup"`
}

// FromResult projects the application Result onto AddUserGroupResponse.
//
// The embedded marker opts this Response into the framework's generic
// Result→Response mapping: every field is read from the same-named Result
// field, and the pair is checked at boot. A shape that needed renaming or
// reshaping would drop the marker and write FromResult by hand instead.
func (AddUserGroupResponse) FromResult(r commands.AddUserGroupResult) AddUserGroupResponse {
	return fwresponses.AutoFromResult[AddUserGroupResponse](r)
}

// RemoveUserGroupRequest names the entry to take out.
//
// There is no body: everything the verb needs is in the path. Nothing comes
// back either — the endpoint answers 204.
type RemoveUserGroupRequest struct {
	fwrequests.Auto

	UserGroupID string `path:"userGroupId"`
}

// ToCommand hands the body to the application layer unchanged. No
// normalisation happens here: the domain is what decides a value's final form.
//
// The embedded marker opts this Request into the framework's generic
// Request→Command mapping: every field travels to the same-named Command
// field, and the pair is checked at boot. A shape that needed renaming or
// reshaping would drop the marker and write ToCommand by hand instead.
func (r RemoveUserGroupRequest) ToCommand() *commands.RemoveUserGroupCommand {
	return fwrequests.AutoFromRequest[*commands.RemoveUserGroupCommand](r)
}

// RemoveUserGroupGraphQLRequest names the entry to take out.
//
// The entry id is an input field rather than a path segment: GraphQL has no
// path, and the framework's decoder skips a path-tagged field instead of
// inventing a value for it.
type RemoveUserGroupGraphQLRequest struct {
	fwrequests.Auto

	UserGroupID string `json:"userGroupId"`
}

// ToCommand hands the body to the application layer unchanged. No
// normalisation happens here: the domain is what decides a value's final form.
//
// The embedded marker opts this Request into the framework's generic
// Request→Command mapping: every field travels to the same-named Command
// field, and the pair is checked at boot. A shape that needed renaming or
// reshaping would drop the marker and write ToCommand by hand instead.
func (r RemoveUserGroupGraphQLRequest) ToCommand() *commands.RemoveUserGroupCommand {
	return fwrequests.AutoFromRequest[*commands.RemoveUserGroupCommand](r)
}

// RemoveUserGroupGraphQLResponse acknowledges the removal, and says nothing
// else.
//
// The REST verb answers 204 with no body. A GraphQL field cannot: it must
// resolve to a type, and a payload with no fields is not publishable. So the
// payload is a single true — the owner id is what the caller passed in, and
// the entry is gone by definition.
//
// No generic mapper here, and it is not an oversight: the command projects the
// framework's None, so there is no Result field for a mapped one to read.
type RemoveUserGroupGraphQLResponse struct {
	Success bool `json:"success"`
}

// FromResult answers true: the pipeline only projects a result it succeeded
// with.
func (RemoveUserGroupGraphQLResponse) FromResult(fwresults.None) RemoveUserGroupGraphQLResponse {
	return RemoveUserGroupGraphQLResponse{Success: true}
}
