// Code generated by omnicore-gen. DO NOT EDIT.
//
// The Claim service port (5 fact(s)).
//
// entity:     Claim
// spec:       specs/omnicore-gen/claim.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-29
// checksum:   sha256:a57e75436a8756dcf1fc4bff79d66a450b6d5546284fed20f31aa36a031f2747
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package domain

import "github.com/ClaudioSchirmer/omnicore/domain"

// ClaimService answers the questions Claim's rules cannot answer alone.
//
// Every method returns a plain value and NO error. That is deliberate: the
// domain performs no IO, so an error here would leave a rule with three bad
// options — panic, swallow it, or invent an answer. A failed query is
// infra's problem and is raised there.
type ClaimService interface {
	domain.Service

	// Reports whether another ACTIVE claim in the same tenant already holds
	// this name. Excludes the row being updated.
	ClaimNameTaken(tenantID domain.ID, name string, selfID domain.ID) bool

	// Whether the owning tenant is missing, archived, or commercially
	// SUSPENDED. Queries the tenants table by its primary key. A trial tenant
	// is a live customer and is available.
	TenantIsUnavailable(tenantID domain.ID) bool

	// Whether any ACTIVE user_claims row references the ACTIVE claim
	// definition identified by this tenant and name. Join user_claims to
	// claims on claim_id and require user_claims.deleted_at IS NULL AND
	// claims.deleted_at IS NULL — archived edges do not count, because a
	// value somebody removed must not freeze the definition's shape, and the
	// archived-definition half is what keeps a retired row's leftovers out of
	// the answer.
	ClaimIsHeldByAUser(tenantID domain.ID, name string) bool

	// Whether any ACTIVE client_claims row references the ACTIVE claim
	// definition identified by this tenant and name. Same join and the same
	// two archive predicates as its user twin.
	ClaimIsHeldByAClient(tenantID domain.ID, name string) bool

	// How many ACTIVE claim definitions of this tenant declare EXACTLY this
	// AppliesTo member. The two catalog-cap rules add two of these answers to
	// get a bucket: the user bucket is `user` + `both`, the client bucket is
	// `client` + `both`.
	ActiveClaimsWithAppliesTo(tenantID domain.ID, appliesTo string) int64
}
