// Code generated by omnicore-gen. DO NOT EDIT.
//
// The ClientClaimValueDoesNotMatchValueTypeEntry answer shape.
//
// entity:     Client
// spec:       specs/omnicore-gen/client.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-01
// checksum:   sha256:15851d54192d0347a06802d7ce7a6a6befb482d835ef8b44b023d089ccacd508
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package domain

import "github.com/ClaudioSchirmer/omnicore/domain"

// ClientClaimValueDoesNotMatchValueTypeEntry is ONE entry of Claims, as
// ClaimValueDoesNotMatchValueType is asked about it.
//
// The question needs ClaimID and Value of the same entry, and they travel
// together for one reason: two parallel slices are two things a caller can put
// out of step, and the answer would then be about a different entry than the
// one whose values were sent.
//
// ClaimID is what the answer is keyed by.
type ClientClaimValueDoesNotMatchValueTypeEntry struct {
	ClaimID domain.ID
	Value   string
}
