// Code generated by omnicore-gen. DO NOT EDIT.
//
// The Client service port (9 fact(s)).
//
// entity:     Client
// spec:       specs/omnicore-gen/client.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-29
// checksum:   sha256:e3ddaa478949ae779502b0dc64a070760e14a66e79120419d32f8ea4293c70b4
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package domain

import "github.com/ClaudioSchirmer/omnicore/domain"

// ClientService answers the questions Client's rules cannot answer alone.
//
// Every method returns a plain value and NO error. That is deliberate: the
// domain performs no IO, so an error here would leave a rule with three bad
// options — panic, swallow it, or invent an answer. A failed query is
// infra's problem and is raised there.
type ClientService interface {
	domain.Service

	// Reports whether another ACTIVE client in the SAME tenant already holds
	// this label. Excludes the row being updated, so an update never collides
	// with itself.
	NameTaken(tenantID domain.ID, name string, selfID domain.ID) bool

	// The SHA-256 of the secret, lowercase hex. NOT Argon2id, and the reason
	// is in spec §B-Q4: memory-hardness buys nothing against 256 random bits
	// and costs 19 MiB per verify on an unauthenticated endpoint. No salt —
	// a rainbow table over 2^256 random values cannot exist. Pure CPU, no
	// query. It must never log its input, and whatever verifies against it
	// must compare with crypto/subtle.
	HashSecret(secret string) string

	// Whether the owning tenant is missing, archived, or commercially
	// SUSPENDED. Queries the tenants table by its primary key. A trial tenant
	// is a live customer and is available.
	TenantIsUnavailable(tenantID domain.ID) bool

	// Whether this role id is absent from the roles table, points at an
	// archived role, or belongs to a tenant OTHER than the one passed. One
	// answer for all three — the caller-facing message must not distinguish
	// them. Asked ONCE PER ENTRY of Roles, so the answer is about that entry
	// and the cost of the body is multiplied by the size of the collection.
	RoleIsUnavailableInTenant(tenantID domain.ID, roleID domain.ID) bool

	// Whether this role grants a permission carrying a wildcard in either
	// part. Answers TRUE when the id is unknown, so an unresolvable grant
	// never reaches the escalation probe — the framework's HasPermission
	// panics on a wildcard argument. Asked ONCE PER ENTRY of Roles, so the
	// answer is about that entry and the cost of the body is multiplied by the
	// size of the collection.
	RoleGrantsWildcard(roleID domain.ID) bool

	// Whether the requesting caller fails to hold at least one permission this
	// role confers — the escalation half. GUARDS THE WILDCARD ITSELF and
	// answers "lacks" rather than calling through, because a panic on a
	// security rule is a 500. A *:* superadmin passes by construction. Asked
	// ONCE PER ENTRY of Roles, so the answer is about that entry and the cost
	// of the body is multiplied by the size of the collection.
	CallerLacksAnyPermissionOfRole(roleID domain.ID) bool

	// Whether this claim id is absent from the claims table, points at an
	// archived definition, or belongs to a tenant OTHER than the one passed.
	// One answer for all three — the caller-facing message must not
	// distinguish them. Asked ONCE PER ENTRY of Claims, so the answer is about
	// that entry and the cost of the body is multiplied by the size of the
	// collection.
	ClaimIsUnavailableInTenant(tenantID domain.ID, claimID domain.ID) bool

	// Whether the definition behind this id declares appliesTo: user, so no
	// machine client may hold a value for it. client and both answer false.
	// Answers TRUE for an unknown id. Asked ONCE PER ENTRY of Claims, so the
	// answer is about that entry and the cost of the body is multiplied by the
	// size of the collection.
	ClaimDoesNotApplyToClient(claimID domain.ID) bool

	// Whether the value fails to parse as the ValueType the definition
	// declares: `number` wants a valid decimal number, `bool` wants exactly
	// "true" or "false", `string` wants any non-empty value. The same three
	// readings the catalog's own default-value check uses. Answers TRUE for an
	// unknown id. Asked ONCE PER ENTRY of Claims, so the answer is about that
	// entry and the cost of the body is multiplied by the size of the
	// collection.
	ClaimValueDoesNotMatchValueType(claimID domain.ID, value string) bool
}
