// Code generated by omnicore-gen. DO NOT EDIT.
//
// The Group service port (5 fact(s)).
//
// entity:     Group
// spec:       specs/omnicore-gen/group.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-29
// checksum:   sha256:538deb15ca18ab5b9a8a1a840f429e234b3ddafe3d0eb8a008af1f68cd00d7e0
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package domain

import "github.com/ClaudioSchirmer/omnicore/domain"

// GroupService answers the questions Group's rules cannot answer alone.
//
// Every method returns a plain value and NO error. That is deliberate: the
// domain performs no IO, so an error here would leave a rule with three bad
// options — panic, swallow it, or invent an answer. A failed query is
// infra's problem and is raised there.
type GroupService interface {
	domain.Service

	// Reports whether another ACTIVE group in the same tenant already holds
	// this key. Excludes the row being updated.
	GroupKeyTaken(tenantID domain.ID, key string, selfID domain.ID) bool

	// Whether the owning tenant is missing, archived, or commercially
	// SUSPENDED. Queries the tenants table by its primary key. A trial tenant
	// is a live customer and is available.
	TenantIsUnavailable(tenantID domain.ID) bool

	// Whether this role id is absent from the roles table, points at an
	// archived role, or belongs to a tenant OTHER than the one passed. One
	// answer for all three questions — the caller-facing message must not
	// distinguish them, because a distinct "belongs to another tenant" reply
	// is an existence oracle over a competitor's org chart. Asked ONCE PER
	// ENTRY of Roles, so the answer is about that entry and the cost of the
	// body is multiplied by the size of the collection.
	RoleIsUnavailableInTenant(tenantID domain.ID, roleID domain.ID) bool

	// Whether the role behind this id grants any permission carrying a
	// wildcard in either part. Resolve the role through RoleRepository.Loader,
	// whose declared read join fills every grant's resource and action.
	// Answers TRUE when the id is unknown, so an unresolvable attachment never
	// reaches the escalation probe. Asked ONCE PER ENTRY of Roles, so the
	// answer is about that entry and the cost of the body is multiplied by the
	// size of the collection.
	RoleGrantsWildcard(roleID domain.ID) bool

	// Whether the requesting caller fails to hold at least one of the
	// permissions this role grants — the TRANSITIVE half of the escalation
	// rule. Resolves the role through the same single read RoleGrantsWildcard
	// uses, then asks the caller's claim for every key it found. Judges EVERY
	// key the role grants, archived catalog rows included: that is the
	// fail-closed direction, and since the grants no longer carry the catalog
	// row's archive stamp it is also the only reading expressible without a
	// second query. It GUARDS THE WILDCARD ITSELF and answers "lacks" rather
	// than calling through — defence in depth behind the wildcard rule,
	// because a panic on a security rule is a 500. Reads ctx.Identity()
	// through the request-scoped service. Asked ONCE PER ENTRY of Roles, so
	// the answer is about that entry and the cost of the body is multiplied by
	// the size of the collection.
	CallerLacksAnyPermissionOf(roleID domain.ID) bool
}
