// Code generated by omnicore-gen. DO NOT EDIT.
//
// The Permission service port (1 fact(s)).
//
// entity:     Permission
// spec:       specs/omnicore-gen/permission.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-29
// checksum:   sha256:50dbc75077abaef36db397bcd757ab7f33cfaf531594dcd2c4f870efffc47f56
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package domain

import "github.com/ClaudioSchirmer/omnicore/domain"

// PermissionService answers the questions Permission's rules cannot answer
// alone.
//
// Every method returns a plain value and NO error. That is deliberate: the
// domain performs no IO, so an error here would leave a rule with three bad
// options — panic, swallow it, or invent an answer. A failed query is
// infra's problem and is raised there.
type PermissionService interface {
	domain.Service

	// Reports whether another ACTIVE permission already holds this resource
	// and action pair. Excludes the row being updated.
	PermissionKeyTaken(resource string, action string, selfID domain.ID) bool
}
