// Code generated by omnicore-gen. DO NOT EDIT.
//
// Tests for Permission's rules.
//
// entity:     Permission
// spec:       specs/omnicore-gen/permission.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-29
// checksum:   sha256:529c2a7810bc4bbb428b8add5d699508924e5d1c92497ac6849bebc828c6b259
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package domain

import (
	"errors"
	"strings"
	"testing"

	"github.com/ClaudioSchirmer/authcore/internal/domain/vos"
	"github.com/ClaudioSchirmer/omnicore/domain"
)

// rejectedFields lists the fields a rejection blamed.
//
// Rules report through a carrier rather than by returning the first problem,
// so a rejection can name several fields at once — asserting on the set is
// what tells a failing test which rule actually broke.
func permissionRejectedFields(err error) []string {
	var carrier domain.NotificationCarrier
	if !errors.As(err, &carrier) {
		return nil
	}
	var out []string
	for _, ctx := range carrier.NotificationContexts() {
		for _, msg := range ctx.Messages() {
			name := msg.FieldName
			if msg.Override != "" {
				name = msg.Override
			}
			for _, seg := range msg.Path {
				if seg.Name != "" {
					name = seg.Name
				}
			}
			out = append(out, name)
		}
	}
	return out
}

func permissionBlames(err error, field string) bool {
	for _, f := range permissionRejectedFields(err) {
		if f == field || strings.HasSuffix(f, "."+field) {
			return true
		}
	}
	return false
}

// stubPermissionService answers every probe with "nothing found".
//
// A nil service is not an option: the framework refuses the write before any
// rule runs, and every case here would fail for that instead of for the rule
// under test. Answering "nothing found" lets a valid aggregate through.
type stubPermissionService struct {
	domain.ServiceBase
}

func (stubPermissionService) PermissionKeyTaken(_ string, _ string, _ domain.ID) bool { return false }

// validPermission returns an aggregate that satisfies every declared rule.
//
// Each negative case below starts here and breaks one thing, so the failure
// points at the rule under test rather than at unrelated invalid state.
func validPermission() *Permission {
	return &Permission{
		Description: vos.Description("Read tenants: list the tenant registry and fetch a tenant by id."),
		Key:         vos.PermissionKey{Resource: "tenant", Action: "read"},
	}
}

// A valid Permission must be accepted — otherwise every negative case below
// would pass for the wrong reason.
func TestValidPermissionIsAccepted(t *testing.T) {
	if _, err := domain.GetInsertable(validPermission(), &stubPermissionService{}, "GetInsertable"); err != nil {
		t.Fatalf("a valid Permission was rejected: %v (fields: %v)", err, permissionRejectedFields(err))
	}
}

// Permission declares the aggregate contract the framework reads.
//
// Nothing here is called by a rule, which is exactly why it is worth a test:
// the framework calls it, and a disagreement surfaces at boot or as a write
// that quietly saves nothing.
func TestPermissionDeclaresItsAggregateContract(t *testing.T) {
	e := validPermission()
	if !e.RequiresService() {
		t.Error("the entity stopped requiring the domain service, and the rules that ask it would be handed a nil")
	}
}

// Every notification answers the semantic the spec declared.
//
// The semantic is the status code: conflict is 409, validation is 422,
// forbidden is 403. A wrong one still compiles and still returns a rejection
// — just the kind a client handles differently.
func TestPermissionNotificationSemantics(t *testing.T) {
	for _, tc := range []struct {
		name string
		got  domain.NotificationSemantic
		want domain.NotificationSemantic
	}{
		{"PermissionAlreadyExistsNotification", PermissionAlreadyExistsNotification{}.Semantic(), domain.SemanticConflict},
		{"PermissionKeyIsImmutableNotification", PermissionKeyIsImmutableNotification{}.Semantic(), domain.SemanticValidation},
		{"PermissionDescriptionEchoesKeyNotification", PermissionDescriptionEchoesKeyNotification{}.Semantic(), domain.SemanticValidation},
		{"InvalidResourceNameNotification", vos.InvalidResourceNameNotification{}.Semantic(), domain.SemanticValidation},
		{"InvalidActionNameNotification", vos.InvalidActionNameNotification{}.Semantic(), domain.SemanticValidation},
		{"UnmatchablePermissionKeyNotification", vos.UnmatchablePermissionKeyNotification{}.Semantic(), domain.SemanticValidation},
	} {
		if tc.got != tc.want {
			t.Errorf("%s answers %v, the spec says %v", tc.name, tc.got, tc.want)
		}
	}
}

// Key cannot change once set.
//
// It is driven through the update path because the rule reads the previous
// value, and on an insert there is no previous value to read.
func TestPermission_Key_IsImmutable(t *testing.T) {
	e := validPermission()
	_, err := domain.GetUpdatable(e, func(x *Permission) error {
		x.Key = vos.PermissionKey{Resource: "changed-value", Action: "read"}
		return nil
	}, &stubPermissionService{}, "GetUpdatable")
	if err == nil {
		t.Fatal("changing Key was accepted")
	}
	if !permissionBlames(err, "Key") {
		t.Errorf("the rejection should name Key, it named %v", permissionRejectedFields(err))
	}
}
