// Code generated by omnicore-gen. DO NOT EDIT.
//
// The Role service port (5 fact(s)).
//
// entity:     Role
// spec:       specs/omnicore-gen/role.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-21
// checksum:   sha256:87f3b1ad45f9d9896e0aa45968e96c883d70b03c3727ab64543c6a1ce20f06f8
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package domain

import "github.com/ClaudioSchirmer/omnicore/domain"

// RoleService answers the questions Role's rules cannot answer alone.
//
// Every method returns a plain value and NO error. That is deliberate: the
// domain performs no IO, so an error here would leave a rule with three bad
// options — panic, swallow it, or invent an answer. A failed query is
// infra's problem and is raised there.
type RoleService interface {
	domain.Service

	// Whether this tenant already has an ACTIVE role under this key.
	RoleKeyTaken(tenantID domain.ID, key string, selfID domain.ID) bool

	// Whether the owner tenant is unknown or archived. Not answerable from
	// this entity's own table — it is a question about the tenants table, so
	// the implementation holds the tenant repository beside its own.
	TenantIsUnavailable(tenantID domain.ID) bool

	// Whether this granted permission is absent from the catalog or archived.
	// Asked once per entry. Not answerable declaratively — the column lives
	// on the permissions table, not on this entity's. Asked ONCE PER ENTRY of
	// Permissions, so the answer is about that entry and the cost of the body
	// is multiplied by the size of the collection.
	PermissionIsNotInCatalog(permissionID domain.ID) bool

	// Whether the catalog row this grant points at carries a wildcard in
	// either part. Asked once per entry, and answered by resolving the id to
	// its vos.PermissionKey. It is what keeps every wildcard string away from
	// Identity.HasPermission, which panics on one — so it must answer TRUE
	// for an unknown id too, rather than let an unresolvable grant fall
	// through to the caller-holds question. Asked ONCE PER ENTRY of
	// Permissions, so the answer is about that entry and the cost of the body
	// is multiplied by the size of the collection.
	PermissionIsWildcard(permissionID domain.ID) bool

	// Whether the authenticated caller lacks the permission this grant points
	// at. Asked once per entry, and only for concrete keys —
	// no-wildcard-grant has already refused the wildcards. Implementation:
	// resolve the id to its key; return false when ctx.Identity() is nil (auth
	// disabled, dev only) so the rule stands down; otherwise answer NOT
	// Identity.HasPermission(key). Guard the wildcard here as well and answer
	// true rather than calling through — a panic on a security rule is a
	// 500. Asked ONCE PER ENTRY of Permissions, so the answer is about that
	// entry and the cost of the body is multiplied by the size of the
	// collection.
	CallerDoesNotHoldPermission(permissionID domain.ID) bool
}
