// Code generated by omnicore-gen. DO NOT EDIT.
//
// The add command for one user_groups entry.
//
// entity:     User
// spec:       specs/omnicore-gen/user.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-01
// checksum:   sha256:49db52df1f5bbaa484c518b2f2ca1407128db836ea8b59ca496c563c6911b8ba
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package commands

import (
	"github.com/ClaudioSchirmer/omnicore/application/configuration"
	"github.com/ClaudioSchirmer/omnicore/application/pipeline"
	"github.com/ClaudioSchirmer/omnicore/domain"

	cmddtos "github.com/ClaudioSchirmer/authcore/internal/application/commands/dtos"
	cmdutils "github.com/ClaudioSchirmer/authcore/internal/application/commands/utils"
	"github.com/ClaudioSchirmer/authcore/internal/application/dtos"
	appdomain "github.com/ClaudioSchirmer/authcore/internal/domain"
	"github.com/ClaudioSchirmer/authcore/internal/domain/aggregatevos"
)

// AddUserGroupCommand adds ONE entry to User's groups.
//
// The path carries the OWNER's id; the body is the entry. The aggregate is
// loaded, the entry appended, and the whole thing saved in one transaction —
// so the collection's invariants are checked against what will actually be
// stored.
type AddUserGroupCommand struct {
	pipeline.CommandWithBodyIDBase
	GroupID domain.ID
}

func (cmd *AddUserGroupCommand) ApplyTo(ctx *configuration.AppContext, e *appdomain.User) error {
	e.AddUserGroup(dtos.UserGroupInput{
		GroupID: cmd.GroupID,
	}.ToUserGroup())

	// Identity-derived state the rules read. It is never persisted.
	if id := ctx.Identity(); id != nil {
		e.RequestingUserID = id.Subject
		e.RequestingIdentityPresent = true
		e.RequestingTenant = id.TenantID()
		// The super-admin grant, not asked through HasPermission: that
		// method panics on a wildcard, since the CLAIM wildcards and the
		// question does not. The framework gives the wildcard its own
		// question, and this is it.
		e.RequestingMayCrossScope = id.IsSuperAdmin()
	}
	return nil
}

// AddUserGroupResult is the owner plus the entry as stored.
type AddUserGroupResult struct {
	UserID    domain.ID
	UserGroup cmddtos.UserGroupResult
}

func (cmd *AddUserGroupCommand) FromEntity(_ *configuration.AppContext, e *appdomain.User) (AddUserGroupResult, error) {
	items := domain.GetCurrentItemsOf[aggregatevos.UserGroup](e.GetAggregateRoot())
	out := AddUserGroupResult{UserID: *e.GetID()}
	// The entry as STORED, which is the last one the aggregate holds — the
	// domain may have normalised a value the caller sent.
	if len(items) > 0 {
		out.UserGroup = cmdutils.ProjectOneUserGroup(items[len(items)-1])
	}
	return out, nil
}
