// Code generated by omnicore-gen. DO NOT EDIT.
//
// The add command for one client_claims entry.
//
// entity:     Client
// spec:       specs/omnicore-gen/client.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-07
// checksum:   sha256:c094de5a1abe627be3841189e501305f88752e4282b7e4231388b4d185a5f7f0
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package commands

import (
	"github.com/ClaudioSchirmer/omnicore/application/configuration"
	"github.com/ClaudioSchirmer/omnicore/application/pipeline"
	"github.com/ClaudioSchirmer/omnicore/domain"

	cmddtos "github.com/ClaudioSchirmer/authcore/internal/application/commands/dtos"
	cmdutils "github.com/ClaudioSchirmer/authcore/internal/application/commands/utils"
	"github.com/ClaudioSchirmer/authcore/internal/application/dtos"
	appdomain "github.com/ClaudioSchirmer/authcore/internal/domain"
	"github.com/ClaudioSchirmer/authcore/internal/domain/aggregatevos"
)

// AddClientClaimCommand adds ONE entry to Client's claims.
//
// The path carries the OWNER's id; the body is the entry. The aggregate is
// loaded, the entry appended, and the whole thing saved in one transaction —
// so the collection's invariants are checked against what will actually be
// stored.
type AddClientClaimCommand struct {
	pipeline.CommandWithBodyIDBase
	ClaimID domain.ID
	Value   string
}

func (cmd *AddClientClaimCommand) ApplyTo(ctx *configuration.AppContext, e *appdomain.Client) error {
	e.AddClientClaim(dtos.ClientClaimInput{
		ClaimID: cmd.ClaimID,
		Value:   cmd.Value,
	}.ToClientClaim())

	// Identity-derived state the rules read. It is never persisted.
	//
	// The framework does not opine on which custom claims a token carries, so
	// the claim name comes from the spec rather than from a convention.
	if id := ctx.Identity(); id != nil {
		e.RequestingClientID = id.Subject
		if raw, ok := id.Claims["identity_kind"].(string); ok {
			e.RequestingIdentityKind = raw
		}
		e.RequestingTenant = id.TenantID()
		e.RequestingIdentityPresent = true
		// The super-admin grant, not asked through HasPermission: that
		// method panics on a wildcard, since the CLAIM wildcards and the
		// question does not. The framework gives the wildcard its own
		// question, and this is it.
		e.RequestingMayCrossScope = id.IsSuperAdmin()
	}
	return nil
}

// AddClientClaimResult is the owner plus the entry as stored.
type AddClientClaimResult struct {
	ClientID    domain.ID
	ClientClaim cmddtos.ClientClaimResult
}

func (cmd *AddClientClaimCommand) FromEntity(_ *configuration.AppContext, e *appdomain.Client) (AddClientClaimResult, error) {
	items := domain.GetCurrentItemsOf[aggregatevos.ClientClaim](e.GetAggregateRoot())
	out := AddClientClaimResult{ClientID: *e.GetID()}
	// The entry as STORED, which is the last one the aggregate holds — the
	// domain may have normalised a value the caller sent.
	if len(items) > 0 {
		out.ClientClaim = cmdutils.ProjectOneClientClaim(items[len(items)-1])
	}
	return out, nil
}
