// Code generated by omnicore-gen. DO NOT EDIT.
//
// The archive command and result.
//
// entity:     Claim
// spec:       specs/omnicore-gen/claim.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-28
// checksum:   sha256:898f5a9b0a37b1a8dc55fd6478c29f17bb6e9bfe632d8959062fd70edbb3b3bc
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package commands

import (
	"github.com/ClaudioSchirmer/omnicore/application/configuration"
	"github.com/ClaudioSchirmer/omnicore/application/pipeline"

	appdomain "github.com/ClaudioSchirmer/authcore/internal/domain"
	fwresults "github.com/ClaudioSchirmer/omnicore/application/results"
)

// ArchiveClaimCommand carries only the id, taken from the route. The verb has
// no body and answers 204: there is nothing to send back.
type ArchiveClaimCommand struct{ pipeline.CommandByIDBase }

// ApplyTo carries the caller's identity onto the entity, so BuildRules can
// refuse a write to a row outside the caller's scope. The verb has no body:
// this is the only thing it applies.
func (c *ArchiveClaimCommand) ApplyTo(ctx *configuration.AppContext, e *appdomain.Claim) error {

	// Identity-derived state the rules read. It is never persisted.
	if id := ctx.Identity(); id != nil {
		e.RequestingIdentityPresent = true
		e.RequestingTenant = id.TenantID()
		// The super-admin grant, not asked through HasPermission: that
		// method panics on a wildcard, since the CLAIM wildcards and the
		// question does not. The framework gives the wildcard its own
		// question, and this is it.
		e.RequestingMayCrossScope = id.IsSuperAdmin()
	}
	return nil
}

// FromEntity returns the framework's empty result: a bodyless verb has nothing
// to project.
func (c *ArchiveClaimCommand) FromEntity(_ *configuration.AppContext, _ *appdomain.Claim) (fwresults.None, error) {
	return fwresults.None{}, nil
}
