// Code generated by omnicore-gen. DO NOT EDIT.
//
// Tests for archive_permission_command.go.
//
// entity:     Permission
// spec:       specs/omnicore-gen/permission.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-01
// checksum:   sha256:e0c987779213d7f2a7f1543707f729d2358ad3ac826d93f11cdcd294497e69e5
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package commands

import (
	"testing"

	appdomain "github.com/ClaudioSchirmer/authcore/internal/domain"
	"github.com/ClaudioSchirmer/omnicore/application/configuration"
	"github.com/ClaudioSchirmer/omnicore/domain"
)

// ArchivePermissionCommand must apply cleanly to a well-formed entity.
//
// Archive and unarchive carry no body, so what is under test is that the
// mapper leaves the entity alone and reports no error — a mapper that errors
// here turns a legitimate verb into a 400.
func TestArchivePermissionCommandApplies(t *testing.T) {
	ctx := &configuration.AppContext{}
	e := &appdomain.Permission{}
	// The result carries the id, and a verb that reaches this mapper has always
	// loaded the row first — so the entity under test has one too.
	e.SetID(domain.NewID("019ffd00-0000-7000-8000-000000000000"))
	c := &ArchivePermissionCommand{}
	if err := c.ApplyTo(ctx, e); err != nil {
		t.Fatalf("the mapper failed: %v", err)
	}
	if _, err := c.FromEntity(ctx, e); err != nil {
		t.Errorf("projecting the result failed: %v", err)
	}
}
