// Code generated by omnicore-gen. DO NOT EDIT.
//
// The archive command for one user_claims entry.
//
// entity:     User
// spec:       specs/omnicore-gen/user.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-01
// checksum:   sha256:44d34fef59c578c95fef5debeb43137bbc9a9e8b1d9302e3cfcb9149d3128efd
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package commands

import (
	"github.com/ClaudioSchirmer/omnicore/application/configuration"
	"github.com/ClaudioSchirmer/omnicore/application/pipeline"

	fwresults "github.com/ClaudioSchirmer/omnicore/application/results"

	appdomain "github.com/ClaudioSchirmer/authcore/internal/domain"
)

// ArchiveUserClaimCommand takes ONE entry out of the collection.
//
// There is no body: the entry is named by the path. The verb's NAME says which
// of the two removals this collection declared — archived, keeping the row,
// or purged.
type ArchiveUserClaimCommand struct {
	pipeline.CommandWithBodyIDBase
	UserClaimID string
}

func (cmd *ArchiveUserClaimCommand) ApplyTo(ctx *configuration.AppContext, e *appdomain.User) error {
	e.RemoveUserClaimByID(cmd.UserClaimID)

	// Identity-derived state the rules read. It is never persisted.
	if id := ctx.Identity(); id != nil {
		e.RequestingUserID = id.Subject
		e.RequestingIdentityPresent = true
		e.RequestingTenant = id.TenantID()
		// The super-admin grant, not asked through HasPermission: that
		// method panics on a wildcard, since the CLAIM wildcards and the
		// question does not. The framework gives the wildcard its own
		// question, and this is it.
		e.RequestingMayCrossScope = id.IsSuperAdmin()
	}
	return nil
}

// FromEntity projects nothing: the entry ArchiveUserClaimCommand named is
// gone, so the endpoint answers 204 — and the framework's NoBody projection
// is paired with a None on this side.
func (cmd *ArchiveUserClaimCommand) FromEntity(_ *configuration.AppContext, _ *appdomain.User) (fwresults.None, error) {
	return fwresults.None{}, nil
}
