// Code generated by omnicore-gen. DO NOT EDIT.
//
// The per-entry commands for client_claims.
//
// entity:     Client
// spec:       specs/omnicore-gen/client.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-29
// checksum:   sha256:7fe6ca8a03cc4704c128a2efec651283660b84f26696bfad10163c94248ac1f2
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package commands

import (
	"github.com/ClaudioSchirmer/omnicore/application/configuration"
	"github.com/ClaudioSchirmer/omnicore/application/pipeline"
	fwresults "github.com/ClaudioSchirmer/omnicore/application/results"
	"github.com/ClaudioSchirmer/omnicore/domain"

	"github.com/ClaudioSchirmer/authcore/internal/application/dtos"
	appdomain "github.com/ClaudioSchirmer/authcore/internal/domain"
	"github.com/ClaudioSchirmer/authcore/internal/domain/aggregatevos"
)

// AddClientClaimCommand adds ONE entry to Client's claims.
//
// The path carries the OWNER's id; the body is the entry. The aggregate is
// loaded, the entry appended, and the whole thing saved in one transaction —
// so the collection's invariants are checked against what will actually be
// stored.
type AddClientClaimCommand struct {
	pipeline.CommandWithBodyIDBase
	ClaimID domain.ID
	Value   string
}

func (cmd *AddClientClaimCommand) ApplyTo(ctx *configuration.AppContext, e *appdomain.Client) error {
	e.AddClientClaim(dtos.ClientClaimInput{
		ClaimID: cmd.ClaimID,
		Value:   cmd.Value,
	}.ToClientClaim())

	// Identity-derived state the rules read. It is never persisted.
	//
	// The framework does not opine on which custom claims a token carries, so
	// the claim name comes from the spec rather than from a convention.
	if id := ctx.Identity(); id != nil {
		e.RequestingClientID = id.Subject
		if raw, ok := id.Claims["identity_kind"].(string); ok {
			e.RequestingIdentityKind = raw
		}
		e.RequestingIdentityPresent = true
		e.RequestingTenant = id.TenantID()
		// The super-admin grant, not asked through HasPermission: that
		// method panics on a wildcard, since the CLAIM wildcards and the
		// question does not. The framework gives the wildcard its own
		// question, and this is it.
		e.RequestingMayCrossScope = id.IsSuperAdmin()
	}
	return nil
}

// AddClientClaimResult is the owner plus the entry as stored.
type AddClientClaimResult struct {
	ClientID    domain.ID
	ClientClaim ClientClaimResult
}

func (cmd *AddClientClaimCommand) FromEntity(_ *configuration.AppContext, e *appdomain.Client) (AddClientClaimResult, error) {
	items := domain.GetCurrentItemsOf[aggregatevos.ClientClaim](e.GetAggregateRoot())
	out := AddClientClaimResult{ClientID: *e.GetID()}
	// The entry as STORED, which is the last one the aggregate holds — the
	// domain may have normalised a value the caller sent.
	if len(items) > 0 {
		out.ClientClaim = projectOneClientClaim(items[len(items)-1])
	}
	return out, nil
}

// PatchClientClaimCommand changes SOME fields of ONE entry, keeping its id.
//
// Every field is a pointer because a partial change is tri-state: a nil field
// means the caller did not send it, which is different from sending an empty
// value. The consequence is the root patch's own — this verb cannot set a
// value back to null.
//
// The fields it does not carry are not defaults and not blanks: they are read
// off the stored entry, which is what makes this a change to the entry rather
// than a replacement of it. An id the collection does not hold answers
// not-found, exactly as the full replacement does.
type PatchClientClaimCommand struct {
	pipeline.CommandWithBodyIDBase
	ClientClaimID string
	Value         *string
}

func (cmd *PatchClientClaimCommand) ApplyPartiallyTo(ctx *configuration.AppContext, e *appdomain.Client) error {
	// The entry AS STORED. A partial change is a change to what the server
	// already holds, so everything this verb does not carry — the business
	// identity first of all — comes from here and never from the body.
	var entry dtos.ClientClaimInput
	for _, current := range domain.GetCurrentItemsOf[aggregatevos.ClientClaim](e.GetAggregateRoot()) {
		if current.GetID().Value() != cmd.ClientClaimID {
			continue
		}
		stored := projectOneClientClaim(current)
		entry = dtos.ClientClaimInput{
			ClaimID: stored.ClaimID,
			Value:   stored.Value,
		}
		break
	}

	// Then what the caller sent, and only that.
	if cmd.Value != nil {
		entry.Value = *cmd.Value
	}

	// Addressed by id, always — including when the loop above matched nothing.
	// The aggregate answers not-found for an entry it does not hold, and it is
	// the ONE place that answer is decided: the empty replacement never lands,
	// because there is no entry for it to land on.
	e.ChangeClientClaimByID(cmd.ClientClaimID, entry.ToClientClaim())

	// Identity-derived state the rules read. It is never persisted.
	//
	// The framework does not opine on which custom claims a token carries, so
	// the claim name comes from the spec rather than from a convention.
	if id := ctx.Identity(); id != nil {
		e.RequestingClientID = id.Subject
		if raw, ok := id.Claims["identity_kind"].(string); ok {
			e.RequestingIdentityKind = raw
		}
		e.RequestingIdentityPresent = true
		e.RequestingTenant = id.TenantID()
		// The super-admin grant, not asked through HasPermission: that
		// method panics on a wildcard, since the CLAIM wildcards and the
		// question does not. The framework gives the wildcard its own
		// question, and this is it.
		e.RequestingMayCrossScope = id.IsSuperAdmin()
	}
	return nil
}

// PatchClientClaimResult is the owner plus the entry as stored.
type PatchClientClaimResult struct {
	ClientID    domain.ID
	ClientClaim ClientClaimResult
}

func (cmd *PatchClientClaimCommand) FromEntity(_ *configuration.AppContext, e *appdomain.Client) (PatchClientClaimResult, error) {
	out := PatchClientClaimResult{ClientID: *e.GetID()}
	for _, item := range domain.GetCurrentItemsOf[aggregatevos.ClientClaim](e.GetAggregateRoot()) {
		if item.GetID().Value() == cmd.ClientClaimID {
			out.ClientClaim = projectOneClientClaim(item)
			break
		}
	}
	return out, nil
}

// RemoveClientClaimCommand takes ONE entry out of the collection.
//
// There is no body: the entry is named by the path. Whether the row is
// archived or deleted follows the child's own declaration, not this verb.
type RemoveClientClaimCommand struct {
	pipeline.CommandWithBodyIDBase
	ClientClaimID string
}

func (cmd *RemoveClientClaimCommand) ApplyTo(ctx *configuration.AppContext, e *appdomain.Client) error {
	e.RemoveClientClaimByID(cmd.ClientClaimID)

	// Identity-derived state the rules read. It is never persisted.
	//
	// The framework does not opine on which custom claims a token carries, so
	// the claim name comes from the spec rather than from a convention.
	if id := ctx.Identity(); id != nil {
		e.RequestingClientID = id.Subject
		if raw, ok := id.Claims["identity_kind"].(string); ok {
			e.RequestingIdentityKind = raw
		}
		e.RequestingIdentityPresent = true
		e.RequestingTenant = id.TenantID()
		// The super-admin grant, not asked through HasPermission: that
		// method panics on a wildcard, since the CLAIM wildcards and the
		// question does not. The framework gives the wildcard its own
		// question, and this is it.
		e.RequestingMayCrossScope = id.IsSuperAdmin()
	}
	return nil
}

// FromEntity projects nothing: the entry RemoveClientClaimCommand named is
// gone, so the endpoint answers 204 — and the framework's NoBody projection
// is paired with a None on this side.
func (cmd *RemoveClientClaimCommand) FromEntity(_ *configuration.AppContext, _ *appdomain.Client) (fwresults.None, error) {
	return fwresults.None{}, nil
}

// projectOneClientClaim renders one stored entry.
//
// Its plural twin projects the whole collection for the root's own verbs; this
// one exists because a per-entry verb answers with the entry it touched, not
// with everything around it.
func projectOneClientClaim(item aggregatevos.ClientClaim) ClientClaimResult {
	return ClientClaimResult{
		ID:      item.GetID(),
		ClaimID: item.ClaimID,
		Value:   item.Value.Value(),
	}
}
