// Code generated by omnicore-gen. DO NOT EDIT.
//
// The per-entry commands for client_allowed_cidrs.
//
// entity:     Client
// spec:       specs/omnicore-gen/client.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-28
// checksum:   sha256:32ba0ee45c51a781daceef6b307026cdccf650bc0d5c658a0093ade58d760510
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package commands

import (
	"github.com/ClaudioSchirmer/omnicore/application/configuration"
	"github.com/ClaudioSchirmer/omnicore/application/pipeline"
	fwresults "github.com/ClaudioSchirmer/omnicore/application/results"
	"github.com/ClaudioSchirmer/omnicore/domain"

	"github.com/ClaudioSchirmer/authcore/internal/application/dtos"
	appdomain "github.com/ClaudioSchirmer/authcore/internal/domain"
	"github.com/ClaudioSchirmer/authcore/internal/domain/aggregatevos"
)

// AddClientAllowedCIDRCommand adds ONE entry to Client's allowedCIDRs.
//
// The path carries the OWNER's id; the body is the entry. The aggregate is
// loaded, the entry appended, and the whole thing saved in one transaction —
// so the collection's invariants are checked against what will actually be
// stored.
type AddClientAllowedCIDRCommand struct {
	pipeline.CommandWithBodyIDBase
	CIDR  string
	Label string
}

func (cmd *AddClientAllowedCIDRCommand) ApplyTo(ctx *configuration.AppContext, e *appdomain.Client) error {
	e.AddClientAllowedCIDR(dtos.ClientAllowedCIDRInput{
		CIDR:  cmd.CIDR,
		Label: cmd.Label,
	}.ToClientAllowedCIDR())

	// Identity-derived state the rules read. It is never persisted.
	//
	// The framework does not opine on which custom claims a token carries, so
	// the claim name comes from the spec rather than from a convention.
	if id := ctx.Identity(); id != nil {
		e.RequestingClientID = id.Subject
		if raw, ok := id.Claims["identity_kind"].(string); ok {
			e.RequestingIdentityKind = raw
		}
		e.RequestingIdentityPresent = true
		e.RequestingTenant = id.TenantID()
		// The super-admin grant, not asked through HasPermission: that
		// method panics on a wildcard, since the CLAIM wildcards and the
		// question does not. The framework gives the wildcard its own
		// question, and this is it.
		e.RequestingMayCrossScope = id.IsSuperAdmin()
	}
	return nil
}

// AddClientAllowedCIDRResult is the owner plus the entry as stored.
type AddClientAllowedCIDRResult struct {
	ClientID          domain.ID
	ClientAllowedCIDR ClientAllowedCIDRResult
}

func (cmd *AddClientAllowedCIDRCommand) FromEntity(_ *configuration.AppContext, e *appdomain.Client) (AddClientAllowedCIDRResult, error) {
	items := domain.GetCurrentItemsOf[aggregatevos.ClientAllowedCIDR](e.GetAggregateRoot())
	out := AddClientAllowedCIDRResult{ClientID: *e.GetID()}
	// The entry as STORED, which is the last one the aggregate holds — the
	// domain may have normalised a value the caller sent.
	if len(items) > 0 {
		out.ClientAllowedCIDR = projectOneClientAllowedCIDR(items[len(items)-1])
	}
	return out, nil
}

// RemoveClientAllowedCIDRCommand takes ONE entry out of the collection.
//
// There is no body: the entry is named by the path. Whether the row is
// archived or deleted follows the child's own declaration, not this verb.
type RemoveClientAllowedCIDRCommand struct {
	pipeline.CommandWithBodyIDBase
	ClientAllowedCIDRID string
}

func (cmd *RemoveClientAllowedCIDRCommand) ApplyTo(ctx *configuration.AppContext, e *appdomain.Client) error {
	e.RemoveClientAllowedCIDRByID(cmd.ClientAllowedCIDRID)

	// Identity-derived state the rules read. It is never persisted.
	//
	// The framework does not opine on which custom claims a token carries, so
	// the claim name comes from the spec rather than from a convention.
	if id := ctx.Identity(); id != nil {
		e.RequestingClientID = id.Subject
		if raw, ok := id.Claims["identity_kind"].(string); ok {
			e.RequestingIdentityKind = raw
		}
		e.RequestingIdentityPresent = true
		e.RequestingTenant = id.TenantID()
		// The super-admin grant, not asked through HasPermission: that
		// method panics on a wildcard, since the CLAIM wildcards and the
		// question does not. The framework gives the wildcard its own
		// question, and this is it.
		e.RequestingMayCrossScope = id.IsSuperAdmin()
	}
	return nil
}

// FromEntity projects nothing: the entry RemoveClientAllowedCIDRCommand named
// is
// gone, so the endpoint answers 204 — and the framework's NoBody projection
// is paired with a None on this side.
func (cmd *RemoveClientAllowedCIDRCommand) FromEntity(_ *configuration.AppContext, _ *appdomain.Client) (fwresults.None, error) {
	return fwresults.None{}, nil
}

// projectOneClientAllowedCIDR renders one stored entry.
//
// Its plural twin projects the whole collection for the root's own verbs; this
// one exists because a per-entry verb answers with the entry it touched, not
// with everything around it.
func projectOneClientAllowedCIDR(item aggregatevos.ClientAllowedCIDR) ClientAllowedCIDRResult {
	return ClientAllowedCIDRResult{
		ID:    item.GetID(),
		CIDR:  item.CIDR.Value(),
		Label: item.Label.Value(),
	}
}
