// Code generated by omnicore-gen. DO NOT EDIT.
//
// The per-entry commands for group_roles.
//
// entity:     Group
// spec:       specs/omnicore-gen/group.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-28
// checksum:   sha256:27770e7c014b90fcbf6551c1df4aa88c3c5b80aaec8c9591432856565daf6d9f
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package commands

import (
	"github.com/ClaudioSchirmer/authcore/internal/application/dtos"
	appdomain "github.com/ClaudioSchirmer/authcore/internal/domain"
	"github.com/ClaudioSchirmer/authcore/internal/domain/aggregatevos"
	"github.com/ClaudioSchirmer/omnicore/application/configuration"
	"github.com/ClaudioSchirmer/omnicore/application/pipeline"
	fwresults "github.com/ClaudioSchirmer/omnicore/application/results"
	"github.com/ClaudioSchirmer/omnicore/domain"
)

// AddGroupRoleCommand adds ONE entry to Group's roles.
//
// The path carries the OWNER's id; the body is the entry. The aggregate is
// loaded, the entry appended, and the whole thing saved in one transaction —
// so the collection's invariants are checked against what will actually be
// stored.
type AddGroupRoleCommand struct {
	pipeline.CommandWithBodyIDBase
	RoleID domain.ID
}

func (cmd *AddGroupRoleCommand) ApplyTo(ctx *configuration.AppContext, e *appdomain.Group) error {
	e.AddGroupRole(dtos.GroupRoleInput{
		RoleID: cmd.RoleID,
	}.ToGroupRole())

	// Identity-derived state the rules read. It is never persisted.
	if id := ctx.Identity(); id != nil {
		e.RequestingIdentityPresent = true
		e.RequestingTenant = id.TenantID()
		// The super-admin grant, not asked through HasPermission: that
		// method panics on a wildcard, since the CLAIM wildcards and the
		// question does not. The framework gives the wildcard its own
		// question, and this is it.
		e.RequestingMayCrossScope = id.IsSuperAdmin()
	}
	return nil
}

// AddGroupRoleResult is the owner plus the entry as stored.
type AddGroupRoleResult struct {
	GroupID   domain.ID
	GroupRole GroupRoleResult
}

func (cmd *AddGroupRoleCommand) FromEntity(_ *configuration.AppContext, e *appdomain.Group) (AddGroupRoleResult, error) {
	items := domain.GetCurrentItemsOf[aggregatevos.GroupRole](e.GetAggregateRoot())
	out := AddGroupRoleResult{GroupID: *e.GetID()}
	// The entry as STORED, which is the last one the aggregate holds — the
	// domain may have normalised a value the caller sent.
	if len(items) > 0 {
		out.GroupRole = projectOneGroupRole(items[len(items)-1])
	}
	return out, nil
}

// RemoveGroupRoleCommand takes ONE entry out of the collection.
//
// There is no body: the entry is named by the path. Whether the row is
// archived or deleted follows the child's own declaration, not this verb.
type RemoveGroupRoleCommand struct {
	pipeline.CommandWithBodyIDBase
	GroupRoleID string
}

func (cmd *RemoveGroupRoleCommand) ApplyTo(ctx *configuration.AppContext, e *appdomain.Group) error {
	e.RemoveGroupRoleByID(cmd.GroupRoleID)

	// Identity-derived state the rules read. It is never persisted.
	if id := ctx.Identity(); id != nil {
		e.RequestingIdentityPresent = true
		e.RequestingTenant = id.TenantID()
		// The super-admin grant, not asked through HasPermission: that
		// method panics on a wildcard, since the CLAIM wildcards and the
		// question does not. The framework gives the wildcard its own
		// question, and this is it.
		e.RequestingMayCrossScope = id.IsSuperAdmin()
	}
	return nil
}

// FromEntity projects nothing: the entry RemoveGroupRoleCommand named is
// gone, so the endpoint answers 204 — and the framework's NoBody projection
// is paired with a None on this side.
func (cmd *RemoveGroupRoleCommand) FromEntity(_ *configuration.AppContext, _ *appdomain.Group) (fwresults.None, error) {
	return fwresults.None{}, nil
}

// projectOneGroupRole renders one stored entry.
//
// Its plural twin projects the whole collection for the root's own verbs; this
// one exists because a per-entry verb answers with the entry it touched, not
// with everything around it.
func projectOneGroupRole(item aggregatevos.GroupRole) GroupRoleResult {
	return GroupRoleResult{
		ID:     item.GetID(),
		RoleID: item.RoleID,
	}
}
