// Code generated by omnicore-gen. DO NOT EDIT.
//
// Tests for the command mappers.
//
// entity:     Group
// spec:       specs/omnicore-gen/group.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-28
// checksum:   sha256:84f23347a3fc85e5875b470ff414cc30e7af46bb9e034084eacf3b5c12acc646
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package commands

import (
	"testing"

	"github.com/ClaudioSchirmer/authcore/internal/application/dtos"
	appdomain "github.com/ClaudioSchirmer/authcore/internal/domain"
	"github.com/ClaudioSchirmer/authcore/internal/domain/aggregatevos"
	"github.com/ClaudioSchirmer/omnicore/application/configuration"
	"github.com/ClaudioSchirmer/omnicore/domain"
)

// The insert mapper must carry every field through.
//
// A field silently dropped here is the quietest bug in the stack: the write
// succeeds and the value is simply not there.
func TestInsertGroupMapsEveryField(t *testing.T) {
	ctx := &configuration.AppContext{}
	// A request has a caller. With no identity the mappers' identity feed is
	// skipped entirely, and what a scoped write is checked against is exactly
	// what the feed carries.
	ctx.SetIdentity(&configuration.Identity{
		Claims: map[string]any{
			"tenant_id": "0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410",
		},
	})
	c := &InsertGroupCommand{
		TenantID:    domain.NewID("0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410"),
		Key:         "engineering",
		Name:        "Engineering",
		Description: "Everyone in the product engineering org: read access to the tenant registry and the permission catalog, plus deploy rights.",
		Roles: []dtos.GroupRoleInput{{
			RoleID: domain.NewID("0198f3e0-9c25-7a1f-b73d-5e08c4a29f61"),
		}},
	}
	e, err := c.ToEntity(ctx)
	if err != nil {
		t.Fatalf("ToEntity: %v", err)
	}
	if e.RequestingTenant != "0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410" {
		t.Errorf("the caller's scope did not reach the entity (%q) — a write outside it could not be refused", e.RequestingTenant)
	}
	if e.TenantID != domain.NewID("0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410") {
		t.Errorf("TenantID did not survive the mapper")
	}
	if e.Key.Value() != "engineering" {
		t.Errorf("Key did not survive the mapper")
	}
	if e.Name.Value() != "Engineering" {
		t.Errorf("Name did not survive the mapper")
	}
	if e.Description.Value() != "Everyone in the product engineering org: read access to the tenant registry and the permission catalog, plus deploy rights." {
		t.Errorf("Description did not survive the mapper")
	}
}

// What was written reads back through the result mapper.
//
// The round trip is the point: the same command builds the entity and then
// projects it, so a field that survives one direction and not the other fails
// here rather than in a caller's response.
//
// A SHARED-BASE role reaches the entity through ApplyTo rather than ToEntity
// — its insert is an upsert, because another role may already have created
// the identity — and this test used to skip that shape entirely. The result
// mapper is the same mapper either way, and on a role it is also where a
// computed field's derivation is called, so skipping it left the one seat
// whose body is hand-written with no generated coverage at all.
func TestInsertGroupCommandResultCarriesWhatWasWritten(t *testing.T) {
	ctx := &configuration.AppContext{}
	c := &InsertGroupCommand{
		TenantID:    domain.NewID("0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410"),
		Key:         "engineering",
		Name:        "Engineering",
		Description: "Everyone in the product engineering org: read access to the tenant registry and the permission catalog, plus deploy rights.",
		Roles: []dtos.GroupRoleInput{{
			RoleID: domain.NewID("0198f3e0-9c25-7a1f-b73d-5e08c4a29f61"),
		}},
	}
	e, err := c.ToEntity(ctx)
	if err != nil {
		t.Fatalf("ToEntity: %v", err)
	}
	e.SetID(domain.NewRandomID())
	res, err := c.FromEntity(ctx, e)
	if err != nil {
		t.Fatalf("FromEntity: %v", err)
	}
	if res.TenantID != domain.NewID("0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410") {
		t.Errorf("TenantID did not reach the result")
	}
	if res.Key != "engineering" {
		t.Errorf("Key did not reach the result")
	}
	if res.Name != "Engineering" {
		t.Errorf("Name did not reach the result")
	}
	if res.Description != "Everyone in the product engineering org: read access to the tenant registry and the permission catalog, plus deploy rights." {
		t.Errorf("Description did not reach the result")
	}
	if len(res.Roles) != 1 {
		t.Errorf("the Roles collection reached the result with %d entries, want 1", len(res.Roles))
	}
}

// A partial update must leave absent fields alone.
//
// This is the whole contract of the verb: sending nothing must not blank
// anything out.
func TestPatchGroupLeavesAbsentFieldsAlone(t *testing.T) {
	ctx := &configuration.AppContext{}
	// A request has a caller. With no identity the mappers' identity feed is
	// skipped entirely, and what a scoped write is checked against is exactly
	// what the feed carries.
	ctx.SetIdentity(&configuration.Identity{
		Claims: map[string]any{
			"tenant_id": "0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410",
		},
	})
	e := &appdomain.Group{}
	orig := domain.NewID("0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410")
	e.TenantID = orig
	c := &PatchGroupCommand{} // nothing sent
	if err := c.ApplyPartiallyTo(ctx, e); err != nil {
		t.Fatalf("ApplyPartiallyTo: %v", err)
	}
	if e.TenantID != orig {
		t.Error("an absent field was overwritten")
	}
}

// A partial update applies every field it DOES carry.
//
// The twin of the case above: leaving absent fields alone is only half the
// contract, and a mapper that leaves everything alone passes that half.
func TestPatchGroupAppliesWhatItCarries(t *testing.T) {
	ctx := &configuration.AppContext{}
	// A request has a caller. With no identity the mappers' identity feed is
	// skipped entirely, and what a scoped write is checked against is exactly
	// what the feed carries.
	ctx.SetIdentity(&configuration.Identity{
		Claims: map[string]any{
			"tenant_id": "0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410",
		},
	})
	e := &appdomain.Group{}
	c := &PatchGroupCommand{
		TenantID: func() *domain.ID { v := domain.ID(domain.NewID("0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410")); return &v }(),
		Key:      func() *string { v := string("engineering"); return &v }(),
		Name:     func() *string { v := string("Engineering"); return &v }(),
		Description: func() *string {
			v := string("Everyone in the product engineering org: read access to the tenant registry and the permission catalog, plus deploy rights.")
			return &v
		}(),
	}
	if err := c.ApplyPartiallyTo(ctx, e); err != nil {
		t.Fatalf("ApplyPartiallyTo: %v", err)
	}
	if e.TenantID != domain.NewID("0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410") {
		t.Errorf("TenantID was sent and not applied")
	}
	if e.Key.Value() != "engineering" {
		t.Errorf("Key was sent and not applied")
	}
	if e.Name.Value() != "Engineering" {
		t.Errorf("Name was sent and not applied")
	}
	if e.Description.Value() != "Everyone in the product engineering org: read access to the tenant registry and the permission catalog, plus deploy rights." {
		t.Errorf("Description was sent and not applied")
	}
}

// What a partial update applied reads back through the result mapper.
//
// The verb's own test proves the fields reach the ENTITY. This one proves they
// reach the CALLER, which is a separate mapper with its own way of dropping
// one.
func TestPatchGroupCommandResultCarriesWhatWasApplied(t *testing.T) {
	ctx := &configuration.AppContext{}
	e := &appdomain.Group{}
	c := &PatchGroupCommand{
		TenantID: func() *domain.ID { v := domain.ID(domain.NewID("0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410")); return &v }(),
		Key:      func() *string { v := string("engineering"); return &v }(),
		Name:     func() *string { v := string("Engineering"); return &v }(),
		Description: func() *string {
			v := string("Everyone in the product engineering org: read access to the tenant registry and the permission catalog, plus deploy rights.")
			return &v
		}(),
	}
	if err := c.ApplyPartiallyTo(ctx, e); err != nil {
		t.Fatalf("ApplyPartiallyTo: %v", err)
	}
	e.SetID(domain.NewRandomID())
	res, err := c.FromEntity(ctx, e)
	if err != nil {
		t.Fatalf("FromEntity: %v", err)
	}
	if res.TenantID != domain.NewID("0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410") {
		t.Errorf("TenantID was applied and did not reach the result")
	}
	if res.Key != "engineering" {
		t.Errorf("Key was applied and did not reach the result")
	}
	if res.Name != "Engineering" {
		t.Errorf("Name was applied and did not reach the result")
	}
	if res.Description != "Everyone in the product engineering org: read access to the tenant registry and the permission catalog, plus deploy rights." {
		t.Errorf("Description was applied and did not reach the result")
	}
}

// ArchiveGroupCommand must apply cleanly to a well-formed entity.
//
// Archive and unarchive carry no body, so what is under test is that the
// mapper leaves the entity alone and reports no error — a mapper that errors
// here turns a legitimate verb into a 400.
func TestArchiveGroupCommandApplies(t *testing.T) {
	ctx := &configuration.AppContext{}
	// A request has a caller. With no identity the mappers' identity feed is
	// skipped entirely, and what a scoped write is checked against is exactly
	// what the feed carries.
	ctx.SetIdentity(&configuration.Identity{
		Claims: map[string]any{
			"tenant_id": "0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410",
		},
	})
	e := &appdomain.Group{}
	// The result carries the id, and a verb that reaches this mapper has always
	// loaded the row first — so the entity under test has one too.
	e.SetID(domain.NewID("019ffd00-0000-7000-8000-000000000000"))
	c := &ArchiveGroupCommand{}
	if err := c.ApplyTo(ctx, e); err != nil {
		t.Fatalf("the mapper failed: %v", err)
	}
	if e.RequestingTenant != "0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410" {
		t.Errorf("the caller's scope did not reach the entity (%q) — a write outside it could not be refused", e.RequestingTenant)
	}
	if _, err := c.FromEntity(ctx, e); err != nil {
		t.Errorf("projecting the result failed: %v", err)
	}
}

// AddGroupRoleCommand appends the entry and projects it back with the id the
// server minted for it — the id the caller addresses it by afterwards.
func TestAddGroupRoleCommand_AppliesAndProjects(t *testing.T) {
	ctx := &configuration.AppContext{}
	// A request has a caller. With no identity the mappers' identity feed is
	// skipped entirely, and what a scoped write is checked against is exactly
	// what the feed carries.
	ctx.SetIdentity(&configuration.Identity{
		Claims: map[string]any{
			"tenant_id": "0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410",
		},
	})
	e := &appdomain.Group{}
	e.SetID(domain.NewID("019ffd00-0000-7000-8000-000000000000"))
	cmd := &AddGroupRoleCommand{RoleID: domain.NewID("0198f3e0-9c25-7a1f-b73d-5e08c4a29f61")}
	if err := cmd.ApplyTo(ctx, e); err != nil {
		t.Fatalf("ApplyTo: %v", err)
	}
	if e.RequestingTenant != "0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410" {
		t.Errorf("the caller's scope did not reach the entity (%q) — a write outside it could not be refused", e.RequestingTenant)
	}
	out, err := cmd.FromEntity(ctx, e)
	if err != nil {
		t.Fatalf("FromEntity: %v", err)
	}
	if out.GroupID.Value() != "019ffd00-0000-7000-8000-000000000000" {
		t.Error("the result does not carry the owner id")
	}
	if out.GroupRole.RoleID != domain.NewID("0198f3e0-9c25-7a1f-b73d-5e08c4a29f61") {
		t.Errorf("the projected entry lost RoleID")
	}
}

// RemoveGroupRoleCommand takes the named entry out of the collection.
//
// It projects NOTHING — the endpoint answers 204 — so the only thing worth
// asserting is the effect: the entry the caller addressed is no longer among
// the current items. A command that silently matched nothing would still
// answer 204, and this is what tells the two apart.
func TestRemoveGroupRoleCommand_TakesTheEntryOut(t *testing.T) {
	ctx := &configuration.AppContext{}
	// A request has a caller. With no identity the mappers' identity feed is
	// skipped entirely, and what a scoped write is checked against is exactly
	// what the feed carries.
	ctx.SetIdentity(&configuration.Identity{
		Claims: map[string]any{
			"tenant_id": "0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410",
		},
	})
	e := &appdomain.Group{}
	e.SetID(domain.NewID("019ffd00-0000-7000-8000-000000000000"))
	seeded := domain.WithID(
		dtos.GroupRoleInput{RoleID: domain.NewID("0198f3e0-9c25-7a1f-b73d-5e08c4a29f61")}.ToGroupRole(),
		domain.NewID("019ffd00-0000-7000-8000-0000000000a1"),
	)
	e.AggregateConstructor([]domain.AggregateValueObject{seeded})

	cmd := &RemoveGroupRoleCommand{GroupRoleID: "019ffd00-0000-7000-8000-0000000000a1"}
	if err := cmd.ApplyTo(ctx, e); err != nil {
		t.Fatalf("ApplyTo: %v", err)
	}
	if e.RequestingTenant != "0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410" {
		t.Errorf("the caller's scope did not reach the entity (%q) — a write outside it could not be refused", e.RequestingTenant)
	}
	for _, item := range domain.GetCurrentItemsOf[aggregatevos.GroupRole](e.GetAggregateRoot()) {
		if item.GetID().Value() == "019ffd00-0000-7000-8000-0000000000a1" {
			t.Error("the entry the command named is still in the collection")
		}
	}
	if _, err := cmd.FromEntity(ctx, e); err != nil {
		t.Fatalf("FromEntity: %v", err)
	}
}
