// Code generated by omnicore-gen. DO NOT EDIT.
//
// The insert command and result.
//
// entity:     Role
// spec:       specs/omnicore-gen/role.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-29
// checksum:   sha256:4fa4f54d8a2c32d3a32c6d77ba0b22defc40750d4231e8d430ad4384b3c48d1d
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package commands

import (
	"github.com/ClaudioSchirmer/omnicore/application/configuration"
	"github.com/ClaudioSchirmer/omnicore/application/pipeline"
	"github.com/ClaudioSchirmer/omnicore/domain"

	appdomain "github.com/ClaudioSchirmer/authcore/internal/domain"
	"github.com/ClaudioSchirmer/authcore/internal/domain/vos"

	"github.com/ClaudioSchirmer/authcore/internal/application/dtos"
)

// InsertRoleCommand carries the writable fields of the request.
type InsertRoleCommand struct {
	pipeline.CommandWithBodyBase
	Key         string
	Name        string
	Description string
	TenantID    *domain.ID
	Permissions []dtos.RolePermissionInput
}

// ToEntity builds the aggregate the framework will validate and persist.
func (c *InsertRoleCommand) ToEntity(ctx *configuration.AppContext) (*appdomain.Role, error) {
	e := &appdomain.Role{}
	e.Key = vos.RoleKey(c.Key)
	e.Name = vos.DisplayName(c.Name)
	e.Description = vos.Description(c.Description)
	for _, item := range c.Permissions {
		e.AddRolePermission(item.ToRolePermission())
	}

	// Filled from the caller's identity, never from the request: these fields
	// are not part of any write DTO. Only an insert sets them.
	if id := ctx.Identity(); id != nil {
		if raw, ok := id.Claims["tenant_id"].(string); ok {
			e.TenantID = domain.NewID(raw)
		}
	}

	// …unless the caller stated the tenant themselves. Absent means
	// "mine", which the line above already wrote. Present, it is applied
	// HERE and judged in BuildRules: a caller who may not cross the row
	// scope meets the same refusal a write into a foreign tenant meets,
	// instead of having the value quietly replaced by their own.
	if c.TenantID != nil {
		e.TenantID = *c.TenantID
	}

	// Identity-derived state the rules read. It is never persisted.
	if id := ctx.Identity(); id != nil {
		e.RequestingIdentityPresent = true
		e.RequestingTenant = id.TenantID()
		// The super-admin grant, not asked through HasPermission: that
		// method panics on a wildcard, since the CLAIM wildcards and the
		// question does not. The framework gives the wildcard its own
		// question, and this is it.
		e.RequestingMayCrossScope = id.IsSuperAdmin()
	}
	return e, nil
}

// InsertRoleResult is the write response, projected from the entity.
type InsertRoleResult struct {
	ID          domain.ID
	TenantID    domain.ID
	Key         string
	Name        string
	Description string
	Permissions []RolePermissionResult
}

// FromEntity projects the aggregate AFTER it was validated and written.
//
// It reads the entity, never the command: the domain may have normalised or
// defaulted a value, and echoing the input back would hide that from the
// caller.
func (c *InsertRoleCommand) FromEntity(_ *configuration.AppContext, e *appdomain.Role) (InsertRoleResult, error) {
	return InsertRoleResult{
		ID:          *e.GetID(),
		TenantID:    e.TenantID,
		Key:         e.Key.Value(),
		Name:        e.Name.Value(),
		Description: e.Description.Value(),
		Permissions: projectRolePermissions(e),
	}, nil
}
