// Code generated by omnicore-gen. DO NOT EDIT.
//
// Tests for insert_user_command.go.
//
// entity:     User
// spec:       specs/omnicore-gen/user.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-07
// checksum:   sha256:6cc6b5f24ef28ac57714742faf4f26589e1f62f95359ffb72e4adcaed51b4d19
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package commands

import (
	"testing"

	"github.com/ClaudioSchirmer/omnicore/application/configuration"
	"github.com/ClaudioSchirmer/omnicore/domain"

	"github.com/ClaudioSchirmer/authcore/internal/application/dtos"
)

// The insert mapper must carry every field through.
//
// A field silently dropped here is the quietest bug in the stack: the write
// succeeds and the value is simply not there.
func TestInsertUserMapsEveryField(t *testing.T) {
	ctx := &configuration.AppContext{}
	// A request has a caller. With no identity the mappers' identity feed is
	// skipped entirely, and what a scoped write is checked against is exactly
	// what the feed carries.
	ctx.SetIdentity(&configuration.Identity{
		Subject: "caller",
		Claims: map[string]any{
			"tenant_id": "0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410",
		},
	})
	c := &InsertUserCommand{
		GivenName:            "Maria",
		FamilyName:           "Souza Lima",
		Email:                "maria@acme.com",
		Status:               "active",
		Password:             "Str0ng!Passphrase",
		PasswordConfirmation: "Str0ng!Passphrase",
		TenantID:             func() *domain.ID { v := domain.ID(domain.NewID("0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410")); return &v }(),
		Groups: []dtos.UserGroupInput{{
			GroupID: domain.NewID("0198f3e0-9c25-7a1f-b73d-5e08c4a29f61"),
		}},
		Roles: []dtos.UserRoleInput{{
			RoleID: domain.NewID("0198f3e0-1a44-7bb2-9c31-77c0d5e1b904"),
		}},
		Claims: []dtos.UserClaimInput{{
			ClaimID: domain.NewID("0198f3e0-7b31-7c02-8a55-1f9d2e6b4c17"),
			Value:   "1000",
		}},
	}
	e, err := c.ToEntity(ctx)
	if err != nil {
		t.Fatalf("ToEntity: %v", err)
	}
	if e.RequestingTenant != "0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410" {
		t.Errorf("the caller's TenantID scope did not reach the entity (%q) — a write outside it could not be refused", e.RequestingTenant)
	}
	if e.RequestingUserID != "caller" {
		t.Errorf("the caller's subject did not reach the entity (%q) — every rule reading it judges the wrong caller", e.RequestingUserID)
	}
	if e.Name.Given != "Maria" {
		t.Errorf("GivenName did not survive the mapper")
	}
	if e.Name.Family != "Souza Lima" {
		t.Errorf("FamilyName did not survive the mapper")
	}
	if e.Email.Value() != "maria@acme.com" {
		t.Errorf("Email did not survive the mapper")
	}
	if e.Status.Value() != "active" {
		t.Errorf("Status did not survive the mapper")
	}
	if e.Password.Value() != "Str0ng!Passphrase" {
		t.Errorf("Password did not survive the mapper")
	}
	if e.PasswordConfirmation != "Str0ng!Passphrase" {
		t.Errorf("PasswordConfirmation did not survive the mapper")
	}
	if e.TenantID != domain.NewID("0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410") {
		t.Errorf("TenantID did not survive the mapper")
	}
}

// What was written reads back through the result mapper.
//
// The round trip is the point: the same command builds the entity and then
// projects it, so a field that survives one direction and not the other fails
// here rather than in a caller's response.
//
// A SHARED-BASE role reaches the entity through ApplyTo rather than ToEntity
// — its insert is an upsert, because another role may already have created
// the identity — and this test used to skip that shape entirely. The result
// mapper is the same mapper either way, and on a role it is also where a
// computed field's derivation is called, so skipping it left the one seat
// whose body is hand-written with no generated coverage at all.
func TestInsertUserCommandResultCarriesWhatWasWritten(t *testing.T) {
	ctx := &configuration.AppContext{}
	c := &InsertUserCommand{
		GivenName:            "Maria",
		FamilyName:           "Souza Lima",
		Email:                "maria@acme.com",
		Status:               "active",
		Password:             "Str0ng!Passphrase",
		PasswordConfirmation: "Str0ng!Passphrase",
		TenantID:             func() *domain.ID { v := domain.ID(domain.NewID("0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410")); return &v }(),
		Groups: []dtos.UserGroupInput{{
			GroupID: domain.NewID("0198f3e0-9c25-7a1f-b73d-5e08c4a29f61"),
		}},
		Roles: []dtos.UserRoleInput{{
			RoleID: domain.NewID("0198f3e0-1a44-7bb2-9c31-77c0d5e1b904"),
		}},
		Claims: []dtos.UserClaimInput{{
			ClaimID: domain.NewID("0198f3e0-7b31-7c02-8a55-1f9d2e6b4c17"),
			Value:   "1000",
		}},
	}
	e, err := c.ToEntity(ctx)
	if err != nil {
		t.Fatalf("ToEntity: %v", err)
	}
	e.SetID(domain.NewRandomID())
	res, err := c.FromEntity(ctx, e)
	if err != nil {
		t.Fatalf("FromEntity: %v", err)
	}
	if res.GivenName != "Maria" {
		t.Errorf("GivenName did not reach the result")
	}
	if res.FamilyName != "Souza Lima" {
		t.Errorf("FamilyName did not reach the result")
	}
	if res.Email != "maria@acme.com" {
		t.Errorf("Email did not reach the result")
	}
	if res.Status != "active" {
		t.Errorf("Status did not reach the result")
	}
	if res.TenantID != domain.NewID("0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410") {
		t.Errorf("TenantID did not reach the result")
	}
	if len(res.Groups) != 1 {
		t.Errorf("the Groups collection reached the result with %d entries, want 1", len(res.Groups))
	}
	if len(res.Roles) != 1 {
		t.Errorf("the Roles collection reached the result with %d entries, want 1", len(res.Roles))
	}
	if len(res.Claims) != 1 {
		t.Errorf("the Claims collection reached the result with %d entries, want 1", len(res.Claims))
	}
}
