// Code generated by omnicore-gen. DO NOT EDIT.
//
// Tests for patch_client_command.go.
//
// entity:     Client
// spec:       specs/omnicore-gen/client.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-01
// checksum:   sha256:f44b42c6f748b254011af97e85fe83ea2229323c5fb3a3ef21874ef3e01f260f
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package commands

import (
	"testing"

	appdomain "github.com/ClaudioSchirmer/authcore/internal/domain"
	"github.com/ClaudioSchirmer/omnicore/application/configuration"
	"github.com/ClaudioSchirmer/omnicore/domain"

	"github.com/ClaudioSchirmer/authcore/internal/domain/vos"
)

// A partial update must leave absent fields alone.
//
// This is the whole contract of the verb: sending nothing must not blank
// anything out.
func TestPatchClientLeavesAbsentFieldsAlone(t *testing.T) {
	ctx := &configuration.AppContext{}
	// A request has a caller. With no identity the mappers' identity feed is
	// skipped entirely, and what a scoped write is checked against is exactly
	// what the feed carries.
	ctx.SetIdentity(&configuration.Identity{
		Subject: "0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410",
		Claims: map[string]any{
			"identity_kind": "someone@example.test",
			"tenant_id":     "0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410",
		},
	})
	e := &appdomain.Client{}
	orig := vos.DisplayName("Billing integration")
	e.Name = orig
	c := &PatchClientCommand{} // nothing sent
	if err := c.ApplyPartiallyTo(ctx, e); err != nil {
		t.Fatalf("ApplyPartiallyTo: %v", err)
	}
	if e.Name != orig {
		t.Error("an absent field was overwritten")
	}
}

// A partial update applies every field it DOES carry.
//
// The twin of the case above: leaving absent fields alone is only half the
// contract, and a mapper that leaves everything alone passes that half.
func TestPatchClientAppliesWhatItCarries(t *testing.T) {
	ctx := &configuration.AppContext{}
	// A request has a caller. With no identity the mappers' identity feed is
	// skipped entirely, and what a scoped write is checked against is exactly
	// what the feed carries.
	ctx.SetIdentity(&configuration.Identity{
		Subject: "0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410",
		Claims: map[string]any{
			"identity_kind": "someone@example.test",
			"tenant_id":     "0198f3c2-6b41-7c9e-9f2a-6d3b1e77a410",
		},
	})
	e := &appdomain.Client{}
	c := &PatchClientCommand{
		Name:        func() *string { v := string("Billing integration"); return &v }(),
		Description: func() *string { v := string("Posts invoices from the billing system into the ledger."); return &v }(),
		Status:      func() *string { v := string("active"); return &v }(),
	}
	if err := c.ApplyPartiallyTo(ctx, e); err != nil {
		t.Fatalf("ApplyPartiallyTo: %v", err)
	}
	if e.Name.Value() != "Billing integration" {
		t.Errorf("Name was sent and not applied")
	}
	if e.Description.Value() != "Posts invoices from the billing system into the ledger." {
		t.Errorf("Description was sent and not applied")
	}
	if e.Status.Value() != "active" {
		t.Errorf("Status was sent and not applied")
	}
}

// What a partial update applied reads back through the result mapper.
//
// The verb's own test proves the fields reach the ENTITY. This one proves they
// reach the CALLER, which is a separate mapper with its own way of dropping
// one.
func TestPatchClientCommandResultCarriesWhatWasApplied(t *testing.T) {
	ctx := &configuration.AppContext{}
	e := &appdomain.Client{}
	c := &PatchClientCommand{
		Name:        func() *string { v := string("Billing integration"); return &v }(),
		Description: func() *string { v := string("Posts invoices from the billing system into the ledger."); return &v }(),
		Status:      func() *string { v := string("active"); return &v }(),
	}
	if err := c.ApplyPartiallyTo(ctx, e); err != nil {
		t.Fatalf("ApplyPartiallyTo: %v", err)
	}
	e.SetID(domain.NewRandomID())
	res, err := c.FromEntity(ctx, e)
	if err != nil {
		t.Fatalf("FromEntity: %v", err)
	}
	if res.Name != "Billing integration" {
		t.Errorf("Name was applied and did not reach the result")
	}
	if res.Description != "Posts invoices from the billing system into the ledger." {
		t.Errorf("Description was applied and did not reach the result")
	}
	if res.Status != "active" {
		t.Errorf("Status was applied and did not reach the result")
	}
}
