// Code generated by omnicore-gen. DO NOT EDIT.
//
// The patch command and result.
//
// entity:     Permission
// spec:       specs/omnicore-gen/permission.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-03
// checksum:   sha256:e4e19990a3152303c22e9857ea96375f9ce61d5126dc6dfc271d2c0601b24d09
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package commands

import (
	"github.com/ClaudioSchirmer/omnicore/application/configuration"
	"github.com/ClaudioSchirmer/omnicore/application/pipeline"
	"github.com/ClaudioSchirmer/omnicore/domain"

	appdomain "github.com/ClaudioSchirmer/authcore/internal/domain"
	"github.com/ClaudioSchirmer/authcore/internal/domain/vos"

	qryutils "github.com/ClaudioSchirmer/authcore/internal/application/queries/utils"
)

// PatchPermissionCommand carries the writable fields of the request.
//
// Every field is a pointer because a partial update is tri-state: a nil field
// means the caller did not send it, which is different from sending an empty
// value.
type PatchPermissionCommand struct {
	pipeline.CommandWithBodyIDBase
	Description *string
}

// ApplyPartiallyTo assigns only what the caller sent.
//
// Each field is guarded on nil, which is what makes a partial update partial.
// Note the consequence: this verb can never set a value back to null, because
// an absent field and an explicit null are indistinguishable here.
func (c *PatchPermissionCommand) ApplyPartiallyTo(ctx *configuration.AppContext, e *appdomain.Permission) error {
	if c.Description != nil {
		e.Description = vos.Description(*c.Description)
	}
	return nil
}

// PatchPermissionResult is the write response, projected from the entity.
type PatchPermissionResult struct {
	ID          domain.ID
	Resource    string
	Action      string
	Description string
	// Permission is COMPUTED: no column backs it, and FromEntity fills it
	// from Resource+Action.
	Permission string
}

// FromEntity projects the aggregate AFTER it was validated and written.
//
// It reads the entity, never the command: the domain may have normalised or
// defaulted a value, and echoing the input back would hide that from the
// caller.
//
// The computed fields are derived through the SAME function the reads call, in
// internal/application/queries. Deriving them a second time here is how one
// question grows two answers.
func (c *PatchPermissionCommand) FromEntity(ctx *configuration.AppContext, e *appdomain.Permission) (PatchPermissionResult, error) {
	out := PatchPermissionResult{
		ID:          *e.GetID(),
		Description: e.Description.Value(),
	}
	out.Resource = e.Permission.Resource
	out.Action = e.Permission.Action
	{
		v, err := qryutils.ComputePermissionPermission(ctx, e.Permission.Resource, e.Permission.Action)
		if err != nil {
			return out, err
		}
		out.Permission = v
	}
	return out, nil
}
