// Code generated by omnicore-gen. DO NOT EDIT.
//
// Tests for the command mappers.
//
// entity:     Role
// spec:       specs/omnicore-gen/role.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-24
// checksum:   sha256:d585fa1e87af8263d881405da2297f763af526f2cc2234880067606ec8299319
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package commands

import (
	"testing"

	"github.com/ClaudioSchirmer/authcore/internal/application/dtos"
	appdomain "github.com/ClaudioSchirmer/authcore/internal/domain"
	"github.com/ClaudioSchirmer/omnicore/application/configuration"
	"github.com/ClaudioSchirmer/omnicore/domain"
)

// The insert mapper must carry every field through.
//
// A field silently dropped here is the quietest bug in the stack: the write
// succeeds and the value is simply not there.
func TestInsertRoleMapsEveryField(t *testing.T) {
	ctx := &configuration.AppContext{}
	// A request has a caller. With no identity the mappers' identity feed is
	// skipped entirely, and what a scoped write is checked against is exactly
	// what the feed carries.
	ctx.SetIdentity(&configuration.Identity{
		Claims: map[string]any{
			"tenant_id": "a3f1c07e-2b58-5d94-8e61-4f2093ab77d5",
		},
	})
	c := &InsertRoleCommand{
		TenantID:    domain.NewID("a3f1c07e-2b58-5d94-8e61-4f2093ab77d5"),
		Key:         "billing-manager",
		Name:        "Billing Manager",
		Description: "Grants read access to the tenant registry and the permission catalog, without any write verb.",
		Permissions: []dtos.RolePermissionInput{{
			PermissionID: domain.NewID("9f14b0a2-6d38-4c5e-b7a1-2e0c5d81f4a3"),
		}},
	}
	e, err := c.ToEntity(ctx)
	if err != nil {
		t.Fatalf("ToEntity: %v", err)
	}
	if e.RequestingTenant != "a3f1c07e-2b58-5d94-8e61-4f2093ab77d5" {
		t.Errorf("the caller's scope did not reach the entity (%q) — a write outside it could not be refused", e.RequestingTenant)
	}
	if e.TenantID != domain.NewID("a3f1c07e-2b58-5d94-8e61-4f2093ab77d5") {
		t.Errorf("TenantID did not survive the mapper")
	}
	if e.Key.Value() != "billing-manager" {
		t.Errorf("Key did not survive the mapper")
	}
	if e.Name.Value() != "Billing Manager" {
		t.Errorf("Name did not survive the mapper")
	}
	if e.Description.Value() != "Grants read access to the tenant registry and the permission catalog, without any write verb." {
		t.Errorf("Description did not survive the mapper")
	}
}

// What was written reads back through the result mapper.
//
// The round trip is the point: the same command builds the entity and then
// projects it, so a field that survives one direction and not the other fails
// here rather than in a caller's response.
//
// A SHARED-BASE role reaches the entity through ApplyTo rather than ToEntity
// — its insert is an upsert, because another role may already have created
// the identity — and this test used to skip that shape entirely. The result
// mapper is the same mapper either way, and on a role it is also where a
// computed field's derivation is called, so skipping it left the one seat
// whose body is hand-written with no generated coverage at all.
func TestInsertRoleCommandResultCarriesWhatWasWritten(t *testing.T) {
	ctx := &configuration.AppContext{}
	c := &InsertRoleCommand{
		TenantID:    domain.NewID("a3f1c07e-2b58-5d94-8e61-4f2093ab77d5"),
		Key:         "billing-manager",
		Name:        "Billing Manager",
		Description: "Grants read access to the tenant registry and the permission catalog, without any write verb.",
		Permissions: []dtos.RolePermissionInput{{
			PermissionID: domain.NewID("9f14b0a2-6d38-4c5e-b7a1-2e0c5d81f4a3"),
		}},
	}
	e, err := c.ToEntity(ctx)
	if err != nil {
		t.Fatalf("ToEntity: %v", err)
	}
	e.SetID(domain.NewRandomID())
	res, err := c.FromEntity(ctx, e)
	if err != nil {
		t.Fatalf("FromEntity: %v", err)
	}
	if res.TenantID != domain.NewID("a3f1c07e-2b58-5d94-8e61-4f2093ab77d5") {
		t.Errorf("TenantID did not reach the result")
	}
	if res.Key != "billing-manager" {
		t.Errorf("Key did not reach the result")
	}
	if res.Name != "Billing Manager" {
		t.Errorf("Name did not reach the result")
	}
	if res.Description != "Grants read access to the tenant registry and the permission catalog, without any write verb." {
		t.Errorf("Description did not reach the result")
	}
	if len(res.Permissions) != 1 {
		t.Errorf("the Permissions collection reached the result with %d entries, want 1", len(res.Permissions))
	}
}

// A partial update must leave absent fields alone.
//
// This is the whole contract of the verb: sending nothing must not blank
// anything out.
func TestPatchRoleLeavesAbsentFieldsAlone(t *testing.T) {
	ctx := &configuration.AppContext{}
	// A request has a caller. With no identity the mappers' identity feed is
	// skipped entirely, and what a scoped write is checked against is exactly
	// what the feed carries.
	ctx.SetIdentity(&configuration.Identity{
		Claims: map[string]any{
			"tenant_id": "a3f1c07e-2b58-5d94-8e61-4f2093ab77d5",
		},
	})
	e := &appdomain.Role{}
	orig := domain.NewID("a3f1c07e-2b58-5d94-8e61-4f2093ab77d5")
	e.TenantID = orig
	c := &PatchRoleCommand{} // nothing sent
	if err := c.ApplyPartiallyTo(ctx, e); err != nil {
		t.Fatalf("ApplyPartiallyTo: %v", err)
	}
	if e.TenantID != orig {
		t.Error("an absent field was overwritten")
	}
}

// A partial update applies every field it DOES carry.
//
// The twin of the case above: leaving absent fields alone is only half the
// contract, and a mapper that leaves everything alone passes that half.
func TestPatchRoleAppliesWhatItCarries(t *testing.T) {
	ctx := &configuration.AppContext{}
	// A request has a caller. With no identity the mappers' identity feed is
	// skipped entirely, and what a scoped write is checked against is exactly
	// what the feed carries.
	ctx.SetIdentity(&configuration.Identity{
		Claims: map[string]any{
			"tenant_id": "a3f1c07e-2b58-5d94-8e61-4f2093ab77d5",
		},
	})
	e := &appdomain.Role{}
	c := &PatchRoleCommand{
		TenantID: func() *domain.ID { v := domain.ID(domain.NewID("a3f1c07e-2b58-5d94-8e61-4f2093ab77d5")); return &v }(),
		Key:      func() *string { v := string("billing-manager"); return &v }(),
		Name:     func() *string { v := string("Billing Manager"); return &v }(),
		Description: func() *string {
			v := string("Grants read access to the tenant registry and the permission catalog, without any write verb.")
			return &v
		}(),
	}
	if err := c.ApplyPartiallyTo(ctx, e); err != nil {
		t.Fatalf("ApplyPartiallyTo: %v", err)
	}
	if e.TenantID != domain.NewID("a3f1c07e-2b58-5d94-8e61-4f2093ab77d5") {
		t.Errorf("TenantID was sent and not applied")
	}
	if e.Key.Value() != "billing-manager" {
		t.Errorf("Key was sent and not applied")
	}
	if e.Name.Value() != "Billing Manager" {
		t.Errorf("Name was sent and not applied")
	}
	if e.Description.Value() != "Grants read access to the tenant registry and the permission catalog, without any write verb." {
		t.Errorf("Description was sent and not applied")
	}
}

// What a partial update applied reads back through the result mapper.
//
// The verb's own test proves the fields reach the ENTITY. This one proves they
// reach the CALLER, which is a separate mapper with its own way of dropping
// one.
func TestPatchRoleCommandResultCarriesWhatWasApplied(t *testing.T) {
	ctx := &configuration.AppContext{}
	e := &appdomain.Role{}
	c := &PatchRoleCommand{
		TenantID: func() *domain.ID { v := domain.ID(domain.NewID("a3f1c07e-2b58-5d94-8e61-4f2093ab77d5")); return &v }(),
		Key:      func() *string { v := string("billing-manager"); return &v }(),
		Name:     func() *string { v := string("Billing Manager"); return &v }(),
		Description: func() *string {
			v := string("Grants read access to the tenant registry and the permission catalog, without any write verb.")
			return &v
		}(),
	}
	if err := c.ApplyPartiallyTo(ctx, e); err != nil {
		t.Fatalf("ApplyPartiallyTo: %v", err)
	}
	e.SetID(domain.NewRandomID())
	res, err := c.FromEntity(ctx, e)
	if err != nil {
		t.Fatalf("FromEntity: %v", err)
	}
	if res.TenantID != domain.NewID("a3f1c07e-2b58-5d94-8e61-4f2093ab77d5") {
		t.Errorf("TenantID was applied and did not reach the result")
	}
	if res.Key != "billing-manager" {
		t.Errorf("Key was applied and did not reach the result")
	}
	if res.Name != "Billing Manager" {
		t.Errorf("Name was applied and did not reach the result")
	}
	if res.Description != "Grants read access to the tenant registry and the permission catalog, without any write verb." {
		t.Errorf("Description was applied and did not reach the result")
	}
}

// ArchiveRoleCommand must apply cleanly to a well-formed entity.
//
// Archive and unarchive carry no body, so what is under test is that the
// mapper leaves the entity alone and reports no error — a mapper that errors
// here turns a legitimate verb into a 400.
func TestArchiveRoleCommandApplies(t *testing.T) {
	ctx := &configuration.AppContext{}
	// A request has a caller. With no identity the mappers' identity feed is
	// skipped entirely, and what a scoped write is checked against is exactly
	// what the feed carries.
	ctx.SetIdentity(&configuration.Identity{
		Claims: map[string]any{
			"tenant_id": "a3f1c07e-2b58-5d94-8e61-4f2093ab77d5",
		},
	})
	e := &appdomain.Role{}
	// The result carries the id, and a verb that reaches this mapper has always
	// loaded the row first — so the entity under test has one too.
	e.SetID(domain.NewID("019ffd00-0000-7000-8000-000000000000"))
	c := &ArchiveRoleCommand{}
	if err := c.ApplyTo(ctx, e); err != nil {
		t.Fatalf("the mapper failed: %v", err)
	}
	if e.RequestingTenant != "a3f1c07e-2b58-5d94-8e61-4f2093ab77d5" {
		t.Errorf("the caller's scope did not reach the entity (%q) — a write outside it could not be refused", e.RequestingTenant)
	}
	if _, err := c.FromEntity(ctx, e); err != nil {
		t.Errorf("projecting the result failed: %v", err)
	}
}

// AddRolePermissionCommand appends the entry and projects it back with the id
// the server minted for it — the id the caller addresses it by afterwards.
func TestAddRolePermissionCommand_AppliesAndProjects(t *testing.T) {
	ctx := &configuration.AppContext{}
	// A request has a caller. With no identity the mappers' identity feed is
	// skipped entirely, and what a scoped write is checked against is exactly
	// what the feed carries.
	ctx.SetIdentity(&configuration.Identity{
		Claims: map[string]any{
			"tenant_id": "a3f1c07e-2b58-5d94-8e61-4f2093ab77d5",
		},
	})
	e := &appdomain.Role{}
	e.SetID(domain.NewID("019ffd00-0000-7000-8000-000000000000"))
	cmd := &AddRolePermissionCommand{PermissionID: domain.NewID("9f14b0a2-6d38-4c5e-b7a1-2e0c5d81f4a3")}
	if err := cmd.ApplyTo(ctx, e); err != nil {
		t.Fatalf("ApplyTo: %v", err)
	}
	if e.RequestingTenant != "a3f1c07e-2b58-5d94-8e61-4f2093ab77d5" {
		t.Errorf("the caller's scope did not reach the entity (%q) — a write outside it could not be refused", e.RequestingTenant)
	}
	out, err := cmd.FromEntity(ctx, e)
	if err != nil {
		t.Fatalf("FromEntity: %v", err)
	}
	if out.RoleID.Value() != "019ffd00-0000-7000-8000-000000000000" {
		t.Error("the result does not carry the owner id")
	}
	if out.RolePermission.PermissionID != domain.NewID("9f14b0a2-6d38-4c5e-b7a1-2e0c5d81f4a3") {
		t.Errorf("the projected entry lost PermissionID")
	}
}

// RemoveRolePermissionCommand takes the entry out and answers with the owner
// alone — the entry it names is gone, so there is nothing to project.
func TestRemoveRolePermissionCommand_AppliesAndProjects(t *testing.T) {
	ctx := &configuration.AppContext{}
	// A request has a caller. With no identity the mappers' identity feed is
	// skipped entirely, and what a scoped write is checked against is exactly
	// what the feed carries.
	ctx.SetIdentity(&configuration.Identity{
		Claims: map[string]any{
			"tenant_id": "a3f1c07e-2b58-5d94-8e61-4f2093ab77d5",
		},
	})
	e := &appdomain.Role{}
	e.SetID(domain.NewID("019ffd00-0000-7000-8000-000000000000"))
	seeded := domain.WithID(
		dtos.RolePermissionInput{PermissionID: domain.NewID("9f14b0a2-6d38-4c5e-b7a1-2e0c5d81f4a3")}.ToRolePermission(),
		domain.NewID("019ffd00-0000-7000-8000-0000000000a1"),
	)
	e.AggregateConstructor([]domain.AggregateValueObject{seeded})

	cmd := &RemoveRolePermissionCommand{RolePermissionID: "019ffd00-0000-7000-8000-0000000000a1"}
	if err := cmd.ApplyTo(ctx, e); err != nil {
		t.Fatalf("ApplyTo: %v", err)
	}
	if e.RequestingTenant != "a3f1c07e-2b58-5d94-8e61-4f2093ab77d5" {
		t.Errorf("the caller's scope did not reach the entity (%q) — a write outside it could not be refused", e.RequestingTenant)
	}
	out, err := cmd.FromEntity(ctx, e)
	if err != nil {
		t.Fatalf("FromEntity: %v", err)
	}
	if out.RoleID.Value() != "019ffd00-0000-7000-8000-000000000000" {
		t.Error("the result does not carry the owner id")
	}
}
