// Code generated by omnicore-gen. DO NOT EDIT.
//
// Tests for the command mappers.
//
// entity:     Tenant
// spec:       specs/omnicore-gen/tenant.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-29
// checksum:   sha256:40ee81db6cfbc6ec96f8e55fc333c02c635cf66da592157b036242e5237c72e9
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package commands

import (
	"testing"

	appdomain "github.com/ClaudioSchirmer/authcore/internal/domain"
	"github.com/ClaudioSchirmer/authcore/internal/domain/vos"
	"github.com/ClaudioSchirmer/omnicore/application/configuration"
	"github.com/ClaudioSchirmer/omnicore/domain"
)

// The insert mapper must carry every field through.
//
// A field silently dropped here is the quietest bug in the stack: the write
// succeeds and the value is simply not there.
func TestInsertTenantMapsEveryField(t *testing.T) {
	ctx := &configuration.AppContext{}
	c := &InsertTenantCommand{
		Name:        "Acme Comércio e Serviços Ltda",
		Workspace:   "acme-comercio",
		Description: "Retail operations of the Acme group in Brazil.",
		Status:      "active",
	}
	e, err := c.ToEntity(ctx)
	if err != nil {
		t.Fatalf("ToEntity: %v", err)
	}
	if e.Name.Value() != "Acme Comércio e Serviços Ltda" {
		t.Errorf("Name did not survive the mapper")
	}
	if e.Workspace.Value() != "acme-comercio" {
		t.Errorf("Workspace did not survive the mapper")
	}
	if e.Description.Value() != "Retail operations of the Acme group in Brazil." {
		t.Errorf("Description did not survive the mapper")
	}
	if e.Status.Value() != "active" {
		t.Errorf("Status did not survive the mapper")
	}
}

// What was written reads back through the result mapper.
//
// The round trip is the point: the same command builds the entity and then
// projects it, so a field that survives one direction and not the other fails
// here rather than in a caller's response.
//
// A SHARED-BASE role reaches the entity through ApplyTo rather than ToEntity
// — its insert is an upsert, because another role may already have created
// the identity — and this test used to skip that shape entirely. The result
// mapper is the same mapper either way, and on a role it is also where a
// computed field's derivation is called, so skipping it left the one seat
// whose body is hand-written with no generated coverage at all.
func TestInsertTenantCommandResultCarriesWhatWasWritten(t *testing.T) {
	ctx := &configuration.AppContext{}
	c := &InsertTenantCommand{
		Name:        "Acme Comércio e Serviços Ltda",
		Workspace:   "acme-comercio",
		Description: "Retail operations of the Acme group in Brazil.",
		Status:      "active",
	}
	e, err := c.ToEntity(ctx)
	if err != nil {
		t.Fatalf("ToEntity: %v", err)
	}
	e.SetID(domain.NewRandomID())
	res, err := c.FromEntity(ctx, e)
	if err != nil {
		t.Fatalf("FromEntity: %v", err)
	}
	if res.Name != "Acme Comércio e Serviços Ltda" {
		t.Errorf("Name did not reach the result")
	}
	if res.Workspace != "acme-comercio" {
		t.Errorf("Workspace did not reach the result")
	}
	if res.Description != "Retail operations of the Acme group in Brazil." {
		t.Errorf("Description did not reach the result")
	}
	if res.Status != "active" {
		t.Errorf("Status did not reach the result")
	}
}

// A partial update must leave absent fields alone.
//
// This is the whole contract of the verb: sending nothing must not blank
// anything out.
func TestPatchTenantLeavesAbsentFieldsAlone(t *testing.T) {
	ctx := &configuration.AppContext{}
	e := &appdomain.Tenant{}
	orig := vos.DisplayName("Acme Comércio e Serviços Ltda")
	e.Name = orig
	c := &PatchTenantCommand{} // nothing sent
	if err := c.ApplyPartiallyTo(ctx, e); err != nil {
		t.Fatalf("ApplyPartiallyTo: %v", err)
	}
	if e.Name != orig {
		t.Error("an absent field was overwritten")
	}
}

// A partial update applies every field it DOES carry.
//
// The twin of the case above: leaving absent fields alone is only half the
// contract, and a mapper that leaves everything alone passes that half.
func TestPatchTenantAppliesWhatItCarries(t *testing.T) {
	ctx := &configuration.AppContext{}
	e := &appdomain.Tenant{}
	c := &PatchTenantCommand{
		Name:        func() *string { v := string("Acme Comércio e Serviços Ltda"); return &v }(),
		Description: func() *string { v := string("Retail operations of the Acme group in Brazil."); return &v }(),
		Status:      func() *string { v := string("active"); return &v }(),
	}
	if err := c.ApplyPartiallyTo(ctx, e); err != nil {
		t.Fatalf("ApplyPartiallyTo: %v", err)
	}
	if e.Name.Value() != "Acme Comércio e Serviços Ltda" {
		t.Errorf("Name was sent and not applied")
	}
	if e.Description.Value() != "Retail operations of the Acme group in Brazil." {
		t.Errorf("Description was sent and not applied")
	}
	if e.Status.Value() != "active" {
		t.Errorf("Status was sent and not applied")
	}
}

// What a partial update applied reads back through the result mapper.
//
// The verb's own test proves the fields reach the ENTITY. This one proves they
// reach the CALLER, which is a separate mapper with its own way of dropping
// one.
func TestPatchTenantCommandResultCarriesWhatWasApplied(t *testing.T) {
	ctx := &configuration.AppContext{}
	e := &appdomain.Tenant{}
	c := &PatchTenantCommand{
		Name:        func() *string { v := string("Acme Comércio e Serviços Ltda"); return &v }(),
		Description: func() *string { v := string("Retail operations of the Acme group in Brazil."); return &v }(),
		Status:      func() *string { v := string("active"); return &v }(),
	}
	if err := c.ApplyPartiallyTo(ctx, e); err != nil {
		t.Fatalf("ApplyPartiallyTo: %v", err)
	}
	e.SetID(domain.NewRandomID())
	res, err := c.FromEntity(ctx, e)
	if err != nil {
		t.Fatalf("FromEntity: %v", err)
	}
	if res.Name != "Acme Comércio e Serviços Ltda" {
		t.Errorf("Name was applied and did not reach the result")
	}
	if res.Description != "Retail operations of the Acme group in Brazil." {
		t.Errorf("Description was applied and did not reach the result")
	}
	if res.Status != "active" {
		t.Errorf("Status was applied and did not reach the result")
	}
}

// ArchiveTenantCommand must apply cleanly to a well-formed entity.
//
// Archive and unarchive carry no body, so what is under test is that the
// mapper leaves the entity alone and reports no error — a mapper that errors
// here turns a legitimate verb into a 400.
func TestArchiveTenantCommandApplies(t *testing.T) {
	ctx := &configuration.AppContext{}
	e := &appdomain.Tenant{}
	// The result carries the id, and a verb that reaches this mapper has always
	// loaded the row first — so the entity under test has one too.
	e.SetID(domain.NewID("019ffd00-0000-7000-8000-000000000000"))
	c := &ArchiveTenantCommand{}
	if err := c.ApplyTo(ctx, e); err != nil {
		t.Fatalf("the mapper failed: %v", err)
	}
	if _, err := c.FromEntity(ctx, e); err != nil {
		t.Errorf("projecting the result failed: %v", err)
	}
}

// UnarchiveTenantCommand must apply cleanly to a well-formed entity.
//
// Archive and unarchive carry no body, so what is under test is that the
// mapper leaves the entity alone and reports no error — a mapper that errors
// here turns a legitimate verb into a 400.
func TestUnarchiveTenantCommandApplies(t *testing.T) {
	ctx := &configuration.AppContext{}
	e := &appdomain.Tenant{}
	// The result carries the id, and a verb that reaches this mapper has always
	// loaded the row first — so the entity under test has one too.
	e.SetID(domain.NewID("019ffd00-0000-7000-8000-000000000000"))
	c := &UnarchiveTenantCommand{}
	if err := c.ApplyTo(ctx, e); err != nil {
		t.Fatalf("the mapper failed: %v", err)
	}
	if _, err := c.FromEntity(ctx, e); err != nil {
		t.Errorf("projecting the result failed: %v", err)
	}
}
