// Code generated by omnicore-gen. DO NOT EDIT.
//
// The per-entry commands for user_groups.
//
// entity:     User
// spec:       specs/omnicore-gen/user.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-08-28
// checksum:   sha256:c80e7d3a742cc51cfd14f091836556c96b68c4c550ab7f0bb3bd48c3452b4a10
//
// The checksum covers this file with the checksum line itself blanked. The
// generator recomputes it before every write: if it does not match, the file
// was changed by hand and the run REFUSES it — your change is neither
// overwritten nor updated. Change the spec and regenerate instead; to keep a
// deliberate edit, run omnicore-gen adopt on this path.

package commands

import (
	"github.com/ClaudioSchirmer/omnicore/application/configuration"
	"github.com/ClaudioSchirmer/omnicore/application/pipeline"
	fwresults "github.com/ClaudioSchirmer/omnicore/application/results"
	"github.com/ClaudioSchirmer/omnicore/domain"

	"github.com/ClaudioSchirmer/authcore/internal/application/dtos"
	appdomain "github.com/ClaudioSchirmer/authcore/internal/domain"
	"github.com/ClaudioSchirmer/authcore/internal/domain/aggregatevos"
)

// AddUserGroupCommand adds ONE entry to User's groups.
//
// The path carries the OWNER's id; the body is the entry. The aggregate is
// loaded, the entry appended, and the whole thing saved in one transaction —
// so the collection's invariants are checked against what will actually be
// stored.
type AddUserGroupCommand struct {
	pipeline.CommandWithBodyIDBase
	GroupID domain.ID
}

func (cmd *AddUserGroupCommand) ApplyTo(ctx *configuration.AppContext, e *appdomain.User) error {
	e.AddUserGroup(dtos.UserGroupInput{
		GroupID: cmd.GroupID,
	}.ToUserGroup())

	// Identity-derived state the rules read. It is never persisted.
	if id := ctx.Identity(); id != nil {
		e.RequestingUserID = id.Subject
		e.RequestingIdentityPresent = true
		e.RequestingTenant = id.TenantID()
		// The super-admin grant, not asked through HasPermission: that
		// method panics on a wildcard, since the CLAIM wildcards and the
		// question does not. The framework gives the wildcard its own
		// question, and this is it.
		e.RequestingMayCrossScope = id.IsSuperAdmin()
	}
	return nil
}

// AddUserGroupResult is the owner plus the entry as stored.
type AddUserGroupResult struct {
	UserID    domain.ID
	UserGroup UserGroupResult
}

func (cmd *AddUserGroupCommand) FromEntity(_ *configuration.AppContext, e *appdomain.User) (AddUserGroupResult, error) {
	items := domain.GetCurrentItemsOf[aggregatevos.UserGroup](e.GetAggregateRoot())
	out := AddUserGroupResult{UserID: *e.GetID()}
	// The entry as STORED, which is the last one the aggregate holds — the
	// domain may have normalised a value the caller sent.
	if len(items) > 0 {
		out.UserGroup = projectOneUserGroup(items[len(items)-1])
	}
	return out, nil
}

// RemoveUserGroupCommand takes ONE entry out of the collection.
//
// There is no body: the entry is named by the path. Whether the row is
// archived or deleted follows the child's own declaration, not this verb.
type RemoveUserGroupCommand struct {
	pipeline.CommandWithBodyIDBase
	UserGroupID string
}

func (cmd *RemoveUserGroupCommand) ApplyTo(ctx *configuration.AppContext, e *appdomain.User) error {
	e.RemoveUserGroupByID(cmd.UserGroupID)

	// Identity-derived state the rules read. It is never persisted.
	if id := ctx.Identity(); id != nil {
		e.RequestingUserID = id.Subject
		e.RequestingIdentityPresent = true
		e.RequestingTenant = id.TenantID()
		// The super-admin grant, not asked through HasPermission: that
		// method panics on a wildcard, since the CLAIM wildcards and the
		// question does not. The framework gives the wildcard its own
		// question, and this is it.
		e.RequestingMayCrossScope = id.IsSuperAdmin()
	}
	return nil
}

// FromEntity projects nothing: the entry RemoveUserGroupCommand named is
// gone, so the endpoint answers 204 — and the framework's NoBody projection
// is paired with a None on this side.
func (cmd *RemoveUserGroupCommand) FromEntity(_ *configuration.AppContext, _ *appdomain.User) (fwresults.None, error) {
	return fwresults.None{}, nil
}

// projectOneUserGroup renders one stored entry.
//
// Its plural twin projects the whole collection for the root's own verbs; this
// one exists because a per-entry verb answers with the entry it touched, not
// with everything around it.
func projectOneUserGroup(item aggregatevos.UserGroup) UserGroupResult {
	return UserGroupResult{
		ID:      item.GetID(),
		GroupID: item.GroupID,
	}
}
