// Code generated by omnicore-gen. DO NOT EDIT.
//
// The wire shapes of one ClientAllowedCIDR entry.
//
// entity:     Client
// spec:       specs/omnicore-gen/client.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-01
// checksum:   sha256:e711f1f9e65af37b22d937a3667d11650e83abbd31da36469f1c49c0e3438b60
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package dtos

import "github.com/ClaudioSchirmer/omnicore/domain"

// ClientAllowedCIDRRow is one entry of the allowedCIDRs collection as a read
// returns it.
type ClientAllowedCIDRRow struct {
	ID    *string `json:"id,omitempty"`
	CIDR  *string `json:"cidr,omitempty" exportLabelKey:"ClientAllowedCIDRCIDRField" example:"203.0.113.0/24"`
	Label *string `json:"label,omitempty" exportLabelKey:"ClientAllowedCIDRLabelField" example:"NAT gateway, sa-east-1"`
}

// ClientAllowedCIDRRequest is one entry sent in the allowedCIDRs collection.
//
// It carries no id: the server mints one.
//
// It declares no mapper of its own. This type is never the top of a request
// — it is reached as an element of the root's collection or through the
// per-entry verbs' embed — and the generic Request→Command mapping
// recurses into it by field name, so the entry travels without a seat here.
// The marker rides the type at the TOP of each walk.
type ClientAllowedCIDRRequest struct {
	CIDR  string `json:"cidr" example:"203.0.113.0/24"`
	Label string `json:"label" example:"NAT gateway, sa-east-1"`
}

// ClientAllowedCIDRResponse is one entry as stored, with the id it was given.
type ClientAllowedCIDRResponse struct {
	ID    domain.ID `json:"id"`
	CIDR  string    `json:"cidr" example:"203.0.113.0/24"`
	Label string    `json:"label" example:"NAT gateway, sa-east-1"`
}
