// Code generated by omnicore-gen. DO NOT EDIT.
//
// The wire shapes of one UserGroup entry.
//
// entity:     User
// spec:       specs/omnicore-gen/user.omnicore.yaml
// generator:  omnicore-gen
// generated:  2026-09-06
// checksum:   sha256:04928882ad75c13218b62501e4ba6f1c8b95e83c684e716e40f7711e439a81e8
//
// The line above is the Go convention that tells linters to skip this file.
// It is NOT a rule that the code may not change: this file is yours, in your
// repository, and improving it is ordinary work. What the generator asks is
// only that it be told.
//
// Changing the SPEC and regenerating is the cheaper of the two edits — it
// survives every later run. When the spec cannot say what you need and the
// framework can, edit this file: ask whoever owns the service first, and
// then run `omnicore-gen adopt <this path> -why '<what the spec could not
// express>'`. Adopting re-hashes the file as it now stands, so regeneration
// KEEPS your edit — and every later run prints the file as adopted, so it
// stays visible instead of becoming a surprise.
//
// Without that adopt, the next run notices the checksum no longer matches
// and REFUSES rather than overwriting — your work is never lost, but the
// run stops for whoever meets it.

package dtos

import (
	"github.com/ClaudioSchirmer/omnicore/domain"
	"time"
)

// UserGroupRow is one entry of the groups collection as a read returns it.
type UserGroupRow struct {
	ID              *string    `json:"id,omitempty"`
	GroupID         *domain.ID `json:"groupID,omitempty" exportLabelKey:"UserGroupGroupIDField" example:"0198f3e0-9c25-7a1f-b73d-5e08c4a29f61"`
	GroupKey        *string    `json:"groupKey,omitempty" exportLabelKey:"UserGroupGroupKeyField" example:"engineering"`
	GroupName       *string    `json:"groupName,omitempty" exportLabelKey:"UserGroupGroupNameField" example:"Engineering"`
	GroupArchivedAt *time.Time `json:"groupArchivedAt,omitempty" exportLabelKey:"UserGroupGroupArchivedAtField" example:"2026-01-31T12:00:00Z"`
}

// UserGroupRequest is one entry sent in the groups collection.
//
// It carries no id: the server mints one.
//
// It declares no mapper of its own. This type is never the top of a request
// — it is reached as an element of the root's collection or through the
// per-entry verbs' embed — and the generic Request→Command mapping
// recurses into it by field name, so the entry travels without a seat here.
// The marker rides the type at the TOP of each walk.
type UserGroupRequest struct {
	GroupID domain.ID `json:"groupID" example:"0198f3e0-9c25-7a1f-b73d-5e08c4a29f61"`
}

// UserGroupResponse is one entry as stored, with the id it was given.
type UserGroupResponse struct {
	ID      domain.ID `json:"id"`
	GroupID domain.ID `json:"groupID" example:"0198f3e0-9c25-7a1f-b73d-5e08c4a29f61"`
}
